import { useEffect } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { ArrowRight, BookOpen, Check, ClipboardCheck, FileText, Headphones, Languages, Menu, BookMarked, PanelsTopLeft, Smartphone, Sparkles, Youtube, Instagram, Mail } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";

const ORIGIN = "https://www.enonihongo.com";
const MASCOT = "https://raw.githubusercontent.com/enojapan-hub/eno-nihongo/assets/eno-mascot/public/eno-mascot.webp";
const DESCRIPTION = "Belajar bahasa Jepang dan persiapan JLPT N5–N1 bersama ENO NIHONGO: kanji, kosakata, bunpou, dokkai, choukai, latihan, dan simulasi JLPT.";
export const Route = createFileRoute("/")({head:()=>({meta:[{title:"ENO NIHONGO — Belajar Bahasa Jepang & JLPT N5–N1"},{name:"description",content:DESCRIPTION},{name:"robots",content:"index, follow, max-image-preview:large"}],links:[{rel:"canonical",href:`${ORIGIN}/`}]}),component:Home});

const features=[{icon:"漢",title:"Kanji",text:"Dari dasar hingga N1",box:"bg-emerald-50 text-emerald-700"},{icon:BookOpen,title:"Kosakata",text:"Ribuan kata dengan contoh",box:"bg-sky-50 text-sky-600"},{icon:FileText,title:"Bunpou",text:"Penjelasan mudah dipahami",box:"bg-rose-50 text-rose-600"},{icon:Headphones,title:"Choukai",text:"Latihan audio JLPT",box:"bg-violet-50 text-violet-600"},{icon:Languages,title:"Dokkai",text:"Tingkatkan kemampuan baca",box:"bg-amber-50 text-amber-600"},{icon:ClipboardCheck,title:"Simulasi JLPT",text:"Latihan soal seperti ujian",box:"bg-emerald-50 text-emerald-700"}];
const reasons=[{icon:BookMarked,title:"Materi Lengkap N5 – N1",text:"Semua yang kamu butuhkan dalam satu tempat",box:"bg-emerald-50 text-emerald-700"},{icon:PanelsTopLeft,title:"Latihan Interaktif",text:"Quiz, flashcard, dan simulasi JLPT",box:"bg-rose-50 text-rose-600"},{icon:Smartphone,title:"Akses Fleksibel",text:"Belajar kapan saja, di mana saja",box:"bg-emerald-50 text-emerald-700"},{icon:Sparkles,title:"Desain Modern",text:"Belajar jadi lebih fokus dan menyenangkan",box:"bg-sky-50 text-sky-600"}];

function Home(){useEffect(()=>{void(async()=>{try{const{data}=await supabase.auth.getSession();const user=data.session?.user;if(!user)return;const{data:profile}=await supabase.from("profiles").select("onboarding_completed,role").eq("id",user.id).maybeSingle();const role=profile?.role??"student";window.location.replace(role==="owner"||role==="admin"?"/admin":profile?.onboarding_completed?"/dashboard":"/onboarding")}catch{}})()},[]);
return <main className="min-h-screen bg-[#fffdf9] font-sans text-[#17231d]">
<header className="relative z-50 border-b border-black/[.04] bg-[#fffefb]"><div className="mx-auto flex h-[72px] max-w-[1120px] items-center justify-between px-5 sm:px-7"><a href="/" className="flex items-center gap-2.5"><img src="/enonihongo-logo-light.png" alt="Logo ENO NIHONGO" className="h-11 w-11 object-contain"/><div className="leading-none"><div className="text-[16px] font-extrabold text-[#17623f]">ENO NIHONGO</div><div className="mt-1 text-[8px] text-slate-400">Your Japanese Learning Hub</div></div></a><nav className="hidden items-center gap-6 text-[12px] font-semibold md:flex"><a href="/">Beranda</a><a href="#fitur">Fitur</a><a href="#materi">Materi</a><a href="/simulasi">Simulasi</a><a href="#akses">Harga</a><a href="#kenapa">Tentang</a></nav><div className="flex items-center gap-2"><a href="/auth" className="hidden rounded-full bg-[#167347] px-5 py-2.5 text-[12px] font-bold text-white md:block">Mulai Gratis</a><button aria-label="Menu" className="grid h-10 w-10 place-items-center rounded-full border border-slate-200 bg-white"><Menu className="size-[18px]"/></button></div></div></header>

<section className="relative overflow-hidden bg-[#eaf6ff]"><div className="absolute inset-0 bg-[radial-gradient(circle_at_85%_12%,rgba(255,190,210,.5),transparent_27%),radial-gradient(circle_at_18%_75%,rgba(183,225,184,.75),transparent_35%),linear-gradient(180deg,#dff2ff_0%,#eef9f0_65%,#f7fbf5_100%)]"/><div className="relative mx-auto grid max-w-[1120px] px-5 pt-8 md:min-h-[570px] md:grid-cols-[1.03fr_.97fr] md:items-center md:gap-8 md:px-7 md:py-12"><div className="z-10 max-w-[570px]"><p className="text-[10px] font-extrabold tracking-[.22em] text-[#237852]">BELAJAR · LATIH · CAPAI · JLPT</p><h1 className="mt-3 text-[35px] font-black leading-[1.02] tracking-[-.045em] sm:text-[46px] lg:text-[54px]">Wujudkan<br className="md:hidden"/> Kemampuan<br className="md:hidden"/> Bahasa Jepang<br className="md:hidden"/> <span className="text-[#167347]">Versi Terbaikmu</span></h1><p className="mt-4 max-w-[500px] text-[13px] leading-[1.6] text-slate-600 sm:text-[15px]">ENO NIHONGO adalah platform belajar bahasa Jepang lengkap untuk persiapan JLPT N5 – N1. Belajar lebih terarah, praktis, dan menyenangkan.</p><div className="mt-5 hidden gap-3 md:flex"><a href="/auth" className="flex items-center gap-2 rounded-full bg-[#087d48] px-5 py-3 text-[13px] font-bold text-white">Mulai Belajar dengan Google <ArrowRight className="size-4"/></a><a href="#fitur" className="flex items-center gap-2 rounded-full border border-[#087d48] bg-white/80 px-5 py-3 text-[13px] font-bold text-[#17623f]">Lihat Fitur <ArrowRight className="size-4"/></a></div></div><div className="relative mx-auto h-[335px] w-full max-w-[430px] md:h-[455px]"><div className="absolute right-0 top-2 z-20 rounded-[50%] bg-[#fffdf5]/95 px-5 py-4 text-center shadow-sm"><p className="text-[15px] font-black">一緒に<br/>頑張ろう!</p><p className="mt-1 text-[9px]">Ayo belajar<br/>bersama!</p></div><img src={MASCOT} alt="Maskot ENO NIHONGO" className="absolute bottom-0 right-[-10px] z-10 h-[315px] object-contain md:h-[440px]"/></div></div></section>

<section className="bg-white px-5 pb-4 pt-3 md:hidden"><div className="mx-auto grid max-w-md gap-2.5"><a href="/auth" className="flex items-center justify-center gap-2 rounded-full bg-[#087d48] px-5 py-3.5 text-[13px] font-bold text-white">ⓖ Mulai Belajar dengan Google <ArrowRight className="size-4"/></a><a href="#fitur" className="flex items-center justify-center gap-2 rounded-full border border-[#087d48] px-5 py-3 text-[13px] font-bold text-[#17623f]">Lihat Fitur <ArrowRight className="size-4"/></a></div></section>

<section id="fitur" className="bg-white px-4 py-5"><div className="mx-auto grid max-w-[1060px] grid-cols-3 gap-2 md:grid-cols-6 md:gap-3">{features.map(f=>{const I=f.icon;return <article key={f.title} className="rounded-xl bg-white px-1 py-3 text-center shadow-[0_5px_22px_rgba(35,70,50,.06)]"><div className={`mx-auto grid size-11 place-items-center rounded-xl ${f.box}`}>{typeof I==="string"?<span className="text-xl font-black">{I}</span>:<I className="size-5"/>}</div><h2 className="mt-2 text-[11px] font-extrabold">{f.title}</h2><p className="mt-1 text-[9px] leading-[1.35] text-slate-500">{f.text}</p></article>})}</div></section>

<section id="materi" className="bg-white px-4 py-3"><div className="relative mx-auto max-w-[1060px] overflow-hidden rounded-[20px] bg-[#eef8f1] p-5 sm:p-7"><span className="absolute bottom-0 right-3 text-[7rem] font-black text-[#167347]/10">夢</span><div className="relative max-w-[570px]"><h2 className="text-[21px] font-black leading-[1.08]">Belajar Bahasa Jepang<br/>Jadi Lebih Mudah</h2><p className="mt-3 text-[12px] leading-[1.5] text-slate-600">Materi lengkap, latihan interaktif, dan simulasi JLPT dalam satu tempat. Dirancang untuk membantu kamu mencapai target, langkah demi langkah.</p><div className="mt-4 grid gap-2 text-[11px] font-semibold">{["Materi terstruktur N5 – N1","Contoh kalimat & audio","Pantau progres belajar","Akses di mana saja, kapan saja"].map(x=><p key={x} className="flex items-center gap-2"><span className="grid size-5 place-items-center rounded-full bg-[#07804b] text-white"><Check className="size-3"/></span>{x}</p>)}</div></div></div></section>

<section id="akses" className="bg-white px-4 py-6"><div className="mx-auto max-w-[1060px]"><h2 className="text-[19px] font-black">Mulai Perjalanan Belajarmu Sekarang</h2><p className="mt-1 text-[11px] text-slate-500">Gratis untuk memulai. Tingkatkan potensimu dengan fitur premium.</p><div className="mt-4 grid grid-cols-2 gap-2.5"><article className="rounded-xl bg-[#fbfcfb] p-3 shadow-sm"><div className="flex gap-2"><span className="text-xl">🌱</span><div><h3 className="text-[12px] font-black">Gratis</h3><p className="text-[9px] text-slate-500">Akses materi dasar & latihan harian</p></div></div><a href="/auth" className="mt-3 flex justify-center rounded-lg border border-[#087d48] py-2 text-[10px] font-bold text-[#087d48]">Mulai Gratis →</a></article><article className="rounded-xl bg-[#fffdf7] p-3 shadow-sm"><div className="flex gap-2"><span className="text-xl">👑</span><div><h3 className="text-[12px] font-black">Premium</h3><p className="text-[9px] text-slate-500">Akses lengkap N5 – N1, simulasi & lainnya</p></div></div><a href="/auth" className="mt-3 flex justify-center rounded-lg bg-[#087d48] py-2 text-[10px] font-bold text-white">Lihat Paket →</a></article></div></div></section>

<section id="kenapa" className="border-t border-slate-100 bg-[#f8fcfa] px-4 py-7"><div className="mx-auto max-w-[1060px]"><h2 className="text-[20px] font-black tracking-[-.025em]">Kenapa Memilih ENO NIHONGO?</h2><p className="mt-1 text-[11px] text-slate-500">Dirancang khusus untuk pembelajar bahasa Jepang, dari pemula hingga mahir.</p><div className="mt-4 grid grid-cols-2 gap-2.5 md:grid-cols-4 md:gap-3">{reasons.map(r=>{const I=r.icon;return <article key={r.title} className="rounded-xl bg-white p-4 shadow-[0_5px_22px_rgba(35,70,50,.05)]"><div className={`grid size-9 place-items-center rounded-xl ${r.box}`}><I className="size-[18px]"/></div><h3 className="mt-2 text-[11px] font-black leading-tight">{r.title}</h3><p className="mt-1 text-[9px] leading-[1.45] text-slate-500">{r.text}</p></article>})}</div>
<div className="relative mt-5 min-h-[180px] overflow-hidden rounded-[18px] bg-[radial-gradient(circle_at_85%_18%,rgba(255,180,200,.35),transparent_28%),linear-gradient(110deg,#087446_0%,#17814f_45%,#3c8b5c_100%)] px-5 py-6 text-white md:min-h-[190px] md:px-8"><div className="absolute inset-0 opacity-20 [background-image:radial-gradient(circle_at_70%_80%,#fff_0,transparent_2%),radial-gradient(circle_at_92%_20%,#ffd1dc_0,transparent_3%)]"/><div className="relative z-10 max-w-[310px]"><h2 className="text-[21px] font-black leading-[1.05] md:text-[25px]">Siap Memulai Perjalanan<br/>Bahasa Jepangmu?</h2><p className="mt-2 text-[10px] leading-4 text-white/90 md:text-[11px]">Bergabunglah dengan ENO NIHONGO sekarang dan wujudkan kemampuan terbaikmu!</p><a href="/auth" className="mt-4 inline-flex items-center gap-2 rounded-full bg-white px-6 py-2.5 text-[11px] font-bold text-[#087446]">Mulai Gratis <ArrowRight className="size-3.5"/></a></div><img src={MASCOT} alt="Maskot ENO NIHONGO" className="absolute bottom-[-20px] right-[-8px] z-[5] h-[165px] object-contain md:right-[6%] md:h-[210px]"/><div className="absolute right-4 top-6 z-10 hidden text-xl font-black leading-tight md:block">一緒に<br/>頑張ろう!</div></div></div></section>

<footer className="bg-white px-5 py-8"><div className="mx-auto grid max-w-[1060px] gap-7 border-b border-slate-100 pb-7 md:grid-cols-[1.6fr_.8fr_.9fr_1fr]"><div><div className="flex items-center gap-2"><img src="/enonihongo-logo-light.png" alt="ENO NIHONGO" className="size-10 object-contain"/><div><div className="text-[13px] font-black text-[#17623f]">ENO NIHONGO</div><div className="text-[8px] text-slate-400">Your Japanese Learning Hub</div></div></div><p className="mt-3 text-[9px] text-slate-500">Belajar lebih jauh, capai lebih banyak.</p></div><div><h3 className="text-[11px] font-black">Menu</h3><div className="mt-2 grid gap-1 text-[9px] text-slate-500"><a href="/">Beranda</a><a href="#fitur">Fitur</a><a href="#materi">Materi</a><a href="/simulasi">Simulasi</a><a href="#akses">Harga</a></div></div><div><h3 className="text-[11px] font-black">Bantuan</h3><div className="mt-2 grid gap-1 text-[9px] text-slate-500"><span>Pusat Bantuan</span><span>Kontak</span><span>Kebijakan Privasi</span><span>Syarat Layanan</span></div></div><div><h3 className="text-[11px] font-black">Ikuti Kami</h3><div className="mt-3 flex gap-3 text-slate-600"><Youtube className="size-4"/><Instagram className="size-4"/><Mail className="size-4"/></div></div></div><div className="mx-auto flex max-w-[1060px] flex-col gap-2 pt-5 text-[8px] text-slate-400 sm:flex-row sm:justify-between"><span>© {new Date().getFullYear()} ENO NIHONGO. Semua hak dilindungi.</span><span>Belajar hari ini, masa depan lebih cerah.</span></div></footer>
</main>}
