import { useState } from "react";
import { createFileRoute, Link } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { BookOpen, Crown, Database, FileQuestion, Headphones, Languages, LayoutDashboard, ShieldCheck, Users } from "lucide-react";
import { AppShell } from "@/components/layout/AppShell";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { supabase } from "@/integrations/supabase/client";

export const Route=createFileRoute("/_authenticated/admin")({component:AdminPage});
type Overview={users:number;free_users:number;premium_users:number;lifetime_users:number;kanji:number;vocabulary:number;grammar:number;reading:number;listening:number};
type Section="users"|"kanji"|"vocabulary"|"grammar"|"reading"|"listening"|"questions";
const sections:[Section,string,any][]=[["users","Pengguna",Users],["kanji","Kanji",BookOpen],["vocabulary","Kosakata",Languages],["grammar","Bunpou",BookOpen],["reading","Dokkai",BookOpen],["listening","Choukai",Headphones],["questions","Soal JLPT",FileQuestion]];
function AdminPage(){
 const qc=useQueryClient();const[section,setSection]=useState<Section>("users");const[level,setLevel]=useState<string>("");
 const overview=useQuery({queryKey:["admin-overview"],queryFn:async()=>{const{data,error}=await(supabase as any).rpc("get_admin_overview");if(error)throw error;return data as Overview},retry:false});
 const rows=useQuery({queryKey:["admin-console",section,level],queryFn:async()=>{const{data,error}=await(supabase as any).rpc("get_admin_console_data",{p_section:section,p_level:level||null});if(error)throw error;return(data??[]) as any[]},enabled:!overview.isError,retry:false});
 const publish=useMutation({mutationFn:async(v:{kind:string;id:string;published:boolean})=>{const{error}=await(supabase as any).rpc("admin_set_content_published",{p_kind:v.kind,p_id:v.id,p_published:v.published});if(error)throw error},onSuccess:()=>{void qc.invalidateQueries({queryKey:["admin-console"]});void qc.invalidateQueries({queryKey:["admin-overview"]})}});
 const access=useMutation({mutationFn:async(v:{id:string;role?:string;plan?:string})=>{const{error}=await(supabase as any).rpc("admin_update_user_access",{p_user_id:v.id,p_role:v.role??null,p_plan:v.plan??null});if(error)throw error},onSuccess:()=>void qc.invalidateQueries({queryKey:["admin-console","users"]})});
 if(overview.isLoading)return <AppShell title="Admin"><p className="py-12 text-center text-sm text-muted-foreground">Memeriksa akses dan memuat panel admin…</p></AppShell>;
 if(overview.isError)return <AppShell title="Admin"><div className="mx-auto max-w-md py-12 text-center"><ShieldCheck className="mx-auto size-10 text-destructive"/><h1 className="mt-3 font-bold">Akses admin diperlukan</h1><p className="mt-2 text-xs text-muted-foreground">Panel ini hanya tersedia untuk akun owner/admin yang terdaftar di database.</p><Button asChild className="mt-5"><Link to="/dashboard">Kembali ke Home</Link></Button></div></AppShell>;
 const o=overview.data!;
 return <AppShell title="Admin" compact><div className="mx-auto max-w-5xl space-y-4 pb-8">
  <div className="rounded-3xl bg-primary p-5 text-primary-foreground"><div className="flex items-center gap-2 text-xs font-bold"><Crown className="size-4"/>OWNER / ADMIN</div><h1 className="mt-2 text-2xl font-black">Panel Admin</h1><p className="mt-1 text-xs opacity-80">Pusat kontrol operasional ENO NIHONGO.</p></div>
  <div className="grid grid-cols-2 gap-2 sm:grid-cols-4"><Metric label="Pengguna" value={o.users}/><Metric label="Free" value={o.free_users}/><Metric label="Premium" value={o.premium_users}/><Metric label="Lifetime" value={o.lifetime_users}/></div>
  <div className="grid grid-cols-2 gap-2 sm:grid-cols-5"><Metric label="Kanji" value={o.kanji}/><Metric label="Kosakata" value={o.vocabulary}/><Metric label="Bunpou" value={o.grammar}/><Metric label="Dokkai" value={o.reading}/><Metric label="Choukai" value={o.listening}/></div>
  <div className="flex gap-2 overflow-x-auto pb-1">{sections.map(([id,label,Icon])=><Button key={id} size="sm" variant={section===id?"default":"outline"} className="shrink-0 rounded-xl" onClick={()=>setSection(id)}><Icon className="mr-1.5 size-3.5"/>{label}</Button>)}</div>
  {section!=="users"&&<div className="flex gap-2">{["","N5","N4","N3","N2","N1"].map(x=><Button key={x||"all"} size="sm" variant={level===x?"default":"outline"} onClick={()=>setLevel(x)} className="rounded-xl">{x||"Semua"}</Button>)}</div>}
  <Card className="rounded-2xl"><CardContent className="p-3"><div className="mb-3 flex items-center justify-between"><div><p className="text-sm font-bold">{sections.find(x=>x[0]===section)?.[1]}</p><p className="text-[10px] text-muted-foreground">{rows.data?.length??0} data dimuat</p></div><Button asChild variant="outline" size="sm" className="rounded-xl"><Link to="/admin-terjemahan"><Languages className="mr-1.5 size-3.5"/>Terjemahan</Link></Button></div>
   {rows.isLoading?<p className="py-8 text-center text-xs text-muted-foreground">Memuat data…</p>:rows.isError?<p className="py-8 text-center text-xs text-destructive">Data gagal dimuat.</p>:<div className="space-y-2">{rows.data?.map((r:any)=>section==="users"?<UserRow key={r.id} r={r} busy={access.isPending} update={(v)=>access.mutate(v)}/>:<ContentRow key={r.id} r={r} section={section} busy={publish.isPending} toggle={()=>publish.mutate({kind:section,id:r.id,published:!r.is_published})}/>)}</div>}
  </CardContent></Card>
  <Card className="rounded-2xl border-primary/20 bg-primary/[0.04]"><CardContent className="flex items-start gap-3 p-4"><Database className="mt-0.5 size-5 text-primary"/><div><p className="text-xs font-bold">Keamanan database aktif</p><p className="mt-1 text-[10px] leading-4 text-muted-foreground">Operasi admin dijalankan melalui RPC yang memeriksa sesi dan role owner/admin di database. Pengguna biasa tidak mendapat akses admin.</p></div></CardContent></Card>
 </div></AppShell>;
}
function Metric({label,value}:{label:string;value:number}){return <Card className="rounded-2xl"><CardContent className="p-3"><p className="text-[9px] text-muted-foreground">{label}</p><p className="mt-1 text-xl font-black">{Number(value??0).toLocaleString("id-ID")}</p></CardContent></Card>}
function UserRow({r,busy,update}:{r:any;busy:boolean;update:(v:any)=>void}){return <div className="rounded-xl border p-3"><div className="flex items-center justify-between gap-2"><div className="min-w-0"><p className="truncate text-xs font-bold">{r.display_name||"Tanpa nama"}</p><p className="text-[9px] text-muted-foreground">{r.target_level||"N5"} · {r.country||"—"} · {r.role||"student"}</p></div><span className="rounded-full bg-primary/10 px-2 py-1 text-[9px] font-bold text-primary">{r.plan||"free"}</span></div><div className="mt-2 flex flex-wrap gap-1.5"><Button disabled={busy} size="sm" variant="outline" onClick={()=>update({id:r.id,plan:"free"})}>Free</Button><Button disabled={busy} size="sm" variant="outline" onClick={()=>update({id:r.id,plan:"premium"})}>Premium</Button><Button disabled={busy} size="sm" variant="outline" onClick={()=>update({id:r.id,plan:"lifetime"})}>Lifetime</Button><Button disabled={busy} size="sm" variant="outline" onClick={()=>update({id:r.id,role:"student"})}>Student</Button><Button disabled={busy} size="sm" variant="outline" onClick={()=>update({id:r.id,role:"admin"})}>Admin</Button></div></div>}
function ContentRow({r,section,busy,toggle}:{r:any;section:Section;busy:boolean;toggle:()=>void}){const title=r.character||r.term||r.pattern||r.title||r.prompt_jp||`ID ${r.id}`;const sub=[r.level,r.reading,r.meaning_id,r.section,r.question_type].filter(Boolean).join(" · ");return <div className="flex items-center gap-3 rounded-xl border p-3"><div className="min-w-0 flex-1"><p className="truncate text-xs font-bold">{title}</p><p className="truncate text-[9px] text-muted-foreground">{sub||section}</p></div>{section!=="questions"&&<Button disabled={busy} size="sm" variant={r.is_published?"default":"outline"} onClick={toggle}>{r.is_published?"Tayang":"Draft"}</Button>}</div>}
