import { createFileRoute } from "@tanstack/react-router";
import { useQuery,useQueryClient } from "@tanstack/react-query";
import { CheckCircle2,Image,Users,XCircle } from "lucide-react";
import { AppShell } from "@/components/layout/AppShell";
import { Card,CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { supabase } from "@/integrations/supabase/client";
export const Route=createFileRoute("/_authenticated/admin-kelas")({component:Page});
function Page(){const qc=useQueryClient();const q=useQuery({queryKey:["admin-classes"],queryFn:async()=>{const{data,error}=await(supabase as any).from("classes").select("*").order("created_at",{ascending:false});if(error)throw error;return data??[]}});async function status(id:string,value:string){await(supabase as any).from("classes").update({status:value,updated_at:new Date().toISOString()}).eq("id",id);void qc.invalidateQueries({queryKey:["admin-classes"]})}return <AppShell title="Kelas" backTo="/admin"><div className="space-y-4"><div><h1 className="text-xl font-black">Kelola Kelas</h1><p className="text-xs text-muted-foreground">Review kelas guru, banner, status publikasi dan peserta.</p></div><div className="grid gap-3 sm:grid-cols-2"><Card><CardContent className="p-4"><Image className="mb-2 size-5 text-primary"/><p className="font-bold">Banner Halaman Kelas</p><p className="text-[10px] text-muted-foreground">Banner utama, CTA, periode tayang dan urutan.</p></CardContent></Card><Card><CardContent className="p-4"><Users className="mb-2 size-5 text-primary"/><p className="font-bold">Kelas Guru</p><p className="text-[10px] text-muted-foreground">{(q.data??[]).length} kelas terdaftar.</p></CardContent></Card></div><div className="space-y-2">{(q.data??[]).map((c:any)=><Card key={c.id}><CardContent className="flex items-center gap-3 p-3">{c.banner_url&&<img src={c.banner_url} className="h-14 w-24 rounded-xl object-cover" alt=""/>}<div className="min-w-0 flex-1"><p className="truncate text-xs font-bold">{c.title}</p><p className="text-[10px] text-muted-foreground">{c.level} · {c.status} · {Number(c.price)>0?`${c.currency} ${c.price}`:'Gratis'}</p></div>{c.status!=="published"&&<Button size="sm" onClick={()=>status(c.id,"published")}><CheckCircle2 className="mr-1 size-3"/>Publish</Button>}{c.status!=="rejected"&&<Button size="sm" variant="outline" onClick={()=>status(c.id,"rejected")}><XCircle className="size-3"/></Button>}</CardContent></Card>)}</div></div></AppShell>}
