import { createFileRoute } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { useMemo, useState } from "react";
import { BookOpen, Brain, ChevronRight, FileText, Headphones, Languages, NotebookTabs, Search, Tags, X } from "lucide-react";
import { AppShell } from "@/components/layout/AppShell";
import { fetchGrammarList, fetchKanjiList, fetchMyProgress, type Level } from "@/lib/learn-queries";
import { fetchVocabListResilient } from "@/lib/vocab-resilient";
import { fetchTargetLevel } from "@/lib/target-level";
import { supabase } from "@/integrations/supabase/client";

export const Route=createFileRoute("/_authenticated/belajar")({head:()=>({meta:[{title:"Materi — ENO NIHONGO"}]}),component:BelajarPage});
const norm=(v:unknown)=>String(v??"").toLocaleLowerCase().trim();
const pct=(a:number,b:number)=>b?Math.min(100,Math.round(a/b*100)):0;
async function fetchExtra(level:Level){const{data:cats,error}=await supabase.from("vocabulary_categories").select("id,slug,canonical_slug,label_ja,label_id,name_id,sort_order").eq("is_active",true).order("sort_order");if(error)throw error;if(!cats?.length)return[];const{data:links,error:e}=await supabase.from("vocabulary_category_links").select("category_id,vocabulary:vocabulary_id(id,level,is_published)").in("category_id",cats.map((x:any)=>x.id));if(e)throw e;const n=new Map<string,number>();for(const x of links??[]){const v:any=(x as any).vocabulary;if(v?.level===level&&v?.is_published)n.set((x as any).category_id,(n.get((x as any).category_id)??0)+1)}return cats.map((x:any)=>({id:x.id,slug:x.canonical_slug||x.slug,label:x.label_id||x.name_id||x.label_ja||x.slug,count:n.get(x.id)??0})).filter((x:any)=>x.count>0)}
function BelajarPage(){
 const[search,setSearch]=useState("");
 const target=useQuery({queryKey:["target-level"],queryFn:fetchTargetLevel,retry:1});const level=target.data as Level|undefined;const ready=!!level;
 const kanji=useQuery({queryKey:["materi-kanji",level],queryFn:()=>fetchKanjiList(level!),enabled:ready});
 const vocab=useQuery({queryKey:["materi-vocab",level],queryFn:()=>fetchVocabListResilient(level!),enabled:ready,retry:1});
 const grammar=useQuery({queryKey:["materi-grammar",level],queryFn:()=>fetchGrammarList(level!),enabled:ready});
 const progress=useQuery({queryKey:["my-progress"],queryFn:fetchMyProgress,enabled:ready});
 const extra=useQuery({queryKey:["materi-extra-vocab",level],queryFn:()=>fetchExtra(level!),enabled:ready});
 const rows=progress.data?.progress??[];const learned=(t:string)=>rows.filter((r:any)=>r.level===level&&r.item_type===t&&(r.status==="learning"||r.status==="mastered")).length;
 const q=norm(search);const results=useMemo(()=>{if(!q)return[];const out:Array<{type:string,title:string,sub:string,to:string}>=[];for(const x of (kanji.data??[]) as any[])if([x.character,x.meaning_id,x.onyomi,x.kunyomi].some(v=>norm(v).includes(q)))out.push({type:"Kanji",title:x.character,sub:x.meaning_id,to:`/kanji/${x.id}`});for(const x of (vocab.data??[]) as any[])if([x.term,x.reading,x.romaji,x.meaning_id].some(v=>norm(v).includes(q)))out.push({type:"Kosakata",title:x.term,sub:[x.reading,x.meaning_id].filter(Boolean).join(" · "),to:`/kotoba?id=${x.id}`});for(const x of (grammar.data??[]) as any[])if([x.pattern,x.meaning_id,x.structure].some(v=>norm(v).includes(q)))out.push({type:"Bunpou",title:x.pattern,sub:x.meaning_id,to:`/bunpo?id=${x.id}`});return out.slice(0,30)},[q,kanji.data,vocab.data,grammar.data]);
 const cards=[
  {to:"/kana",label:"Hiragana & Katakana",icon:Languages,tone:"bg-teal-100 text-teal-700",meta:"Kana lengkap · romaji dapat disembunyikan",total:0,done:0,showLevel:false},
  {to:"/kanji",label:"Kanji",icon:"井",tone:"bg-emerald-100 text-emerald-700",meta:`${kanji.data?.length??0} kanji · ${learned("kanji")} dipelajari`,total:kanji.data?.length??0,done:learned("kanji"),showLevel:true},
  {to:"/kotoba",label:"Kosakata",icon:BookOpen,tone:"bg-rose-100 text-rose-600",meta:`${vocab.data?.length??0} kata · ${learned("vocabulary")} dipelajari`,total:vocab.data?.length??0,done:learned("vocabulary"),showLevel:true},
  {to:"/bunpo",label:"Bunpou",icon:FileText,tone:"bg-blue-100 text-blue-600",meta:`${grammar.data?.length??0} pola · ${learned("grammar")} dipelajari`,total:grammar.data?.length??0,done:learned("grammar"),showLevel:true},
  {to:"/hafalan",label:"Mode Hafalan",icon:Brain,tone:"bg-violet-100 text-violet-700",meta:"Active recall · SRS · kartu lemah · mode campuran",total:0,done:0,showLevel:true}
 ] as const;
 return <AppShell compact title="Materi"><div className="mx-auto w-full max-w-md pb-2">
  <section className="mb-3 flex items-end justify-between gap-3"><div><h1 className="text-[20px] font-bold">Materi</h1><p className="mt-0.5 text-[10px] text-muted-foreground">Materi JLPT mengikuti level di Profil</p></div>{level&&<span className="rounded-full bg-primary/10 px-2.5 py-1 text-[10px] font-bold text-primary">{level}</span>}</section>
  {target.isLoading?<p className="py-8 text-center text-xs text-muted-foreground">Memuat level profil…</p>:!level?<p className="rounded-xl border p-3 text-center text-[11px] text-destructive">Atur target JLPT di Profil terlebih dahulu.</p>:<>
   <div className="relative mb-3"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder={`Cari kanji, kosakata, atau bunpou ${level}...`} className="h-11 w-full rounded-2xl border bg-card pl-9 pr-9 text-[11px] outline-none"/>{search&&<button onClick={()=>setSearch("")} className="absolute right-3 top-1/2 -translate-y-1/2"><X className="size-4 text-muted-foreground"/></button>}</div>
   {q?<section className="space-y-1.5">{results.length?results.map((r,i)=><a key={`${r.to}-${i}`} href={r.to} className="flex items-center gap-3 rounded-xl border bg-card px-3 py-2.5"><span className="w-16 text-[8px] font-bold uppercase text-primary">{r.type}</span><div className="min-w-0 flex-1"><p className="truncate font-jp text-[12px] font-semibold">{r.title}</p><p className="truncate text-[9px] text-muted-foreground">{r.sub}</p></div><ChevronRight className="size-4 text-muted-foreground"/></a>):<p className="rounded-xl border p-5 text-center text-[10px] text-muted-foreground">Tidak ada materi yang cocok.</p>}</section>:<div className="space-y-2">
    {cards.map(card=>{const Icon=card.icon;const p=pct(card.done,card.total);return <a key={card.to} href={card.to} className="flex items-center gap-3 rounded-2xl border bg-card px-3 py-3"><span className={`grid size-12 shrink-0 place-items-center rounded-xl ${card.tone}`}>{typeof Icon==="string"?<span className="font-jp text-[26px] font-bold">{Icon}</span>:<Icon className="size-6"/>}</span><div className="min-w-0 flex-1"><div className="flex justify-between gap-2"><p className="text-[12px] font-bold">{card.label}{card.showLevel?` ${level}`:""}</p><ChevronRight className="size-4 text-muted-foreground"/></div><p className="mt-0.5 truncate text-[9px] text-muted-foreground">{card.meta}</p>{card.total>0&&<div className="mt-2 flex items-center gap-2"><div className="h-1.5 flex-1 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary" style={{width:`${p}%`}}/></div><span className="w-8 text-right text-[9px]">{p}%</span></div>}</div></a>})}
    {[{label:"Dokkai",icon:NotebookTabs,tone:"bg-orange-100 text-orange-600"},{label:"Choukai",icon:Headphones,tone:"bg-sky-100 text-sky-600"}].map(({label,icon:Icon,tone})=><div key={label} aria-disabled="true" className="flex items-center gap-3 rounded-2xl border bg-card/60 px-3 py-3 opacity-70"><span className={`grid size-12 place-items-center rounded-xl ${tone}`}><Icon className="size-6"/></span><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-2"><p className="text-[12px] font-bold">{label} {level}</p><span className="rounded-full bg-amber-100 px-2 py-1 text-[8px] font-bold text-amber-700">Dalam pengembangan</span></div><p className="mt-1 text-[9px] text-muted-foreground">Belum tersedia · materi tidak dihapus</p></div></div>)}
    <section className="rounded-2xl border bg-card p-3"><div className="mb-2 flex items-center gap-2"><span className="grid size-8 place-items-center rounded-xl bg-violet-100 text-violet-600"><Tags className="size-4"/></span><div><p className="text-[12px] font-bold">Kotoba Tambahan {level}</p><p className="text-[9px] text-muted-foreground">Kata benda, kerja, sifat, keterangan, tema, dan lainnya</p></div></div>{extra.isLoading?<p className="py-2 text-center text-[9px] text-muted-foreground">Memuat kategori…</p>:extra.isError?<p className="py-2 text-center text-[9px] text-muted-foreground">Kategori belum dapat dimuat.</p>:<div className="grid grid-cols-2 gap-1.5">{(extra.data??[]).map((cat:any)=><a key={cat.id} href={`/kotoba?category=${encodeURIComponent(cat.slug)}`} className="flex min-w-0 items-center justify-between gap-2 rounded-xl bg-muted/45 px-2.5 py-2"><span className="truncate text-[10px] font-medium">{cat.label}</span><span className="rounded-full bg-background px-1.5 py-0.5 text-[8px] font-bold text-muted-foreground">{cat.count}</span></a>)}</div>}</section>
   </div>}
  </>}
  {!q&&<div className="mt-3 rounded-2xl bg-emerald-50/80 px-4 py-3 text-center"><p className="text-[10px] text-emerald-900">Konsistensi hari ini, hasil luar biasa nanti.</p><p lang="ja" className="mt-1 font-jp text-[11px] font-semibold text-emerald-700">継続は力なり</p></div>}
 </div></AppShell>
}
