import { createFileRoute } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Check, Headphones, Play, RotateCcw, Square, X } from "lucide-react";
import { useEffect, useState } from "react";
import { AppShell } from "@/components/layout/AppShell";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { supabase } from "@/integrations/supabase/client";
import type { Level } from "@/lib/learn-queries";
import { fetchTargetLevel } from "@/lib/target-level";
import { markContentMastered } from "@/lib/progress-actions";

export const Route = createFileRoute("/_authenticated/choukai")({ component: ChoukaiPage });
type Item={id:string;title:string;level:string;duration_seconds?:number|null;audio_url?:string|null;transcript_jp?:string|null;translation_id?:string|null;source?:string|null;source_book?:string|null;lesson_number?:number|null;lesson_title?:string|null};
type Question={id:string;listening_id:string;prompt:string;prompt_id?:string|null;choices:string[];choices_id?:string[]|null;correct_index:number;explanation_id?:string|null};
type QuestionRow={id:string;listening_id:string|null;prompt:string;prompt_id:string|null;choices:unknown;choices_id:string[]|null;correct_index:number;explanation_id:string|null};
async function fetchChoukaiItems(level:Level):Promise<Item[]>{const{data,error}=await supabase.from("listening_items").select("id,title,level,duration_seconds,audio_url,transcript_jp,translation_id,source,source_book,lesson_number,lesson_title,sort_order").eq("is_published",true).eq("level",level).order("lesson_number",{ascending:true,nullsFirst:false}).order("sort_order",{ascending:true});if(error)throw new Error(error.message);return(data??[]).filter(item=>Boolean(item.audio_url?.trim())||Boolean(item.transcript_jp?.trim())) as Item[]}
async function fetchListeningQuestions(level:Level):Promise<Question[]>{const{data,error}=await supabase.from("questions").select("id,listening_id,prompt,prompt_id,choices,choices_id,correct_index,explanation_id").eq("is_published",true).eq("level",level).eq("skill","listening").not("listening_id","is",null);if(error)throw new Error(error.message);return((data??[]) as QuestionRow[]).filter((q):q is QuestionRow&{listening_id:string}=>Boolean(q.listening_id)).map(q=>({...q,listening_id:q.listening_id,prompt:q.prompt_id?.trim()||q.prompt,choices:Array.isArray(q.choices_id)&&q.choices_id.length?q.choices_id:Array.isArray(q.choices)?q.choices.map(String):[]}))}
function ChoukaiPage(){const qc=useQueryClient();const target=useQuery({queryKey:["target-level"],queryFn:fetchTargetLevel,retry:1});const level=target.data;const itemsQ=useQuery({queryKey:["choukai-canonical",level],queryFn:()=>fetchChoukaiItems(level!),enabled:Boolean(level),retry:1});const questionsQ=useQuery({queryKey:["choukai-questions",level],queryFn:()=>fetchListeningQuestions(level!),enabled:Boolean(level),retry:1});const items=itemsQ.data??[],questions=questionsQ.data??[];const[active,setActive]=useState<string|null>(null),[showTranscript,setShowTranscript]=useState<Record<string,boolean>>({}),[speech,setSpeech]=useState<SpeechSynthesisUtterance|null>(null),[completed,setCompleted]=useState<Record<string,boolean>>({}),[answers,setAnswers]=useState<Record<string,number>>({}),[checked,setChecked]=useState<Record<string,boolean>>({});
 const completeMutation=useMutation({mutationFn:(item:Item)=>markContentMastered({itemType:"listening",itemId:item.id,level:item.level as Level,durationSeconds:Math.max(60,Number(item.duration_seconds??60))}),onSuccess:(_,item)=>{setCompleted(v=>({...v,[item.id]:true}));void qc.invalidateQueries({queryKey:["dashboard-live"]});void qc.invalidateQueries({queryKey:["my-progress"]})}});useEffect(()=>()=>window.speechSynthesis?.cancel(),[]);
 const stop=()=>{window.speechSynthesis?.cancel();document.querySelectorAll<HTMLAudioElement>("audio[data-choukai-audio]").forEach(a=>a.pause());if(speech)speech.onend=null;setSpeech(null);setActive(null)};const play=(item:Item)=>{stop();if(item.audio_url){const a=document.getElementById(`audio-${item.id}`) as HTMLAudioElement|null;if(a){a.currentTime=0;void a.play();setActive(item.id);return}}if(!item.transcript_jp||!window.speechSynthesis)return;const u=new SpeechSynthesisUtterance(item.transcript_jp);u.lang="ja-JP";u.rate=.85;u.onend=()=>setActive(null);u.onerror=()=>setActive(null);setSpeech(u);setActive(item.id);window.speechSynthesis.speak(u)};
 return <AppShell title={`聴解 · Chōkai${level?` ${level}`:""}`} description="Latihan menyimak mengikuti level JLPT yang dipilih di Profil." backTo="/belajar" backLabel="Materi"><div className="mx-auto max-w-3xl space-y-4"><div className="rounded-2xl border border-primary/15 bg-primary/[0.045] p-4 sm:p-5"><div className="flex items-start gap-3"><div className="grid size-10 shrink-0 place-items-center rounded-xl bg-primary/10 text-primary"><Headphones className="size-5"/></div><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-3"><h2 className="font-semibold">Latihan menyimak</h2>{level&&<Badge variant="secondary">{level}</Badge>}</div><p className="mt-1 text-xs leading-5 text-muted-foreground">Audio, soal, hasil dan transkrip mengikuti level profil. Audio sumber diprioritaskan; TTS Jepang hanya dipakai bila audio belum tersedia.</p></div></div></div>
 {target.isLoading&&<p className="py-6 text-center text-xs text-muted-foreground">Memuat level profil…</p>}{target.isError&&<div className="rounded-2xl border border-destructive/30 bg-destructive/5 p-5 text-center"><p className="text-sm font-semibold text-destructive">Level profil tidak dapat dimuat.</p></div>}{itemsQ.isLoading&&<p className="py-6 text-center text-xs text-muted-foreground">Memuat latihan…</p>}{itemsQ.error&&<div className="rounded-2xl border border-destructive/30 bg-destructive/5 p-5 text-center"><p className="text-sm font-semibold text-destructive">Latihan Chōkai gagal dimuat.</p></div>}{!target.isLoading&&!target.isError&&!itemsQ.isLoading&&!itemsQ.error&&items.length===0&&<div className="rounded-2xl border border-dashed p-7 text-center"><Headphones className="mx-auto size-7 text-muted-foreground"/><p className="mt-3 text-sm font-semibold">Materi Chōkai {level} belum tersedia.</p><p className="mt-1 text-xs leading-5 text-muted-foreground">Database saat ini belum memiliki audio/transkrip Chōkai terpublikasi untuk level ini. Saya tidak mencampur materi level lain.</p></div>}
 {items.map(item=>{const qs=questions.filter(q=>q.listening_id===item.id),done=checked[item.id],correct=qs.filter(q=>answers[q.id]===Number(q.correct_index)).length;return <Card key={item.id} className="overflow-hidden shadow-none"><CardHeader><div className="flex items-center justify-between gap-3"><div><p className="mb-1 text-xs text-primary">{item.audio_url?"Audio sumber":"TTS dari transkrip"}</p><CardTitle className="text-base leading-6">{item.title}</CardTitle></div><Badge variant="secondary">{item.level}</Badge></div></CardHeader><CardContent className="space-y-4">{item.audio_url&&<audio id={`audio-${item.id}`} data-choukai-audio src={item.audio_url} onPlay={()=>setActive(item.id)} onEnded={()=>setActive(null)} onPause={()=>setActive(v=>v===item.id?null:v)} preload="metadata" className="w-full" controls/>}<div className="flex flex-wrap gap-2"><Button type="button" onClick={()=>active===item.id?stop():play(item)} disabled={!item.audio_url&&!item.transcript_jp}>{active===item.id?<><Square className="mr-2 size-4"/>Berhenti</>:<><Play className="mr-2 size-4"/>Dengarkan</>}</Button><Button type="button" variant="outline" onClick={()=>play(item)} disabled={!item.audio_url&&!item.transcript_jp}><RotateCcw className="mr-2 size-4"/>Ulangi</Button><Button type="button" variant="outline" disabled={!item.transcript_jp} onClick={()=>setShowTranscript(v=>({...v,[item.id]:!v[item.id]}))}>{showTranscript[item.id]?"Sembunyikan transkrip":"Tampilkan transkrip"}</Button></div>
 {qs.length>0&&<section className="space-y-4 rounded-2xl border p-4"><h3 className="text-sm font-semibold">Pertanyaan</h3>{qs.map((q,qi)=><div key={q.id}><p className="text-sm font-medium">{qi+1}. {q.prompt}</p><div className="mt-2 space-y-2">{q.choices.map((c,ci)=>{const chosen=answers[q.id]===ci,isCorrect=ci===Number(q.correct_index);return <button key={ci} disabled={done} onClick={()=>setAnswers(v=>({...v,[q.id]:ci}))} className={`w-full rounded-xl border px-3 py-2 text-left text-xs ${done&&isCorrect?"border-primary bg-primary/10":done&&chosen&&!isCorrect?"border-destructive bg-destructive/5":chosen?"border-primary bg-primary/5":""}`}>{String.fromCharCode(65+ci)}. {c}</button>})}</div>{done&&<div className="mt-2 text-xs">{answers[q.id]===Number(q.correct_index)?<p className="flex items-center gap-1 font-semibold text-primary"><Check className="size-3.5"/>Benar</p>:<><p className="flex items-center gap-1 font-semibold text-destructive"><X className="size-3.5"/>Salah</p><p className="mt-1 text-muted-foreground">Jawaban benar: {q.choices[Number(q.correct_index)]}</p></>}{q.explanation_id&&<p className="mt-1 leading-5 text-muted-foreground">{q.explanation_id}</p>}</div>}</div>)}{!done?<Button className="w-full rounded-full" disabled={qs.some(q=>answers[q.id]===undefined)} onClick={()=>{setChecked(v=>({...v,[item.id]:true}));completeMutation.mutate(item)}}>Periksa Jawaban</Button>:<div className="rounded-xl bg-primary/[.06] p-3 text-center"><p className="text-xs text-muted-foreground">Hasil Chōkai</p><p className="mt-1 text-lg font-bold">{correct} / {qs.length} benar</p><p className="text-xs text-muted-foreground">{Math.round(correct/qs.length*100)}%</p></div>}</section>}
 {showTranscript[item.id]&&item.transcript_jp&&<div className="space-y-3 rounded-2xl border bg-muted/20 p-4"><div><p className="mb-2 text-xs font-semibold text-muted-foreground">日本語</p><p lang="ja" className="font-jp text-lg leading-8">{item.transcript_jp}</p></div><div className="border-t pt-3"><p className="mb-2 text-xs font-semibold text-muted-foreground">Bahasa Indonesia</p><p className="text-sm leading-7">{item.translation_id||"Terjemahan Indonesia belum tersedia."}</p></div></div>}
 {qs.length===0&&<Button type="button" className="h-10 w-full rounded-full text-[11px]" variant={completed[item.id]?"secondary":"default"} disabled={completed[item.id]||completeMutation.isPending} onClick={()=>completeMutation.mutate(item)}>{completed[item.id]?<><Check className="mr-1.5 size-4"/>Sudah selesai</>:"Tandai selesai · +5 XP"}</Button>}</CardContent></Card>})}</div></AppShell>}
