import { createFileRoute, Link } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { useState } from "react";
import { useServerFn } from "@tanstack/react-start";
import { ArrowRight, BookOpen, CalendarDays, CheckCircle2, Clock3, Crown, Flame, Headphones, Languages, Pencil, Sparkles, Target, Type, Zap } from "lucide-react";
import { getMyAccount } from "@/lib/profile.functions";
import { fetchAdaptivePlan } from "@/lib/adaptive-plan";
import { fetchLeaderboard } from "@/lib/leaderboard";
import { fetchDashboardMetrics, resolveContinueLesson } from "@/lib/dashboard-live";
import { getAccountLevel } from "@/lib/progression";
import { AppShell } from "@/components/layout/AppShell";
import { JlptStatusBar } from "@/components/layout/JlptStatusBar";
import { Card, CardContent } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { LEVELS, type Level } from "@/lib/learn-queries";
import { fetchMembership } from "@/lib/membership";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";

export const Route = createFileRoute("/_authenticated/dashboard")({ head: () => ({ meta: [{ title: "Home — ENO NIHONGO" }] }), component: DashboardPage });

const materialMeta = [
  { key: "kanji", label: "Kanji", icon: Type }, { key: "vocabulary", label: "Kosakata", icon: Languages }, { key: "grammar", label: "Bunpou", icon: BookOpen }, { key: "reading", label: "Dokkai", icon: CheckCircle2 }, { key: "listening", label: "Choukai", icon: Headphones },
] as const;

function DashboardPage() {
  const [showPlannerUpgrade, setShowPlannerUpgrade] = useState(false);
  const fetchAccount = useServerFn(getMyAccount);
  const { data, isLoading, isError, refetch } = useQuery({ queryKey: ["my-account"], queryFn: () => fetchAccount() });
  const rawLevel = data?.profile?.target_level;
  const level: Level = LEVELS.includes(rawLevel as Level) ? rawLevel as Level : "N5";
  const adaptive = useQuery({ queryKey: ["adaptive-plan"], queryFn: fetchAdaptivePlan, enabled: !isLoading && !isError, staleTime: 20_000 });
  const membership = useQuery({ queryKey: ["membership"], queryFn: fetchMembership, enabled: !isLoading && !isError, staleTime: 30_000 });
  const leaderboard = useQuery({ queryKey: ["leaderboard", 100], queryFn: () => fetchLeaderboard(100), enabled: !isLoading && !isError, staleTime: 30_000 });
  const metrics = useQuery({ queryKey: ["dashboard-live", level], queryFn: fetchDashboardMetrics, enabled: !isLoading && !isError, staleTime: 20_000 });
  const continueLesson = useQuery({ queryKey: ["continue-lesson", metrics.data?.last?.id], queryFn: () => resolveContinueLesson(metrics.data?.last ?? null), enabled: !!metrics.data?.last?.id, staleTime: 30_000 });
  const profile = data?.profile; const me = leaderboard.data?.find((u) => u.userId === profile?.id); const name = profile?.display_name?.trim() || "Pembelajar"; const plannerLocked = profile?.role !== "owner" && profile?.role !== "admin" && membership.data?.plan === "free";
  const completed = adaptive.data?.completed ?? 0; const target = adaptive.data?.target ?? 0; const percent = target ? Math.min(100, (completed / target) * 100) : 0; const targetDone = target > 0 && completed >= target; const accountLevel = getAccountLevel(me?.xp ?? 0);
  const weekly = metrics.data?.weekly ?? []; const maxMinutes = Math.max(1, ...weekly.map((d) => d.minutes)); const weeklyMinutes = weekly.reduce((s,d)=>s+d.minutes,0); const weeklyXp = weekly.reduce((s,d)=>s+d.xp,0);
  if (isLoading) return <AppShell compact title="Home"><div className="space-y-3"><Skeleton className="h-32 w-full rounded-2xl"/><Skeleton className="h-24 w-full rounded-2xl"/><Skeleton className="h-40 w-full rounded-2xl"/></div></AppShell>;
  if (isError) return <AppShell compact title="Home"><Card><CardContent className="p-5 text-sm">Data belum bisa dimuat. <button className="font-semibold text-primary" onClick={()=>refetch()}>Coba lagi</button></CardContent></Card></AppShell>;
  return <AppShell compact title="Home"><div className="mx-auto max-w-3xl space-y-4 eno-rise">
    <section className="flex items-center justify-between gap-3"><div className="min-w-0 flex items-center gap-3"><div className="relative shrink-0 eno-pop">{profile?.avatar_url?<img src={profile.avatar_url} alt={name} className="size-14 rounded-full border object-cover"/>:<div className="grid size-14 place-items-center rounded-full bg-primary/10 text-lg font-bold text-primary">{name.slice(0,1).toUpperCase()}</div>}<span className="absolute -bottom-0.5 -right-0.5 rounded-full border-2 border-background bg-primary px-1.5 py-0.5 text-[8px] font-bold text-primary-foreground eno-bounce">Lv {accountLevel.level}</span></div><div className="min-w-0"><p className="text-[10px] font-medium text-muted-foreground">Selamat Datang Kembali 👋</p><h1 className="truncate text-[19px] font-bold tracking-tight">{name}</h1><p className="mt-0.5 truncate text-[10px] text-muted-foreground">Menuju {level} dengan belajar konsisten 🎯</p></div></div><Link to="/profil" className="grid size-9 shrink-0 place-items-center rounded-xl border text-muted-foreground transition hover:border-primary/30 hover:text-primary" aria-label="Edit profil"><Pencil className="size-4"/></Link></section>
    <section className="grid grid-cols-4 gap-2"><Stat icon={Zap} value={(me?.xp??0).toLocaleString("id-ID")} label="XP"/><Stat icon={Sparkles} value={(me?.points??0).toLocaleString("id-ID")} label="Points"/><div className="rounded-2xl border bg-card px-2 py-2.5 text-center eno-rise"><Flame className="mx-auto size-3.5 text-orange-500 eno-pulse-soft"/><p className="mt-1 text-[11px] font-bold leading-none">{me?.streak??0}</p><p className="mt-1 text-[8px] text-muted-foreground">Hari</p></div><Stat icon={Target} value={level} label="JLPT"/></section>
    <Card className={`${targetDone?"rounded-2xl border-primary/35 bg-primary/[0.045] shadow-sm eno-pop":"rounded-2xl border-primary/20 bg-primary/[0.035] shadow-sm eno-rise"} ${plannerLocked?"cursor-pointer transition hover:border-primary/50":""}`} onClick={plannerLocked?()=>setShowPlannerUpgrade(true):undefined} onKeyDown={plannerLocked?(event)=>{if(event.key==="Enter"||event.key===" "){event.preventDefault();setShowPlannerUpgrade(true)}}:undefined} role={plannerLocked?"button":undefined} tabIndex={plannerLocked?0:undefined}><CardContent className="p-4"><div className="flex items-center justify-between gap-3"><div className="min-w-0"><p className="text-[10px] font-medium text-primary">Adaptive Study Planner</p><h2 className="mt-1 truncate text-[14px] font-bold">{targetDone?"Target hari ini selesai! 🎉":continueLesson.data?.title||"Mulai target belajar hari ini"}</h2><p className="mt-0.5 truncate text-[10px] text-muted-foreground">{plannerLocked?"Tersedia di Paket Premium":"Rencana belajar personalmu sudah aktif"}</p></div>{plannerLocked?<span className="grid size-9 shrink-0 place-items-center rounded-xl bg-primary text-primary-foreground" aria-hidden="true"><Crown className="size-4"/></span>:<Link to={(continueLesson.data?.to||"/target") as "/target"} className="grid size-9 shrink-0 place-items-center rounded-xl bg-primary text-primary-foreground"><ArrowRight className="size-4"/></Link>}</div><div className="mt-3 h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary eno-progress" style={{width:`${percent}%`}}/></div><div className="mt-1.5 flex items-center justify-between text-[9px] text-muted-foreground"><span>{Math.round(percent)}% target hari ini</span><span>{completed}/{target||0}</span></div></CardContent></Card>
    <Card className="rounded-2xl eno-rise"><CardContent className="p-3"><div className="flex items-center justify-between"><div><p className="text-[10px] font-semibold">Level Akun {accountLevel.level}</p><p className="mt-0.5 text-[9px] text-muted-foreground">{accountLevel.xpToNext>0?`${accountLevel.xpToNext.toLocaleString("id-ID")} XP lagi ke Lv ${accountLevel.level+1}`:"Level maksimum"}</p></div><span className="text-[10px] font-bold text-primary eno-pop">{Math.round(accountLevel.progress)}%</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary eno-progress" style={{width:`${accountLevel.progress}%`}}/></div></CardContent></Card>
    <section><div className="mb-2 flex items-center justify-between px-1"><h2 className="text-[13px] font-semibold">Progress Materi {level}</h2><Link to="/progress" className="text-[10px] font-semibold text-primary">Detail</Link></div><div className="grid grid-cols-5 gap-2">{materialMeta.map(({key,label,icon:Icon})=>{const m=metrics.data?.progress?.[key]??{done:0,total:0};const value=m.total?Math.round(m.done/m.total*100):0;return <div key={key} className="rounded-2xl border bg-card p-2 text-center eno-rise"><div className="mx-auto grid size-9 place-items-center rounded-full bg-primary/10 text-primary"><Icon className="size-4"/></div><p className="mt-1.5 text-[9px] font-semibold">{label}</p><p className="mt-0.5 text-[8px] text-muted-foreground">{m.done} / {m.total}</p><div className="mt-1.5 h-1 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary eno-progress" style={{width:`${value}%`}}/></div></div>})}</div></section>
    <Card className="rounded-2xl eno-rise"><CardContent className="p-4"><div className="flex items-center justify-between"><div><h2 className="text-[13px] font-semibold">Statistik Mingguan</h2><p className="mt-0.5 text-[9px] text-muted-foreground">Data aktivitas 7 hari terakhir, bukan contoh.</p></div><Clock3 className="size-4 text-primary"/></div>
      <div className="mt-4 grid h-[92px] grid-cols-7 gap-2">{weekly.map(day=>{const date=new Date(`${day.date}T00:00:00+09:00`);const label=new Intl.DateTimeFormat("id-ID",{weekday:"short",timeZone:"Asia/Tokyo"}).format(date).replace(".","");const barPx=day.minutes>0?Math.max(10,Math.round(day.minutes/maxMinutes*64)):3;return <div key={day.date} className="flex min-w-0 flex-col items-center"><div className="relative flex h-[68px] w-full max-w-7 items-end justify-center rounded-md bg-primary/[0.06]" title={`${day.minutes} menit · ${day.xp} XP`}><div className="w-full rounded-t-md bg-primary/75 transition-[height] duration-500" style={{height:`${barPx}px`,minHeight:day.minutes>0?"10px":"3px"}}/></div><span className="mt-1.5 text-[8px] text-muted-foreground">{label}</span></div>})}</div>
      <div className="mt-2 flex items-center justify-between text-[9px] text-muted-foreground"><span>{weeklyMinutes} menit minggu ini</span><span>{weeklyXp.toLocaleString("id-ID")} XP</span></div></CardContent></Card>
    <section><div className="mb-2 flex items-center gap-2 px-1"><CalendarDays className="size-4 text-primary"/><h2 className="text-[13px] font-semibold">JLPT</h2></div><JlptStatusBar/></section>
    <Dialog open={showPlannerUpgrade} onOpenChange={setShowPlannerUpgrade}><DialogContent className="w-[calc(100%-2rem)] max-w-sm rounded-3xl p-5"><DialogHeader className="text-left"><span className="grid size-11 place-items-center rounded-2xl bg-primary text-primary-foreground"><Crown className="size-5"/></span><DialogTitle className="pt-2 text-lg font-black">Adaptive Planner adalah fitur Premium</DialogTitle><DialogDescription className="text-xs leading-5">Premium menyusun target harian sesuai level, waktu belajar, dan progresmu—supaya kamu tahu apa yang perlu dipelajari berikutnya.</DialogDescription></DialogHeader><DialogFooter className="gap-2 sm:flex-col sm:space-x-0"><Button asChild className="w-full rounded-xl"><Link to="/paket">Lihat Paket Premium</Link></Button><Button type="button" variant="outline" className="w-full rounded-xl" onClick={()=>setShowPlannerUpgrade(false)}>Nanti saja</Button></DialogFooter></DialogContent></Dialog>
  </div></AppShell>;
}
function Stat({icon:Icon,value,label}:{icon:typeof Zap;value:string;label:string}){return <div className="rounded-2xl border bg-card px-2 py-2.5 text-center eno-rise"><Icon className="mx-auto size-3.5 text-primary"/><p className="mt-1 text-[11px] font-bold leading-none">{value}</p><p className="mt-1 text-[8px] text-muted-foreground">{label}</p></div>}
