import { createFileRoute, Link } from '@tanstack/react-router'
import { useEffect, useState } from 'react'
import { CalendarDays, Clock3, Crown, LockKeyhole, Trophy } from 'lucide-react'
import { AppShell } from '@/components/layout/AppShell'
import { Button } from '@/components/ui/button'
import { Card, CardContent } from '@/components/ui/card'
import { supabase } from '@/integrations/supabase/client'

type Exam={id:string;title:string;level:string;exam_month:string;opens_at:string;closes_at:string;duration_minutes:number;passing_score:number;status:string;premium_only:boolean;is_entitled:boolean;attempts_used:number}
export const Route=createFileRoute('/_authenticated/eno-exam')({component:Page})
function Page(){const[items,setItems]=useState<Exam[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('');useEffect(()=>{void load()},[]);async function load(){setLoading(true);const{data,error}=await supabase.rpc('get_visible_eno_monthly_exams' as never);if(error)setError(error.message);else setItems((data??[]) as Exam[]);setLoading(false)}
return <AppShell title="ENO Exam Bulanan" description="Ujian resmi bulanan ENO NIHONGO untuk member Premium."><div className="mb-4 rounded-2xl border border-primary/20 bg-primary/5 p-4"><div className="flex items-start gap-3"><Crown className="mt-0.5 size-5 text-primary"/><div><h1 className="font-bold">ENO Exam Premium</h1><p className="mt-1 text-xs leading-5 text-muted-foreground">Simulasi JLPT adalah latihan kapan saja. ENO Exam adalah event ujian resmi bulanan dengan satu kesempatan dan ranking tersendiri.</p></div></div></div>{loading&&<p className="text-sm text-muted-foreground">Memuat ujian…</p>}{error&&<p className="text-sm text-destructive">{error}</p>}<div className="space-y-3">{items.map(e=>{const now=Date.now(),open=new Date(e.opens_at).getTime(),close=new Date(e.closes_at).getTime(),active=e.status==='published'&&now>=open&&now<=close;return <Card key={e.id}><CardContent className="p-4"><div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2"><span className="rounded-lg bg-primary/10 px-2 py-1 text-xs font-bold text-primary">{e.level}</span><span className="rounded-lg bg-amber-500/10 px-2 py-1 text-[10px] font-bold text-amber-700 dark:text-amber-300">PREMIUM</span></div><h2 className="mt-2 font-bold">{e.title}</h2></div><Trophy className="size-5 text-primary"/></div><div className="mt-3 grid grid-cols-2 gap-2 text-xs text-muted-foreground"><span className="flex items-center gap-1.5"><CalendarDays className="size-3.5"/>{new Date(e.exam_month).toLocaleDateString('id-ID',{month:'long',year:'numeric'})}</span><span className="flex items-center gap-1.5"><Clock3 className="size-3.5"/>{e.duration_minutes} menit</span><span>Nilai lulus {e.passing_score}</span><span>Percobaan {e.attempts_used}/1</span></div><div className="mt-4">{!e.is_entitled?<Button className="w-full" variant="outline" disabled><LockKeyhole className="mr-2 size-4"/>Khusus Premium</Button>:active&&e.attempts_used<1?<Button className="w-full" asChild><Link to="/eno-exam/$examId" params={{examId:e.id}}>Mulai ENO Exam</Link></Button>:<Button className="w-full" variant="secondary" disabled>{e.status==='closed'?'Ujian telah ditutup':e.attempts_used>=1?'Kesempatan sudah digunakan':now<open?'Belum dibuka':'Tidak tersedia'}</Button>}</div></CardContent></Card>})}{!loading&&!error&&items.length===0&&<div className="rounded-2xl border border-dashed p-8 text-center text-sm text-muted-foreground">Belum ada ENO Exam yang dipublikasikan.</div>}</div></AppShell>}
