import { createFileRoute, useNavigate } from '@tanstack/react-router'
import { useEffect, useMemo, useState } from 'react'
import { Clock3 } from 'lucide-react'
import { AppShell } from '@/components/layout/AppShell'
import { Button } from '@/components/ui/button'
import { Card, CardContent } from '@/components/ui/card'
import { supabase } from '@/integrations/supabase/client'

type Q={id:string;section:string;question_no:number;mondai_no:number;instruction_jp:string|null;prompt_jp:string;choices:unknown;image_url:string|null;audio_url:string|null;passage_jp:string|null}
export const Route=createFileRoute('/_authenticated/eno-exam/$examId')({component:Page})
function Page(){const{examId}=Route.useParams();const nav=useNavigate();const[attemptId,setAttemptId]=useState('');const[questions,setQuestions]=useState<Q[]>([]);const[answers,setAnswers]=useState<Record<string,number>>({});const[seconds,setSeconds]=useState(0);const[error,setError]=useState('');const[submitting,setSubmitting]=useState(false);useEffect(()=>{void start()},[examId]);useEffect(()=>{if(seconds<=0)return;const t=setInterval(()=>setSeconds(s=>Math.max(0,s-1)),1000);return()=>clearInterval(t)},[seconds>0]);async function start(){const{data,error}=await supabase.rpc('start_eno_monthly_exam' as never,{p_exam_id:examId} as never);if(error){setError(error.message);return}const r=data as unknown as {attempt_id:string;duration_minutes:number};setAttemptId(r.attempt_id);setSeconds(r.duration_minutes*60);const q=await supabase.rpc('get_eno_monthly_exam_questions' as never,{p_attempt_id:r.attempt_id} as never);if(q.error)setError(q.error.message);else setQuestions((q.data??[]) as Q[])}async function submit(){if(!attemptId||submitting)return;setSubmitting(true);const{data,error}=await supabase.rpc('submit_eno_monthly_exam' as never,{p_attempt_id:attemptId,p_answers:answers} as never);if(error){setError(error.message);setSubmitting(false);return}const r=data as unknown as {score:number;correct_count:number;total_questions:number;passed:boolean};alert(`Nilai: ${r.score} — ${r.correct_count}/${r.total_questions}${r.passed?' — LULUS':''}`);await nav({to:'/eno-exam'});}
const time=useMemo(()=>`${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`,[seconds]);return <AppShell title="ENO Exam" backTo="/eno-exam" compact><div className="sticky top-14 z-20 mb-4 flex items-center justify-between rounded-xl border bg-background/95 p-3 shadow-sm backdrop-blur"><span className="text-xs font-semibold">Terjawab {Object.keys(answers).length}/{questions.length}</span><span className="flex items-center gap-1.5 font-mono text-sm font-bold"><Clock3 className="size-4"/>{time}</span></div>{error&&<div className="rounded-xl border border-destructive/30 bg-destructive/5 p-4 text-sm text-destructive">{error}</div>}<div className="space-y-4">{questions.map((q,i)=>{const choices=Array.isArray(q.choices)?q.choices:[];return <Card key={q.id}><CardContent className="p-4"><p className="text-[10px] font-bold uppercase tracking-wide text-primary">{q.section.replace('_',' / ')} · Mondai {q.mondai_no}</p>{q.instruction_jp&&<p className="mt-2 text-xs text-muted-foreground">{q.instruction_jp}</p>}{q.passage_jp&&<div className="mt-3 rounded-xl bg-muted/50 p-3 text-sm leading-7">{q.passage_jp}</div>}{q.image_url&&<img src={q.image_url} alt="Ilustrasi soal" className="mt-3 max-h-72 w-full rounded-xl object-contain"/>}{q.audio_url&&<audio controls preload="none" src={q.audio_url} className="mt-3 w-full"/>}<p className="mt-3 font-medium leading-7">{i+1}. {q.prompt_jp}</p><div className="mt-3 space-y-2">{choices.map((c,idx)=><button key={idx} type="button" onClick={()=>setAnswers(a=>({...a,[q.id]:idx}))} className={`w-full rounded-xl border p-3 text-left text-sm ${answers[q.id]===idx?'border-primary bg-primary/10':'border-border'}`}><span className="mr-2 font-bold">{idx+1}.</span>{String(c)}</button>)}</div></CardContent></Card>})}</div>{questions.length>0&&<Button className="mt-5 w-full" onClick={submit} disabled={submitting||seconds===0}>{submitting?'Mengirim…':'Kirim Jawaban'}</Button>}</AppShell>}
