import { createFileRoute, Link } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { BookOpen, FileQuestion, GraduationCap, Headphones, ShieldCheck } from "lucide-react";
import { AppShell } from "@/components/layout/AppShell";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { supabase } from "@/integrations/supabase/client";
export const Route=createFileRoute("/_authenticated/guru")({component:TeacherPage});
function TeacherPage(){const access=useQuery({queryKey:["teacher-console-access"],queryFn:async()=>{const{data,error}=await(supabase as any).rpc("get_teacher_console_data");if(error)throw error;return data as {role:string;can_manage_learning_content:boolean}},retry:false});if(access.isLoading)return <AppShell title="Panel Guru"><p className="py-12 text-center text-xs text-muted-foreground">Memeriksa akses guru…</p></AppShell>;if(access.isError)return <AppShell title="Panel Guru"><div className="mx-auto max-w-md py-12 text-center"><ShieldCheck className="mx-auto size-10 text-destructive"/><h1 className="mt-3 font-bold">Akses guru diperlukan</h1><p className="mt-2 text-xs text-muted-foreground">Panel ini hanya tersedia untuk akun dengan role Guru, Admin, atau Owner.</p><Button asChild className="mt-5"><Link to="/profil">Kembali ke Profil</Link></Button></div></AppShell>;return <AppShell title="Panel Guru" compact><div className="mx-auto max-w-3xl space-y-4 pb-8"><div className="rounded-3xl bg-primary p-5 text-primary-foreground"><div className="flex items-center gap-2 text-xs font-bold"><GraduationCap className="size-4"/>PANEL GURU</div><h1 className="mt-2 text-2xl font-black">Ruang Kerja Guru</h1><p className="mt-1 text-xs opacity-80">Kelola materi pembelajaran dan kontribusi pengajaran ENO NIHONGO.</p></div><div className="grid gap-3 sm:grid-cols-3"><Tool icon={BookOpen} title="Materi" text="Kanji, Kotoba, Bunpou, dan Dokkai."/><Tool icon={Headphones} title="Choukai" text="Materi listening dan audio."/><Tool icon={FileQuestion} title="Latihan" text="Soal latihan pembelajaran."/></div><Card className="border-primary/20 bg-primary/[0.04]"><CardContent className="p-4"><p className="text-xs font-bold">Hak akses terpisah</p><p className="mt-1 text-[10px] leading-4 text-muted-foreground">Guru tidak mendapat hak administrasi pengguna, paket, atau role. Owner/Admin tetap memiliki kontrol administrasi penuh.</p></CardContent></Card></div></AppShell>}
function Tool({icon:Icon,title,text}:{icon:any;title:string;text:string}){return <Card className="rounded-2xl"><CardContent className="p-4"><Icon className="size-5 text-primary"/><p className="mt-3 text-sm font-bold">{title}</p><p className="mt-1 text-[10px] text-muted-foreground">{text}</p></CardContent></Card>}
