import { createFileRoute,Link } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { UserRound,BookOpen } from "lucide-react";
import { AppShell } from "@/components/layout/AppShell";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { supabase } from "@/integrations/supabase/client";
export const Route=createFileRoute("/_authenticated/guru-kelas/$classId")({component:Page});
function Page(){const{classId}=Route.useParams();const q=useQuery({queryKey:["teacher-class-participants",classId],queryFn:async()=>{const{data,error}=await(supabase as any).rpc("get_teacher_class_participants",{p_class_id:classId});if(error)throw error;return data??[]}});return <AppShell title="Kelola Kelas" backTo="/guru"><div className="mx-auto max-w-2xl space-y-4"><div className="flex items-start justify-between gap-3"><div><h1 className="text-xl font-black">Peserta Kelas</h1><p className="text-xs text-muted-foreground">Daftar siswa aktif yang bergabung ke kelas ini.</p></div><Button size="sm" asChild><Link to="/guru-kelas/$classId/konten" params={{classId}}><BookOpen className="mr-1 size-4"/>Kelola Konten</Link></Button></div><Card><CardContent className="p-4">{q.isLoading&&<p className="text-xs">Memuat peserta…</p>}{q.isError&&<p className="text-xs text-destructive">Anda tidak memiliki akses ke daftar peserta kelas ini.</p>}{(q.data??[]).map((p:any)=><div key={p.user_id} className="flex items-center justify-between border-b py-3 last:border-0"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-full bg-primary/10"><UserRound className="size-4 text-primary"/></span><div><p className="text-xs font-bold">{p.display_name}</p><p className="text-[10px] text-muted-foreground">Bergabung {new Date(p.joined_at).toLocaleDateString("id-ID")}</p></div></div><span className="rounded-full bg-primary/10 px-2 py-1 text-[9px] font-bold text-primary">{p.status}</span></div>)}{!q.isLoading&&!q.isError&&(q.data??[]).length===0&&<p className="text-xs text-muted-foreground">Belum ada peserta.</p>}</CardContent></Card></div></AppShell>}
