import { createFileRoute } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { useState } from "react";
import { ChevronLeft, ChevronRight, Volume2 } from "lucide-react";
import { AppShell } from "@/components/layout/AppShell";
import { fetchTargetLevel } from "@/lib/target-level";
import { fetchVocabCount, fetchVocabPage, fetchVocabSenses, VOCAB_PAGE_SIZE } from "@/lib/vocab-resilient";
import { asExamples, type Level } from "@/lib/learn-queries";

export const Route=createFileRoute("/_authenticated/kotoba")({component:KotobaPage});
type VocabRow={id:string;term:string;reading:string|null;meaning_id:string|null;meaning_en?:string|null;part_of_speech:string|null;examples:unknown;level:Level};
function speak(t:string){if(!window.speechSynthesis)return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang="ja-JP";u.rate=.85;window.speechSynthesis.speak(u)}
function KotobaPage(){
 const {data:targetLevel,isLoading:levelLoading,error:levelError}=useQuery({queryKey:["target-level"],queryFn:fetchTargetLevel,retry:1,staleTime:300000});
 const level:Level=targetLevel??"N5",ready=!levelLoading&&Boolean(targetLevel);
 const [page,setPage]=useState(0),[selected,setSelected]=useState<VocabRow|null>(null);
 const {data:total=0}=useQuery({queryKey:["vocab-count",level],queryFn:()=>fetchVocabCount(level),enabled:ready,staleTime:600000});
 const {data:rows=[],isLoading,error}=useQuery({queryKey:["vocab-page",level,page],queryFn:()=>fetchVocabPage(level,page*VOCAB_PAGE_SIZE,VOCAB_PAGE_SIZE),enabled:ready,staleTime:600000,placeholderData:p=>p});
 const {data:senses=[]}=useQuery({queryKey:["vocab-senses",selected?.id],queryFn:()=>fetchVocabSenses(selected!.id),enabled:Boolean(selected?.id),staleTime:600000});
 const examples=selected?[...asExamples(selected.examples),...senses.flatMap((s:any)=>asExamples(s.examples))].slice(0,4):[];
 const pages=Math.max(1,Math.ceil(total/VOCAB_PAGE_SIZE));
 if(levelLoading)return <AppShell title="Kotoba" backTo="/belajar" backLabel="Materi" compact><p className="py-8 text-center text-xs">Memuat level…</p></AppShell>;
 if(levelError)return <AppShell title="Kotoba" backTo="/belajar" backLabel="Materi" compact><p className="py-8 text-center text-xs text-destructive">Level profil tidak dapat dimuat.</p></AppShell>;
 return <AppShell title="Kotoba" backTo="/belajar" backLabel="Materi" compact><div className="mx-auto max-w-md">
  {selected?<><button onClick={()=>setSelected(null)} className="mb-4 flex items-center gap-1 text-xs font-semibold"><ChevronLeft className="size-4"/>Kosakata {level}</button><section className="text-center"><div lang="ja" className="font-jp text-5xl font-bold">{selected.term}</div>{selected.reading&&<p className="mt-2 font-jp text-sm text-muted-foreground">{selected.reading}</p>}<p className="mt-2 font-medium">{selected.meaning_id}</p><button onClick={()=>speak(selected.term)} className="mx-auto mt-3 grid size-11 place-items-center rounded-full bg-primary text-primary-foreground"><Volume2/></button></section><div className="mt-5 grid grid-cols-2 gap-2"><Info label="Level" value={level}/><Info label="Kelas Kata" value={selected.part_of_speech||"—"}/></div>{senses[0]?.usage_note_id&&<section className="mt-3 rounded-xl bg-primary/[.06] p-3"><h2 className="text-xs font-bold text-primary">Penggunaan</h2><p className="mt-1 text-xs leading-5">{senses[0].usage_note_id}</p></section>}<section className="mt-4"><h2 className="text-sm font-bold">Contoh Kalimat</h2>{examples.length?examples.map((e:any,i:number)=><div key={i} className="mt-2 rounded-xl bg-muted/35 p-3 text-xs"><p lang="ja" className="font-jp text-sm font-medium">{e.jp}</p><p className="mt-1">{e.id||"Terjemahan belum tersedia."}</p></div>):<p className="mt-2 text-xs text-muted-foreground">Contoh kalimat belum tersedia.</p>}</section></>:<><div className="mb-3 flex items-end justify-between"><div><h1 className="text-xl font-bold">Kosakata {level}</h1><p className="mt-1 text-[10px] text-muted-foreground">Level mengikuti target JLPT di Profil.</p></div><span className="text-xs font-semibold">{total.toLocaleString("id-ID")} kotoba</span></div>{error?<p className="py-8 text-center text-xs text-destructive">Kosakata gagal dimuat.</p>:isLoading?<p className="py-8 text-center text-xs">Memuat materi…</p>:<div className="space-y-2">{rows.map((w:any)=><button key={w.id} onClick={()=>setSelected(w)} className="flex w-full items-center gap-3 rounded-xl border bg-card px-3 py-2.5 text-left"><span className="grid size-7 place-items-center rounded-lg bg-primary/[.08] text-primary">語</span><div className="min-w-0 flex-1"><div className="font-jp text-sm font-bold">{w.term}{w.reading&&<span className="ml-1 text-[10px] font-normal text-muted-foreground">（{w.reading}）</span>}</div><p className="truncate text-[10px] text-muted-foreground">{w.meaning_id||"Arti belum tersedia"}</p></div><ChevronRight className="size-4"/></button>)}</div>}<div className="mt-4 flex items-center justify-between"><button disabled={page===0} onClick={()=>setPage(p=>Math.max(0,p-1))} className="rounded-lg border px-3 py-2 text-xs disabled:opacity-30">Sebelumnya</button><span className="text-xs text-muted-foreground">{page+1} / {pages}</span><button disabled={page>=pages-1} onClick={()=>setPage(p=>Math.min(pages-1,p+1))} className="rounded-lg border px-3 py-2 text-xs disabled:opacity-30">Berikutnya</button></div></>}
 </div></AppShell>;
}
function Info({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-muted/35 p-3"><p className="text-[10px] text-muted-foreground">{label}</p><p className="mt-1 text-xs font-semibold">{value}</p></div>}
