import { createFileRoute } from "@tanstack/react-router";
import { Bell, BookOpenCheck, CircleHelp, Globe2, Instagram, LogOut, MessageSquareText, Moon, Music2, RefreshCw, Shield, Sun, UserRound, Users, X, type LucideIcon } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { useQueryClient } from "@tanstack/react-query";
import { AppShell } from "@/components/layout/AppShell";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Switch } from "@/components/ui/switch";
import { supabase } from "@/integrations/supabase/client";

export const Route=createFileRoute("/_authenticated/pengaturan")({component:SettingsPage});
function Row({icon:Icon,title,desc,onClick,children}:{icon:LucideIcon;title:string;desc:string;onClick?:()=>void;children?:React.ReactNode}){return <button type="button" onClick={onClick} className="flex w-full items-center gap-3 rounded-xl p-2.5 text-left transition hover:bg-muted/50 active:bg-muted"><span className="grid size-8 place-items-center rounded-lg bg-primary/10 text-primary"><Icon className="size-4"/></span><span className="min-w-0 flex-1"><span className="block text-[12px] font-semibold">{title}</span><span className="block text-[9px] leading-4 text-muted-foreground">{desc}</span></span>{children}</button>}

type ModalKind="guide"|"target"|"notifications"|"appearance"|"refresh"|"edit"|"security"|"report"|"support"|"faq"|"about"|"instagram"|"tiktok"|"logout"|null;
const modalCopy:Record<Exclude<ModalKind,null|"logout">,{title:string;text:string;actionLabel?:string;action?:"profile"|"report"|"support"|"refresh"|"instagram"|"tiktok"}>={
 guide:{title:"Instruksi & Panduan",text:"Gunakan Target untuk rencana harian. Pelajari Kanji, Kosakata, Bunpou, Dokkai, dan Choukai, lalu ukur kemampuan melalui Simulasi JLPT."},
 target:{title:"Target Belajar",text:"Atur level aktif, tujuan belajar, dan target waktumu. Data ini dipakai Adaptive Study Planner untuk menyusun rencana harian.",actionLabel:"Buka Target Profil",action:"profile"},
 notifications:{title:"Notifikasi",text:"Mengatur pemberitahuan target belajar, progres, simulasi, dan informasi akun pada perangkat ini."},
 appearance:{title:"Mode Tampilan",text:"Pilih mode terang atau gelap. Pilihan disimpan pada perangkat yang sedang digunakan."},
 refresh:{title:"Segarkan Data",text:"Memuat ulang data terbaru dari akun dan server tanpa menghapus progres belajar.",actionLabel:"Segarkan Sekarang",action:"refresh"},
 edit:{title:"Edit Profil",text:"Ubah nama, foto profil, level bahasa, bahasa aplikasi, negara, dan target belajar.",actionLabel:"Buka Edit Profil",action:"profile"},
 security:{title:"Keamanan & Privasi",text:"ENO NIHONGO menggunakan autentikasi akun untuk menjaga akses. Jangan membagikan akun atau kode masuk. Data profil dan progres hanya digunakan untuk menjalankan fitur belajar dan akun."},
 report:{title:"Masukan & Laporan Masalah",text:"Laporkan bug, tampilan yang tidak sesuai, atau materi bermasalah. Sertakan halaman dan penjelasan singkat agar lebih cepat diperiksa.",actionLabel:"Kirim Laporan",action:"report"},
 support:{title:"Layanan Pelanggan",text:"Hubungi ENO NIHONGO untuk bantuan akun, membership, materi, atau masalah penggunaan aplikasi.",actionLabel:"Hubungi Support",action:"support"},
 faq:{title:"FAQ",text:"Progres belajar tersimpan di akun. Free mendapat 1 simulasi penuh per bulan; Premium dapat mengulang simulasi dan mengakses ENO Monthly Exam; Lifetime membuka seluruh fitur membership."},
 about:{title:"Tentang ENO NIHONGO",text:"ENO NIHONGO adalah aplikasi belajar bahasa Jepang N5–N1 dengan target adaptif, Kanji, Kosakata, Bunpou, Dokkai, Choukai, review, simulasi JLPT, XP, poin, dan leaderboard."},
 instagram:{title:"Instagram ENO NIHONGO",text:"Ikuti akun Instagram kami @enottf untuk update ENO NIHONGO, informasi belajar, dan konten bahasa Jepang.",actionLabel:"Buka Instagram",action:"instagram"},
 tiktok:{title:"TikTok ENO NIHONGO",text:"Ikuti akun TikTok kami @enottff untuk konten belajar bahasa Jepang dan update ENO NIHONGO.",actionLabel:"Buka TikTok",action:"tiktok"},
};

function CenterModal({kind,onClose,onAction}:{kind:Exclude<ModalKind,null>;onClose:()=>void;onAction:(action?:string)=>void}){
 if(kind==="logout")return <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/35 p-4" onClick={onClose}><div onClick={e=>e.stopPropagation()} className="w-full max-w-[300px] rounded-2xl border bg-background p-4 shadow-2xl"><h2 className="text-center text-[14px] font-bold">Keluar dari akun?</h2><p className="mt-2 text-center text-[10px] leading-5 text-muted-foreground">Apakah kamu yakin ingin keluar dari ENO NIHONGO pada perangkat ini?</p><div className="mt-4 grid grid-cols-2 gap-2"><button onClick={onClose} className="h-9 rounded-full border text-[10px] font-semibold">Batal</button><button onClick={()=>onAction("logout")} className="h-9 rounded-full bg-destructive text-[10px] font-semibold text-destructive-foreground">Ya, Keluar</button></div></div></div>;
 const data=modalCopy[kind];
 return <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/35 p-4" onClick={onClose}><div role="dialog" aria-modal="true" onClick={e=>e.stopPropagation()} className="w-full max-w-[310px] rounded-2xl border bg-background shadow-2xl"><div className="flex items-center gap-2 border-b px-3.5 py-3"><div className="grid size-7 place-items-center rounded-lg bg-primary/10 text-primary"><CircleHelp className="size-3.5"/></div><h2 className="flex-1 text-[12px] font-bold">{data.title}</h2><button type="button" onClick={onClose} className="grid size-7 place-items-center rounded-full hover:bg-muted"><X className="size-3.5"/></button></div><div className="p-3.5"><p className="text-[10px] leading-5 text-muted-foreground">{data.text}</p>{data.actionLabel&&<button type="button" onClick={()=>onAction(data.action)} className="mt-3 h-9 w-full rounded-full bg-primary text-[10px] font-semibold text-primary-foreground">{data.actionLabel}</button>}</div></div></div>;
}

function SettingsPage(){
 const qc=useQueryClient();const[notifications,setNotifications]=useState(()=>localStorage.getItem("enonihongo-notifications")!=="off");const[dark,setDark]=useState(()=>localStorage.getItem("enonihongo-theme")==="dark");const[modal,setModal]=useState<ModalKind>(null);
 const toggleDark=(v:boolean)=>{setDark(v);document.documentElement.classList.toggle("dark",v);localStorage.setItem("enonihongo-theme",v?"dark":"light")};
 const toggleNotifications=(v:boolean)=>{setNotifications(v);localStorage.setItem("enonihongo-notifications",v?"on":"off")};
 const logout=async()=>{await supabase.auth.signOut();window.location.href="/auth"};
 const runAction=async(action?:string)=>{if(action==="logout"){await logout();return}if(action==="profile"){window.location.href="/edit-profil";return}if(action==="report"){window.location.href="mailto:enoinjapan@gmail.com?subject=Laporan%20Masalah%20ENO%20NIHONGO";return}if(action==="support"){window.location.href="mailto:enoinjapan@gmail.com";return}if(action==="instagram"){window.open("https://www.instagram.com/enottf/","_blank","noopener,noreferrer");setModal(null);return}if(action==="tiktok"){window.open("https://www.tiktok.com/@enottff","_blank","noopener,noreferrer");setModal(null);return}if(action==="refresh"){await qc.invalidateQueries();toast.success("Data disegarkan.");setModal(null)}};
 return <AppShell title="Pengaturan" backTo="/profil" compact><div className="mx-auto max-w-md space-y-3">
  <Card className="rounded-2xl"><CardHeader className="pb-1"><CardTitle className="text-xs">Aplikasi & Belajar</CardTitle></CardHeader><CardContent className="p-2"><Row icon={BookOpenCheck} title="Instruksi & Panduan" desc="Cara menggunakan ENO NIHONGO." onClick={()=>setModal("guide")}/><Row icon={BookOpenCheck} title="Target Belajar" desc="Atur level dan target belajar." onClick={()=>setModal("target")}/><Row icon={Bell} title="Notifikasi" desc="Pemberitahuan target, simulasi, dan akun." onClick={()=>setModal("notifications")}><span onClick={e=>e.stopPropagation()}><Switch checked={notifications} onCheckedChange={toggleNotifications}/></span></Row><Row icon={dark?Sun:Moon} title="Mode Tampilan" desc="Terang atau gelap." onClick={()=>setModal("appearance")}><span onClick={e=>e.stopPropagation()}><Switch checked={dark} onCheckedChange={toggleDark}/></span></Row><Row icon={RefreshCw} title="Segarkan Data" desc="Ambil data terbaru dari server." onClick={()=>setModal("refresh")}/></CardContent></Card>
  <Card className="rounded-2xl"><CardHeader className="pb-1"><CardTitle className="text-xs">Akun</CardTitle></CardHeader><CardContent className="p-2"><Row icon={UserRound} title="Edit Profil" desc="Nama, foto, level bahasa, bahasa aplikasi, dan negara." onClick={()=>setModal("edit")}/><Row icon={Shield} title="Keamanan & Privasi" desc="Kelola informasi akun dengan aman." onClick={()=>setModal("security")}/><Row icon={LogOut} title="Keluar" desc="Keluar dari akun pada perangkat ini." onClick={()=>setModal("logout")}/></CardContent></Card>
  <Card className="rounded-2xl"><CardHeader className="pb-1"><CardTitle className="text-xs">Follow Akun Kami</CardTitle></CardHeader><CardContent className="p-2"><Row icon={Instagram} title="Instagram" desc="@enottf" onClick={()=>setModal("instagram")}/><Row icon={Music2} title="TikTok" desc="@enottff" onClick={()=>setModal("tiktok")}/></CardContent></Card>
  <Card className="rounded-2xl"><CardHeader className="pb-1"><CardTitle className="text-xs">Bantuan & Tentang</CardTitle></CardHeader><CardContent className="p-2"><Row icon={MessageSquareText} title="Masukan & Laporan Masalah" desc="Kirim laporan langsung ke ENO NIHONGO." onClick={()=>setModal("report")}/><Row icon={Users} title="Layanan Pelanggan" desc="enoinjapan@gmail.com" onClick={()=>setModal("support")}/><Row icon={CircleHelp} title="FAQ" desc="Pertanyaan umum tentang aplikasi." onClick={()=>setModal("faq")}/><Row icon={Globe2} title="Tentang ENO NIHONGO" desc="Platform belajar bahasa Jepang dan persiapan JLPT." onClick={()=>setModal("about")}/></CardContent></Card>
  <p className="px-2 text-center text-[9px] text-muted-foreground">ENO NIHONGO V1</p>
 </div>{modal&&<CenterModal kind={modal} onClose={()=>setModal(null)} onAction={a=>void runAction(a)}/>}</AppShell>;
}