import { createFileRoute, Link } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { ArrowRight, BookOpen, Crown, Headphones, Languages, ListChecks, Timer, Type } from "lucide-react";
import { AppShell } from "@/components/layout/AppShell";
import { Button } from "@/components/ui/button";
import { fetchFullSimulationAccess } from "@/lib/membership";
import { fetchTargetLevel } from "@/lib/target-level";
export const Route=createFileRoute("/_authenticated/simulasi")({component:SimulationPage});
const sections=[{key:"vocabulary",jp:"文字・語彙",label:"Kanji & Kosakata",icon:Type,tone:"bg-emerald-50 text-emerald-600"},{key:"grammar",jp:"文法",label:"Bunpou",icon:Languages,tone:"bg-amber-50 text-amber-600"},{key:"reading",jp:"読解",label:"Dokkai",icon:BookOpen,tone:"bg-sky-50 text-sky-600"},{key:"listening",jp:"聴解",label:"Choukai",icon:Headphones,tone:"bg-rose-50 text-rose-500"}] as const;
function SimulationPage(){
 const target=useQuery({queryKey:["target-level"],queryFn:fetchTargetLevel,retry:1}); const level=target.data??"N5"; const access=useQuery({queryKey:["full-simulation-access"],queryFn:fetchFullSimulationAccess,staleTime:30000}); const a=access.data;
 return <AppShell title="Simulasi JLPT" compact><div className="mx-auto max-w-md"><h1 className="text-[20px] font-bold">Simulasi JLPT {level}</h1><p className="mt-1 text-[10px] text-muted-foreground">Level mengikuti target JLPT yang dipilih di Profil.</p>
 {target.isLoading?<p className="py-8 text-center text-xs text-muted-foreground">Memuat level profil…</p>:target.isError?<p className="py-8 text-center text-xs text-destructive">Level profil tidak dapat dimuat.</p>:<><div className="mt-3 space-y-2">{sections.map(({key,jp,label,icon:Icon,tone})=><Link key={key} to="/simulasi-bagian/$level/$section" params={{level,section:key}} className="flex items-center gap-3 rounded-xl border bg-card px-3 py-3"><span className={`grid size-8 place-items-center rounded-lg ${tone}`}><Icon className="size-4"/></span><span className="flex-1"><span className="block font-jp text-[13px] font-bold">{jp}</span><span className="text-[10px] text-muted-foreground">{label} {level}</span></span><ArrowRight className="size-4 text-muted-foreground"/></Link>)}</div>
 <section className="mt-4 rounded-2xl border bg-card p-4"><div className="flex items-start justify-between"><div><h2 className="text-[14px] font-bold">JLPT {level} Mock Test #01</h2><p className="mt-1 text-[10px] text-muted-foreground">Simulasi lengkap semua bagian ujian {level}</p></div><span className="rounded-full bg-primary/10 px-2 py-1 text-[9px] font-bold text-primary">FREE</span></div><div className="mt-3 space-y-2 text-[11px]"><div className="flex items-center gap-2"><Timer className="size-3.5 text-primary"/><span>Waktu mengikuti format level {level}</span></div><div className="flex items-center gap-2"><ListChecks className="size-3.5 text-primary"/><span>Free: simulasi penuh tanpa batas selama tahap pengembangan</span></div><div className="flex items-center gap-2"><Crown className="size-3.5 text-primary"/><span>Premium & Lifetime: fitur premium akan terus ditambahkan</span></div></div><Button asChild className="mt-4 h-10 w-full rounded-full text-[11px]"><Link to="/simulasi/$level" params={{level}}>Mulai Simulasi {level}<ArrowRight className="ml-1.5 size-3.5"/></Link></Button></section>
 <section className="mt-3 rounded-2xl border border-primary/20 bg-primary/[.04] p-4"><div className="flex items-center gap-2"><Crown className="size-4 text-primary"/><h2 className="text-[12px] font-bold">ENO Monthly Exam {level}</h2></div><p className="mt-1 text-[10px] leading-4 text-muted-foreground">Ujian bulanan mengikuti level profil.</p><Button className="mt-3 h-9 w-full rounded-full text-[10px]" disabled={!a?.monthlyExam}>{a?.monthlyExam?"Ikuti Monthly Exam":"Khusus Premium / Lifetime"}</Button></section></>}
 </div></AppShell>;
}
