import { createFileRoute, Link, Outlet } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, ArrowLeft, ArrowRight, Award, BookOpenCheck, CheckCircle2, Clock3, RotateCcw, XCircle } from "lucide-react";
import { AppShell } from "@/components/layout/AppShell";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { jlptSessions, sectionLabels } from "@/lib/jlpt-simulation-config";
import { buildPracticeResult, type FullProgress } from "@/lib/jlpt-simulation-result";
import type { Level } from "@/lib/learn-queries";

export const Route=createFileRoute("/_authenticated/simulasi-penuh/$level")({component:FullSimulationOverview});

function FullSimulationOverview(){
 const{level:rawLevel}=Route.useParams();const level=rawLevel.toUpperCase() as Level;const sessions=jlptSessions[level]??[];const storageKey=`eno-jlpt-full-${level}`;const totalMinutes=sessions.reduce((s,x)=>s+x.minutes,0);const[progress,setProgress]=useState<FullProgress|null>(null);const[confirmStart,setConfirmStart]=useState(false);
 useEffect(()=>{try{const raw=window.localStorage.getItem(storageKey);if(raw)setProgress(JSON.parse(raw))}catch{setProgress(null)}},[storageKey]);
 const active=useMemo(()=>progress?sessions[progress.sessionIndex]??null:null,[progress,sessions]);const finalResult=useMemo(()=>progress&&!active&&progress.results?buildPracticeResult(level,progress):null,[level,progress,active]);
 const clearServerState=()=>{window.localStorage.removeItem(`${storageKey}-server-id`);window.localStorage.removeItem(`${storageKey}-server-result`)};
 const openSession=(index:number)=>{window.location.assign(`/simulasi-penuh/${encodeURIComponent(level)}/${index}`)};
 const begin=()=>{setConfirmStart(false);clearServerState();const next:FullProgress={sessionIndex:0,sectionIndex:0,startedAt:Date.now(),completed:[],results:{}};window.localStorage.setItem(storageKey,JSON.stringify(next));setProgress(next);openSession(0)};
 const reset=()=>{for(let i=0;i<sessions.length;i++){window.localStorage.removeItem(`${storageKey}-session-${i}-answers`);window.localStorage.removeItem(`${storageKey}-session-${i}-deadline`)}clearServerState();window.localStorage.removeItem(storageKey);setProgress(null)};
 const isSessionRoute=typeof window!=="undefined"&&/^\/simulasi-penuh\/[^/]+\/[^/]+\/?$/.test(window.location.pathname);
 if(isSessionRoute)return <Outlet key={window.location.pathname}/>;
 return <AppShell title={`Simulasi JLPT ${level}`} compact><div className="mx-auto max-w-xl space-y-3"><div className="flex items-center justify-between"><Button asChild size="sm" variant="ghost"><Link to="/simulasi"><ArrowLeft className="mr-1 size-4"/>Kembali</Link></Button><span className="rounded-full bg-primary/10 px-3 py-1 text-xs font-semibold text-primary">本試験モード</span></div>
 {finalResult?<><Card className="rounded-2xl"><CardContent className="p-5 text-center">{finalResult.passed?<CheckCircle2 className="mx-auto size-10 text-primary"/>:<XCircle className="mx-auto size-10 text-destructive"/>}<p className="mt-3 text-xs font-semibold text-muted-foreground">日本語能力試験 {level} · ENO NIHONGO 模擬試験</p><h1 className="mt-2 text-2xl font-black">{finalResult.passed?"合格":"不合格"}</h1><p className="mt-1 text-sm font-semibold">{finalResult.passed?"Lulus":"Belum Lulus"}</p><div className="mt-5 text-4xl font-black">{finalResult.total}<span className="text-base font-semibold text-muted-foreground"> / 180</span></div>{finalResult.cefr&&<div className="mx-auto mt-4 w-fit rounded-xl bg-primary/10 px-5 py-2"><p className="text-[10px] font-semibold text-muted-foreground">CEFR REFERENCE</p><p className="text-xl font-black text-primary">{finalResult.cefr}</p></div>}<p className="mt-3 text-[10px] text-muted-foreground">Batas kelulusan simulasi: {finalResult.overallPass}/180 dan seluruh scoring section wajib melewati nilai minimum.</p></CardContent></Card><div className="space-y-2">{finalResult.blocks.map(b=><Card key={b.id} className="rounded-xl"><CardContent className="flex items-center justify-between gap-3 p-4"><span className="font-jp text-xs font-semibold">{b.label}</span><div className="text-right"><span className="text-sm font-black">{b.score} / {b.max}</span><p className="text-[9px] text-muted-foreground">Minimum {b.passMark}</p></div></CardContent></Card>)}</div><Card className="rounded-xl"><CardContent className="p-4 text-xs text-muted-foreground">Jawaban benar mentah: {finalResult.rawCorrect}/{finalResult.rawQuestions}. Skor simulasi ENO NIHONGO memakai struktur rentang dan batas kelulusan JLPT, tetapi bukan scaled score resmi JLPT. CEFR ditampilkan sebagai referensi hanya jika lulus.</CardContent></Card><Button asChild className="w-full"><Link to="/simulasi-hasil/$level" params={{level}}><BookOpenCheck className="mr-2 size-4"/>Lihat Pembahasan Soal</Link></Button>{finalResult.passed&&<Button asChild variant="outline" className="w-full"><Link to="/sertifikat-simulasi/$level" params={{level}}><Award className="mr-2 size-4"/>Lihat Sertifikat ENO NIHONGO</Link></Button>}<Button variant="outline" className="w-full" onClick={reset}><RotateCcw className="mr-1 size-4"/>Simulasi baru</Button></>:
 <><Card className="rounded-2xl"><CardContent className="p-5"><p className="text-xs font-semibold text-primary">日本語能力試験 {level}</p><h1 className="mt-1 text-xl font-bold">Simulasi Penuh</h1><p className="mt-2 text-xs leading-5 text-muted-foreground">Timer berlaku per sesi ujian. Setelah satu sesi selesai, simulasi berlanjut otomatis ke sesi berikutnya. Hasil baru ditampilkan setelah seluruh sesi selesai.</p><div className="mt-4 flex items-center gap-2 text-sm font-semibold"><Clock3 className="size-4 text-primary"/>Total sesi: {totalMinutes} menit</div></CardContent></Card><div className="space-y-2">{sessions.map((session,i)=>{const done=progress?i<progress.sessionIndex:false;const current=progress?.sessionIndex===i;return <button key={session.id} type="button" disabled={!current} onClick={()=>current&&openSession(i)} className="block w-full text-left disabled:cursor-default"><Card className={`rounded-2xl ${current?"border-primary cursor-pointer active:scale-[.99] transition-transform":""}`}><CardContent className="p-4"><div className="flex items-start justify-between gap-3"><div><p className="flex items-center gap-1 text-[10px] font-semibold text-muted-foreground">第 {i+1} セッション {done&&<CheckCircle2 className="size-3 text-primary"/>}</p><h2 className="mt-1 font-jp text-sm font-bold">{session.labelJp}</h2><p className="mt-2 text-[11px] text-muted-foreground">{session.sections.map(s=>sectionLabels[s]).join("・")}</p></div><span className="shrink-0 rounded-lg border px-2 py-1 text-xs font-bold">{session.minutes}分</span></div>{current&&<p className="mt-3 text-[10px] font-semibold text-primary">進行中 · タップして続ける</p>}</CardContent></Card></button>})}</div>{!progress?<Button className="w-full" onClick={()=>setConfirmStart(true)}>Mulai simulasi penuh<ArrowRight className="ml-1 size-4"/></Button>:active?<><Button className="w-full" onClick={()=>openSession(progress.sessionIndex)}>Lanjutkan sesi {progress.sessionIndex+1}<ArrowRight className="ml-1 size-4"/></Button><Button variant="outline" className="w-full" onClick={reset}><RotateCcw className="mr-1 size-4"/>Mulai ulang simulasi</Button></>:null}</>}
 {confirmStart&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4" role="dialog" aria-modal="true" aria-labelledby="start-simulation-title" onClick={()=>setConfirmStart(false)}><Card className="w-full max-w-sm rounded-2xl" onClick={e=>e.stopPropagation()}><CardContent className="p-5"><div className="flex items-start gap-3"><div className="rounded-full bg-amber-500/10 p-2"><AlertTriangle className="size-5 text-amber-600"/></div><div><h2 id="start-simulation-title" className="font-bold">Siap memulai simulasi?</h2><p className="mt-2 text-xs leading-5 text-muted-foreground">Timer Sesi 1 akan langsung berjalan setelah Anda menekan <b>Mulai sekarang</b>. Pastikan Anda sudah siap dan memiliki waktu untuk mengerjakan tanpa gangguan.</p></div></div><div className="mt-5 rounded-xl bg-muted p-3 text-xs"><div className="flex items-center justify-between"><span>Sesi pertama</span><b>{sessions[0]?.minutes??0} menit</b></div><div className="mt-2 flex items-center justify-between"><span>Total simulasi</span><b>{totalMinutes} menit</b></div></div><div className="mt-5 grid grid-cols-2 gap-2"><Button variant="outline" onClick={()=>setConfirmStart(false)}>Belum siap</Button><Button onClick={begin}>Mulai sekarang</Button></div></CardContent></Card></div>}
 </div></AppShell>;
}
