import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, CheckCircle2, ChevronDown, ChevronUp, CircleHelp, XCircle } from "lucide-react";
import { AppShell } from "@/components/layout/AppShell";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { supabase } from "@/integrations/supabase/client";

export const Route=createFileRoute("/_authenticated/simulasi-review/$attemptId")({component:SectionReviewPage});

type Item={question_id:string;section:string;mondai_no:number;question_no:number;display_question_no:number|null;question_type:string;instruction_jp:string;prompt_jp:string;choices:string[];selected_index:number|null;correct_index:number;is_correct:boolean;answered:boolean;passage_title:string|null;passage_jp:string|null;transcript_jp:string|null;image_url:string|null;explanation_indonesian:string|null};
type Filter="all"|"wrong"|"unanswered"|"correct";
const names:Record<string,string>={vocabulary:"文字・語彙",grammar:"文法",reading:"読解",listening:"聴解"};

function explain(x:Item){const answer=x.choices[x.correct_index]??"-";if(x.explanation_indonesian)return x.explanation_indonesian;if(x.section==="reading")return `Jawaban yang tepat adalah 「${answer}」. Cocokkan pilihan dengan informasi yang dinyatakan atau disimpulkan dari bacaan sumber.`;if(x.section==="listening")return `Jawaban yang tepat adalah 「${answer}」. Periksa transkrip bila tersedia dan cari bagian percakapan yang menentukan respons atau tindakan yang benar.`;if(x.question_type==="sentence_composition")return `Setelah unsur kalimat disusun dengan benar, 「${answer}」 adalah bagian yang menempati posisi ★.`;if(x.section==="grammar")return `Jawaban yang tepat adalah 「${answer}」 karena pilihan ini membentuk pola tata bahasa yang sesuai dengan hubungan sebelum dan sesudah bagian kosong.`;return `Jawaban yang tepat adalah 「${answer}」. Bandingkan kembali bacaan, bentuk, atau makna kata pada soal dengan pilihan yang Anda pilih.`}

function ReviewCard({x}:{x:Item}){const[open,setOpen]=useState(!x.is_correct);const no=x.display_question_no??x.question_no;return <Card className={`rounded-2xl ${x.is_correct?"border-primary/20":"border-destructive/25"}`}><CardContent className="p-4"><button className="flex w-full items-start justify-between gap-3 text-left" onClick={()=>setOpen(v=>!v)}><div className="flex gap-2">{x.is_correct?<CheckCircle2 className="mt-1 size-4 shrink-0 text-primary"/>:<XCircle className="mt-1 size-4 shrink-0 text-destructive"/>}<div><p className="text-[10px] font-bold text-muted-foreground">問題 {x.mondai_no} · 問 {no}</p><p className="mt-1 font-jp text-sm font-semibold leading-6">{x.prompt_jp}</p></div></div>{open?<ChevronUp className="size-4 shrink-0"/>:<ChevronDown className="size-4 shrink-0"/>}</button>{open&&<div className="mt-4 space-y-3 border-t pt-4">{x.image_url&&<img src={x.image_url} alt={`Ilustrasi soal ${no}`} className="mx-auto max-h-72 rounded-xl border object-contain"/>}<div className="space-y-2">{x.choices.map((choice,i)=>{const correct=i===x.correct_index,selected=x.answered&&i===x.selected_index;return <div key={i} className={`flex gap-2 rounded-xl border p-3 text-xs ${correct?"border-primary bg-primary/5":selected?"border-destructive/40 bg-destructive/5":""}`}><b>{i+1}.</b><span className="font-jp flex-1">{choice}</span>{correct&&<b className="text-[10px] text-primary">BENAR</b>}{selected&&!correct&&<b className="text-[10px] text-destructive">JAWABANMU</b>}</div>})}</div><div className="grid grid-cols-2 gap-2 text-[11px]"><div className="rounded-xl bg-muted/50 p-3"><p className="text-muted-foreground">Jawaban Anda</p><b className="mt-1 block">{x.answered?`${(x.selected_index??0)+1}. ${x.choices[x.selected_index??0]??"-"}`:"Tidak dijawab"}</b></div><div className="rounded-xl bg-primary/10 p-3"><p className="text-muted-foreground">Jawaban benar</p><b className="mt-1 block text-primary">{x.correct_index+1}. {x.choices[x.correct_index]??"-"}</b></div></div><div className="rounded-xl border border-primary/20 bg-primary/5 p-3"><div className="flex items-center gap-2 text-xs font-bold text-primary"><CircleHelp className="size-4"/>Pembahasan</div><p className="mt-2 text-xs leading-6">{explain(x)}</p></div>{x.passage_jp&&<details className="rounded-xl border p-3"><summary className="cursor-pointer text-xs font-semibold">Tampilkan bacaan sumber</summary>{x.passage_title&&<p className="mt-3 font-jp text-xs font-bold">{x.passage_title}</p>}<p className="mt-2 whitespace-pre-wrap font-jp text-xs leading-7">{x.passage_jp}</p></details>}{x.transcript_jp&&<details className="rounded-xl border p-3"><summary className="cursor-pointer text-xs font-semibold">Tampilkan transkrip Chōkai</summary><p className="mt-3 whitespace-pre-wrap font-jp text-xs leading-7">{x.transcript_jp}</p></details>}</div>}</CardContent></Card>}

function SectionReviewPage(){const{attemptId}=Route.useParams();const[items,setItems]=useState<Item[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);const[filter,setFilter]=useState<Filter>("all");useEffect(()=>{let active=true;(async()=>{try{const{data,error}=await(supabase as any).rpc("get_jlpt_simulation_attempt_review",{p_attempt_id:attemptId});if(error)throw error;if(active)setItems(Array.isArray(data)?data:[])}catch(e){console.error(e);if(active)setError("Pembahasan belum dapat dibuka. Untuk simulasi penuh, pembahasan baru tersedia setelah seluruh ujian selesai.")}finally{if(active)setLoading(false)}})();return()=>{active=false}},[attemptId]);const shown=useMemo(()=>items.filter(x=>filter==="all"?true:filter==="correct"?x.is_correct:filter==="unanswered"?!x.answered:x.answered&&!x.is_correct),[items,filter]);const title=items[0]?names[items[0].section]??items[0].section:"Simulasi";return <AppShell title="Pembahasan Simulasi" compact><div className="mx-auto max-w-2xl space-y-3"><Button asChild size="sm" variant="ghost"><Link to="/simulasi"><ArrowLeft className="mr-1 size-4"/>Simulasi</Link></Button><Card className="rounded-2xl"><CardContent className="p-5"><p className="text-[10px] font-bold uppercase tracking-widest text-primary">Review</p><h1 className="mt-1 text-xl font-black">Pembahasan {title}</h1><p className="mt-2 text-xs text-muted-foreground">Jawaban dan kunci ditampilkan setelah sesi latihan selesai. Kunci simulasi penuh tetap terkunci sampai seluruh ujian selesai.</p><div className="mt-4 flex gap-2 overflow-x-auto">{([['all','Semua'],['wrong','Salah'],['unanswered','Kosong'],['correct','Benar']] as [Filter,string][]).map(([id,label])=><Button key={id} size="sm" variant={filter===id?"default":"outline"} onClick={()=>setFilter(id)}>{label}</Button>)}</div></CardContent></Card>{loading?<Card><CardContent className="p-6 text-center text-xs text-muted-foreground">Memuat pembahasan…</CardContent></Card>:error?<Card><CardContent className="p-6 text-center text-xs text-destructive">{error}</CardContent></Card>:shown.length?<div className="space-y-3">{shown.map(x=><ReviewCard key={x.question_id} x={x}/>)}</div>:<Card><CardContent className="p-6 text-center text-xs text-muted-foreground">Tidak ada soal pada filter ini.</CardContent></Card>}</div></AppShell>}
