import { createFileRoute, Link } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, Check } from "lucide-react";
import { AppShell } from "@/components/layout/AppShell";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { supabase } from "@/integrations/supabase/client";
import type { Database } from "@/integrations/supabase/types";
import type { Level } from "@/lib/learn-queries";

export const Route=createFileRoute("/_authenticated/simulasi-bagian/$level/$section")({component:SectionRunner});
const labels:Record<string,string>={vocabulary:"文字・語彙 · Kanji & Kosakata",grammar:"文法 · Bunpō",reading:"読解 · Dokkai",listening:"聴解 · Chōkai"};
type Skill=Database["public"]["Enums"]["skill_kind"];
type QuestionRow=Pick<Database["public"]["Tables"]["questions"]["Row"],"id"|"prompt"|"prompt_note"|"choices"|"correct_index"|"explanation_id"|"skill">;
type SimulationQuestion=Omit<QuestionRow,"choices">&{choices:string[]};
function isFourChoiceQuestion(q:QuestionRow):q is QuestionRow&{choices:string[]}{return Array.isArray(q.choices)&&q.choices.length===4&&q.choices.every(choice=>typeof choice==="string")}
async function fetchQuestions(level:Level,section:string):Promise<SimulationQuestion[]>{const skills:Skill[]=section==="vocabulary"?["vocabulary","kanji"]:[section as Skill];const{data,error}=await supabase.from("questions").select("id,prompt,prompt_note,choices,correct_index,explanation_id,skill").eq("is_published",true).eq("level",level).in("skill",skills).limit(20);if(error)throw error;return(data??[]).filter(isFourChoiceQuestion)}
function SectionRunner(){
 const params=Route.useParams();const level=params.level.toUpperCase() as Level;const section=params.section;const q=useQuery({queryKey:["simulation-section",level,section],queryFn:()=>fetchQuestions(level,section)});const questions=useMemo(()=>q.data??[],[q.data]);const[index,setIndex]=useState(0);const[answers,setAnswers]=useState<Record<string,number>>({});const[finished,setFinished]=useState(false);const[saving,setSaving]=useState(false);const current=questions[index];const correct=useMemo(()=>questions.reduce((n,x)=>n+(answers[x.id]===x.correct_index?1:0),0),[questions,answers]);
 const finish=async()=>{setSaving(true);try{const{data:auth}=await supabase.auth.getUser();if(!auth.user)throw new Error("Sesi tidak ditemukan.");const score=questions.length?Math.round(correct/questions.length*10000)/100:0;const skill:Skill=section==="vocabulary"?"vocabulary":section as Skill;const{data:attempt,error}=await supabase.from("quiz_attempts").insert({user_id:auth.user.id,quiz_id:null,level,skill,total_questions:questions.length,correct_count:correct,score,xp_earned:correct*10,duration_seconds:0,completed_at:new Date().toISOString()}).select("id").single();if(error)throw error;if(attempt){const userId=auth.user.id;await supabase.from("quiz_answers").insert(questions.map(x=>({attempt_id:attempt.id,user_id:userId,question_id:x.id,selected_index:answers[x.id]??-1,is_correct:answers[x.id]===x.correct_index})));}setFinished(true);}catch(e){alert(e instanceof Error?e.message:"Gagal menyimpan simulasi.")}finally{setSaving(false)}};
 if(q.isLoading)return <AppShell title="Simulasi Bagian"><p className="py-10 text-center text-xs text-muted-foreground">Menyiapkan soal…</p></AppShell>;
 if(!questions.length)return <AppShell title="Simulasi Bagian"><Card><CardContent className="p-6 text-center text-xs">Belum ada soal untuk bagian ini.<Button asChild className="mt-4"><Link to="/simulasi">Kembali</Link></Button></CardContent></Card></AppShell>;
 if(finished)return <AppShell title="Hasil Simulasi"><div className="mx-auto max-w-md"><Card><CardContent className="p-6 text-center"><Check className="mx-auto size-8 text-primary"/><h1 className="mt-3 text-xl font-bold">{Math.round(correct/questions.length*100)}%</h1><p className="mt-1 text-xs text-muted-foreground">{correct} benar dari {questions.length} soal</p><p className="mt-3 text-[10px] text-primary">Poin simulasi bagian sudah ditambahkan.</p><Button asChild className="mt-4 w-full"><Link to="/simulasi">Kembali ke Simulasi</Link></Button></CardContent></Card></div></AppShell>;
 return <AppShell title={labels[section]??"Simulasi Bagian"} compact><div className="mx-auto max-w-md"><div className="mb-3 flex items-center justify-between text-[10px] text-muted-foreground"><span>{level}</span><span>Soal {index+1}/{questions.length}</span></div><Card className="rounded-2xl"><CardContent className="p-4"><h1 className="text-[14px] font-semibold leading-6">{current.prompt}</h1>{current.prompt_note&&<p className="mt-1 text-[10px] text-muted-foreground">{current.prompt_note}</p>}<div className="mt-4 space-y-2">{current.choices.map((choice,i)=><button key={i} onClick={()=>setAnswers(v=>({...v,[current.id]:i}))} className={`w-full rounded-xl border p-3 text-left text-[12px] ${answers[current.id]===i?"border-primary bg-primary/5":""}`}>{String.fromCharCode(65+i)}. {choice}</button>)}</div><div className="mt-5 flex justify-between gap-2"><Button variant="outline" disabled={index===0} onClick={()=>setIndex(v=>v-1)}><ArrowLeft className="mr-1 size-4"/>Sebelumnya</Button>{index===questions.length-1?<Button disabled={saving} onClick={()=>void finish()}><Check className="mr-1 size-4"/>Selesai</Button>:<Button disabled={answers[current.id]===undefined} onClick={()=>setIndex(v=>v+1)}>Berikutnya<ArrowRight className="ml-1 size-4"/></Button>}</div></CardContent></Card></div></AppShell>;
}
