INSERT INTO public.vocabulary_source_items (id,vocabulary_id,term,reading,meaning_id,lexical_class,subgroup,source_book,source_order,level_hint,is_verified,created_at,lesson_number,lesson_title,accent,verb_group,is_reference,is_expression,source_section) VALUES
(gen_random_uuid(),NULL,'ある（町にあるもの）','ある','ada (berbagai hal / sesuatu yang ada di kota)',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',60001,NULL,TRUE,now(),6,NULL,'あ↓る',1,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'もの','もの','hal / sesuatu; benda',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',60002,NULL,TRUE,now(),6,NULL,'もの↓',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'信号','しんごう','lampu lalu lintas',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',60003,NULL,TRUE,now(),6,NULL,'しんごう○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'横断歩道','おうだんほどう','penyeberangan pejalan kaki; zebra cross',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',60004,NULL,TRUE,now(),6,NULL,'おうだんほ↓どう',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'角','かど','sudut',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',60005,NULL,TRUE,now(),6,NULL,'か↓ど',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'交差点','こうさてん','persimpangan',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',60006,NULL,TRUE,now(),6,NULL,'こうさてん○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'道','みち','jalan',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',60007,NULL,TRUE,now(),6,NULL,'みち○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'橋','はし','jembatan',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',60008,NULL,TRUE,now(),6,NULL,'はし↓',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'道案内','みちあんない','petunjuk arah',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',60009,NULL,TRUE,now(),6,NULL,'みちあ↓んない',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'まっすぐ','まっすぐ','lurus',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',60010,NULL,TRUE,now(),6,NULL,'まっす↓ぐ',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'左','ひだり','kiri',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',60011,NULL,TRUE,now(),6,NULL,'ひだり○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'曲がる','まがる','belok; berbelok',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',60012,NULL,TRUE,now(),6,NULL,'まがる○',1,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'右','みぎ','kanan',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',60013,NULL,TRUE,now(),6,NULL,'みぎ○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'渡る','わたる','menyeberang',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',60014,NULL,TRUE,now(),6,NULL,'わたる○',1,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'～つ目','～つめ','yang~ (menyatakan urutan; angka)',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',60015,NULL,TRUE,now(),6,NULL,'～つめ↓',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'1つ目','ひとつめ','pertama',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',60016,NULL,TRUE,now(),6,NULL,'ひとつめ↓',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'2つ目','ふたつめ','kedua',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',60017,NULL,TRUE,now(),6,NULL,'ふたつめ↓',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'バス停','バスてい','pemberhentian bus; halte bus',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',60018,NULL,TRUE,now(),6,NULL,'バスてい○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'郵便局','ゆうびんきょく','kantor pos',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',60019,NULL,TRUE,now(),6,NULL,'ゆうび↓んきょく',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'デパート','デパート','toserba; pasaraya; department store',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',60020,NULL,TRUE,now(),6,NULL,'デパ↓ート',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'科学','かがく','ilmu pengetahuan',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',60021,NULL,TRUE,now(),6,NULL,'か↓がく',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'博物館','はくぶつかん','museum',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',60022,NULL,TRUE,now(),6,NULL,'はくぶつ↓かん',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'ずっと','ずっと','(lurus) terus',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',60023,NULL,TRUE,now(),6,NULL,'ずっと○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'銀行','ぎんこう','bank',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',60024,NULL,TRUE,now(),6,NULL,'ぎんこう○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'神社','じんじゃ','kuil Shinto',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',60025,NULL,TRUE,now(),6,NULL,'じ↓んじゃ',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'駐車場','ちゅうしゃじょう','tempat parkir',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',60026,NULL,TRUE,now(),6,NULL,'ちゅうしゃじょう○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'交番','こうばん','pos polisi',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',60027,NULL,TRUE,now(),6,NULL,'こうばん○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'病院','びょういん','rumah sakit',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',60028,NULL,TRUE,now(),6,NULL,'びょういん○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'黒い','くろい','hitam',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',60029,NULL,TRUE,now(),6,NULL,'くろ↓い',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'白い','しろい','putih',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',60030,NULL,TRUE,now(),6,NULL,'しろ↓い',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'青い','あおい','biru',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',60031,NULL,TRUE,now(),6,NULL,'あお↓い',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'ビル','ビル','bangunan',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',60032,NULL,TRUE,now(),6,NULL,'ビ↓ル',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'アジア食材','アジアしょくざい','bahan makanan khas Asia',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',60033,NULL,TRUE,now(),6,NULL,'アジアしょ↓くざい',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'そちら','そちら','di situ',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',60034,NULL,TRUE,now(),6,NULL,'そちら○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'北口','きたぐち','pintu utara',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',60035,NULL,TRUE,now(),6,NULL,'きたぐち○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'間（～と～の間）','あいだ','di antara ～ dan ～',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',60036,NULL,TRUE,now(),6,NULL,'あいだ○（～と～のあいだ○）',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'そうすると','そうすると','setelah itu',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',60037,NULL,TRUE,now(),6,NULL,'そうすると○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'見える','みえる','terlihat',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',60038,NULL,TRUE,now(),6,NULL,'みえ↓る',2,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'お待ちしております','おまちしております','kami menantikan kedatangan Anda.',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',60039,NULL,TRUE,now(),6,NULL,'おまちしておりま↓す',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'帰る','かえる','pulang',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',60040,NULL,TRUE,now(),6,NULL,'か↓える',1,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'～町（小島町）','～ちょう','Kota~ (pembagian geografis dalam suatu distrik, mis. Kojima-cho / Kota Kojima)',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',60041,NULL,TRUE,now(),6,NULL,'～ちょう（こじまちょう○）',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'高校','こうこう','SMA',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',60042,NULL,TRUE,now(),6,NULL,'こうこう○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'送る','おくる','mengantar (orang)',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',60043,NULL,TRUE,now(),6,NULL,'おくる○',1,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'大きな','おおきな','besar',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',60044,NULL,TRUE,now(),6,NULL,'お↓おきな',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'入る','はいる','masuk; berbelok',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',60045,NULL,TRUE,now(),6,NULL,'は↓いる',1,FALSE,FALSE,NULL)
ON CONFLICT (source_book,source_order,term) DO UPDATE SET reading=EXCLUDED.reading,meaning_id=EXCLUDED.meaning_id,accent=EXCLUDED.accent,verb_group=EXCLUDED.verb_group,lesson_number=EXCLUDED.lesson_number,is_verified=TRUE;
