revoke execute on function public.get_admin_overview() from public, anon;
grant execute on function public.get_admin_overview() to authenticated;
revoke execute on function public.award_referral_signup(text) from public, anon;
grant execute on function public.award_referral_signup(text) to authenticated;
revoke execute on function public.can_start_full_simulation() from public, anon;
grant execute on function public.can_start_full_simulation() to authenticated;
revoke execute on function public.create_or_replace_study_plan(public.jlpt_level,date,integer) from public, anon;
grant execute on function public.create_or_replace_study_plan(public.jlpt_level,date,integer) to authenticated;
revoke execute on function public.ensure_active_study_plan() from public, anon;
grant execute on function public.ensure_active_study_plan() to authenticated;
revoke execute on function public.generate_daily_study_tasks(date) from public, anon;
grant execute on function public.generate_daily_study_tasks(date) to authenticated;
revoke execute on function public.get_my_dashboard_metrics() from public, anon;
grant execute on function public.get_my_dashboard_metrics() to authenticated;
revoke execute on function public.get_my_membership() from public, anon;
grant execute on function public.get_my_membership() to authenticated;
revoke execute on function public.get_target_page_metrics() from public, anon;
grant execute on function public.get_target_page_metrics() to authenticated;
revoke execute on function public.is_premium(uuid) from public, anon;
grant execute on function public.is_premium(uuid) to authenticated;
revoke execute on function public.mark_item_mastered(text,uuid,public.jlpt_level) from public, anon;
grant execute on function public.mark_item_mastered(text,uuid,public.jlpt_level) to authenticated;
revoke execute on function public.record_learning_activity(text,integer,integer,jsonb) from public, anon;
grant execute on function public.record_learning_activity(text,integer,integer,jsonb) to authenticated;
revoke execute on function public.record_learning_activity(text,text,uuid,integer,integer,boolean,integer,jsonb) from public, anon;
grant execute on function public.record_learning_activity(text,text,uuid,integer,integer,boolean,integer,jsonb) to authenticated;
revoke execute on function public.redeem_referral_points(integer) from public, anon;
grant execute on function public.redeem_referral_points(integer) to authenticated;
revoke execute on function public.submit_quiz_attempt(uuid,public.jlpt_level,public.content_skill,jsonb,integer) from public, anon;
grant execute on function public.submit_quiz_attempt(uuid,public.jlpt_level,public.content_skill,jsonb,integer) to authenticated;
revoke execute on function public.sync_daily_study_task_progress(date) from public, anon;
grant execute on function public.sync_daily_study_task_progress(date) to authenticated;
