create schema if not exists backup;
create table if not exists backup.kanji_pre_curriculum as table public.kanji with no data;
create table if not exists backup.vocabulary_pre_curriculum as table public.vocabulary with no data;
create table if not exists backup.grammar_points_pre_curriculum as table public.grammar_points with no data;
insert into backup.kanji_pre_curriculum select * from public.kanji where not exists (select 1 from backup.kanji_pre_curriculum);
insert into backup.vocabulary_pre_curriculum select * from public.vocabulary where not exists (select 1 from backup.vocabulary_pre_curriculum);
insert into backup.grammar_points_pre_curriculum select * from public.grammar_points where not exists (select 1 from backup.grammar_points_pre_curriculum);
with ranked as (select id, level::text lvl, row_number() over (partition by level order by sort_order, id) rn, count(*) over (partition by level) total from public.kanji where lesson_number is null)
update public.kanji k set lesson_number = case when ranked.lvl='N5' then ceil(ranked.rn::numeric/ranked.total*25)::int when ranked.lvl='N4' then 25+ceil(ranked.rn::numeric/ranked.total*25)::int when ranked.lvl in ('N3','N2','N1') then ceil(ranked.rn::numeric/ranked.total*36)::int end, lesson_title = case when ranked.lvl in ('N5','N4') then 'Minna no Nihongo — 課 ' || case when ranked.lvl='N5' then ceil(ranked.rn::numeric/ranked.total*25)::int else 25+ceil(ranked.rn::numeric/ranked.total*25)::int end else 'Sō-Matome — Week ' || ceil(ceil(ranked.rn::numeric/ranked.total*36)::numeric/6)::int || ' Day ' || (((ceil(ranked.rn::numeric/ranked.total*36)::int-1)%6)+1) end from ranked where k.id=ranked.id;
with ranked as (select id, level::text lvl, row_number() over (partition by level order by sort_order, id) rn, count(*) over (partition by level) total from public.vocabulary where lesson_number is null)
update public.vocabulary v set lesson_number = case when ranked.lvl='N5' then ceil(ranked.rn::numeric/ranked.total*25)::int when ranked.lvl='N4' then 25+ceil(ranked.rn::numeric/ranked.total*25)::int when ranked.lvl in ('N3','N2','N1') then ceil(ranked.rn::numeric/ranked.total*36)::int end, lesson_title = case when ranked.lvl in ('N5','N4') then 'Minna no Nihongo — 課 ' || case when ranked.lvl='N5' then ceil(ranked.rn::numeric/ranked.total*25)::int else 25+ceil(ranked.rn::numeric/ranked.total*25)::int end else 'Sō-Matome — Week ' || ceil(ceil(ranked.rn::numeric/ranked.total*36)::numeric/6)::int || ' Day ' || (((ceil(ranked.rn::numeric/ranked.total*36)::int-1)%6)+1) end from ranked where v.id=ranked.id;
with ranked as (select id, level::text lvl, row_number() over (partition by level order by sort_order, id) rn, count(*) over (partition by level) total from public.grammar_points where lesson_number is null)
update public.grammar_points g set lesson_number = case when ranked.lvl='N5' then ceil(ranked.rn::numeric/ranked.total*25)::int when ranked.lvl='N4' then 25+ceil(ranked.rn::numeric/ranked.total*25)::int when ranked.lvl in ('N3','N2','N1') then ceil(ranked.rn::numeric/ranked.total*36)::int end, lesson_title = case when ranked.lvl in ('N5','N4') then 'Minna no Nihongo — 課 ' || case when ranked.lvl='N5' then ceil(ranked.rn::numeric/ranked.total*25)::int else 25+ceil(ranked.rn::numeric/ranked.total*25)::int end else 'Sō-Matome — Week ' || ceil(ceil(ranked.rn::numeric/ranked.total*36)::numeric/6)::int || ' Day ' || (((ceil(ranked.rn::numeric/ranked.total*36)::int-1)%6)+1) end from ranked where g.id=ranked.id;
