INSERT INTO public.vocabulary_source_items (id,vocabulary_id,term,reading,meaning_id,lexical_class,subgroup,source_book,source_order,level_hint,is_verified,created_at,lesson_number,lesson_title,accent,verb_group,is_reference,is_expression,source_section) VALUES
(gen_random_uuid(),NULL,'日本語学校','にほんごがっこう','Sekolah bahasa Jepang',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',90001,NULL,TRUE,now(),9,NULL,'にほんごが↓っこう',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'高校','こうこう','SMA',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',90002,NULL,TRUE,now(),9,NULL,'こうこう○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'どれぐらい','どれぐらい','berapa lama',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',90003,NULL,TRUE,now(),9,NULL,'どれぐらい○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'上手（な）','じょうず','pandai / terampil',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',90004,NULL,TRUE,now(),9,NULL,'じょうず↓（な）',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'～間（2年間）','～かん','selama ～ (selama 2 tahun)',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',90005,NULL,TRUE,now(),9,NULL,'～かん（にね↓んかん）',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'自分で','じぶんで','melakukan sendiri',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',90006,NULL,TRUE,now(),9,NULL,'じぶんで○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'まだまだです','まだまだです','masih belum begitu mahir.',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',90007,NULL,TRUE,now(),9,NULL,'ま↓だ△ま↓だです',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'そんなことないです','そんなことないです','tidak juga',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',90008,NULL,TRUE,now(),9,NULL,'そんなこ↓とな↓いです',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'大学','だいがく','universitas',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',90009,NULL,TRUE,now(),9,NULL,'だいがく○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'ラジオ','ラジオ','radio',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',90010,NULL,TRUE,now(),9,NULL,'ラ↓ジオ',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'ネット','ネット','internet',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',90011,NULL,TRUE,now(),9,NULL,'ネット○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'アプリ','アプリ','aplikasi',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',90012,NULL,TRUE,now(),9,NULL,'ア↓プリ',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'日本語','にほんご','Bahasa Jepang',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',90013,NULL,TRUE,now(),9,NULL,'にほんご○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'勉強','べんきょう','belajar',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',90014,NULL,TRUE,now(),9,NULL,'べんきょう○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'簡単（な）','かんたん','mudah; gampang',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',90015,NULL,TRUE,now(),9,NULL,'かんたん（な）○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'難しい','むずかしい','susah; sulit',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',90016,NULL,TRUE,now(),9,NULL,'むずかしい○／むずかし↓い',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'似ている','にている','serupa; mirip',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',90017,NULL,TRUE,now(),9,NULL,'にている○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'違う','ちがう','berbeda',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',90018,NULL,TRUE,now(),9,NULL,'ちがう○',1,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'得意（な）','とくい','mahir; pandai',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',90019,NULL,TRUE,now(),9,NULL,'とく↓い（な）／とくいな○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'苦手（な）','にがて','tidak mahir; tidak pandai',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',90020,NULL,TRUE,now(),9,NULL,'にがて（な）○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'文法','ぶんぽう','tata bahasa',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',90021,NULL,TRUE,now(),9,NULL,'ぶんぽう○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'発音','はつおん','pelafalan; pengucapan',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',90022,NULL,TRUE,now(),9,NULL,'はつおん○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'会話','かいわ','percakapan',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',90023,NULL,TRUE,now(),9,NULL,'かいわ○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'モンゴル語','モンゴルご','bahasa Mongolia',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',90024,NULL,TRUE,now(),9,NULL,'モンゴルご○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'ベトナム語','ベトナムご','bahasa Vietnam',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',90025,NULL,TRUE,now(),9,NULL,'ベトナムご○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'覚える','おぼえる','menghafal',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',90026,NULL,TRUE,now(),9,NULL,'おぼえ↓る',2,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'教える','おしえる','mengajar; mengajarkan',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',90027,NULL,TRUE,now(),9,NULL,'おしえる○',2,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'辞書','じしょ','kamus',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',90028,NULL,TRUE,now(),9,NULL,'じ↓しょ',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'貸す','かす','meminjamkan',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',90029,NULL,TRUE,now(),9,NULL,'かす○',1,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'見せる','みせる','memperlihatkan',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',90030,NULL,TRUE,now(),9,NULL,'みせ↓る',2,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'チェックする','チェックする','memeriksa',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',90031,NULL,TRUE,now(),9,NULL,'チェ↓ックする',3,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'説明する','せつめいする','menjelaskan',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',90032,NULL,TRUE,now(),9,NULL,'せつめいする○',3,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'紙','かみ','kertas',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',90033,NULL,TRUE,now(),9,NULL,'かみ↓',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'書く','かく','menulis',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',90034,NULL,TRUE,now(),9,NULL,'か↓く',1,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'言う','いう','mengatakan; mengucapkan',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',90035,NULL,TRUE,now(),9,NULL,'いう○',1,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'ゆっくり','ゆっくり','pelan-pelan',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',90036,NULL,TRUE,now(),9,NULL,'ゆっく↓り',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'～方（読み方）','～かた','cara～ (cara membaca)',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',90037,NULL,TRUE,now(),9,NULL,'～かた（よみか↓た）',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'メール','メール','surel (surat elektronik)',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',90038,NULL,TRUE,now(),9,NULL,'メール○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'書類','しょるい','dokumen',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',90039,NULL,TRUE,now(),9,NULL,'しょるい○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'教科書','きょうかしょ','buku pelajaran',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',90040,NULL,TRUE,now(),9,NULL,'きょうか↓しょ',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'自信がありません','じしんがありません','tidak percaya diri',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',90041,NULL,TRUE,now(),9,NULL,'じしんがありませ↓ん',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'練習','れんしゅう','latihan',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',90042,NULL,TRUE,now(),9,NULL,'れんしゅう○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'探す','さがす','mencari',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',90043,NULL,TRUE,now(),9,NULL,'さがす○',1,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'知恵','ちえ','kebijaksanaan',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',90044,NULL,TRUE,now(),9,NULL,'ちえ↓',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'拝借する','はいしゃくする','meminjam',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',90045,NULL,TRUE,now(),9,NULL,'はいしゃくする○',3,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'サイト','サイト','situs web',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',90046,NULL,TRUE,now(),9,NULL,'サイト○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'トップ','トップ','(halaman) utama',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',90047,NULL,TRUE,now(),9,NULL,'ト↓ップ',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'カテゴリー','カテゴリー','kategori',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',90048,NULL,TRUE,now(),9,NULL,'カテ↓ゴリー／カ↓テゴリー',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'ランキング','ランキング','peringkat',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',90049,NULL,TRUE,now(),9,NULL,'ランキング○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'わし','わし','Saya (pengucapan ini biasanya digunakan oleh orang yang sudah tua atau lansia)',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',90050,NULL,TRUE,now(),9,NULL,'わし○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'検索','けんさく','pencarian',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',90051,NULL,TRUE,now(),9,NULL,'けんさく○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'質問','しつもん','pertanyaan',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',90052,NULL,TRUE,now(),9,NULL,'しつもん○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'相談','そうだん','konsultasi',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',90053,NULL,TRUE,now(),9,NULL,'そうだん○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'おしゃべりする','おしゃべりする','berbincang',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',90054,NULL,TRUE,now(),9,NULL,'おしゃ↓べりする',3,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'シャドーイングする','シャドーイングする','(melakukan latihan dengan) teknik shadowing',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',90055,NULL,TRUE,now(),9,NULL,'シャドーイングする○',3,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'ボランティア','ボランティア','sukarelawan',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',90056,NULL,TRUE,now(),9,NULL,'ボラ↓ンティア',NULL,FALSE,FALSE,NULL)
ON CONFLICT (source_book,source_order,term) DO UPDATE SET reading=EXCLUDED.reading,meaning_id=EXCLUDED.meaning_id,accent=EXCLUDED.accent,verb_group=EXCLUDED.verb_group,lesson_number=EXCLUDED.lesson_number,is_verified=TRUE;
