insert into public.vocabulary_source_items(term,reading,meaning_id,lexical_class,subgroup,source_book,source_order,level_hint,is_verified,lesson_number,lesson_title,accent,verb_group,is_expression,source_section) values
('旅行する','りょこうする','berwisata; bepergian','kata_kerja','kata_kerja','Kotoba Irodori A1 Buku Pink.pdf',1800001,null,true,18,'温泉に入りたいです','りょこうする○／',3,false,'Daftar Kosakata'),
('友だち','ともだち','teman',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1800002,null,true,18,'温泉に入りたいです','ともだち○',null,false,'Daftar Kosakata'),
('会う','あう','bertemu','kata_kerja','kata_kerja','Kotoba Irodori A1 Buku Pink.pdf',1800003,null,true,18,'温泉に入りたいです','あ↓う／あいま↓す',1,false,'Daftar Kosakata'),
('行く','いく','pergi','kata_kerja','kata_kerja','Kotoba Irodori A1 Buku Pink.pdf',1800004,null,true,18,'温泉に入りたいです','いく○／いきま↓す',1,false,'Daftar Kosakata'),
('炊飯器','すいはんき','penanak nasi',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1800005,null,true,18,'温泉に入りたいです','すいは↓んき',null,false,'Daftar Kosakata'),
('買う','かう','membeli','kata_kerja','kata_kerja','Kotoba Irodori A1 Buku Pink.pdf',1800006,null,true,18,'温泉に入りたいです','かう○／かいま↓す',1,false,'Daftar Kosakata'),
('うち','うち','rumah',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1800007,null,true,18,'温泉に入りたいです','うち○',null,false,'Daftar Kosakata'),
('もうすぐ','もうすぐ','sebentar lagi',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1800008,null,true,18,'温泉に入りたいです','もうす↓ぐ',null,false,'Daftar Kosakata'),
('夏休み','なつやすみ','libur musim panas',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1800009,null,true,18,'温泉に入りたいです','なつや↓すみ',null,false,'Daftar Kosakata'),
('広島','ひろしま','Hiroshima',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1800010,null,true,18,'温泉に入りたいです','ひろしま○',null,false,'Daftar Kosakata'),
('連休','れんきゅう','libur panjang',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1800011,null,true,18,'温泉に入りたいです','れんきゅう○',null,false,'Daftar Kosakata'),
('どこか','どこか','ke suatu tempat',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1800012,null,true,18,'温泉に入りたいです','ど↓こか',null,false,'Daftar Kosakata'),
('予定','よてい','rencana',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1800013,null,true,18,'温泉に入りたいです','よてい○',null,false,'Daftar Kosakata'),
('池袋','いけぶくろ','Ikebukuro',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1800014,null,true,18,'温泉に入りたいです','いけぶ↓くろ',null,false,'Daftar Kosakata'),
('ディズニーランド','ディズニーランド','Disneyland',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1800015,null,true,18,'温泉に入りたいです','ディズニーラ↓ンド',null,false,'Daftar Kosakata'),
('富士山','ふじさん','Gunung Fuji',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1800016,null,true,18,'温泉に入りたいです','ふ↓じさん',null,false,'Daftar Kosakata'),
('登る','のぼる','mendaki','kata_kerja','kata_kerja','Kotoba Irodori A1 Buku Pink.pdf',1800017,null,true,18,'温泉に入りたいです','のぼる○／のぼりま↓す',1,false,'Daftar Kosakata'),
('京都','きょうと','Kyoto',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1800018,null,true,18,'温泉に入りたいです','きょ↓うと',null,false,'Daftar Kosakata'),
('神社','じんじゃ','kuil Shinto',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1800019,null,true,18,'温泉に入りたいです','じ↓んじゃ',null,false,'Daftar Kosakata'),
('雪','ゆき','salju',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1800020,null,true,18,'温泉に入りたいです','ゆき↓',null,false,'Daftar Kosakata'),
('見る','みる','melihat; menonton','kata_kerja','kata_kerja','Kotoba Irodori A1 Buku Pink.pdf',1800021,null,true,18,'温泉に入りたいです','み↓る／みま↓す',2,false,'Daftar Kosakata'),
('どら焼き','どらやき','dorayaki (kue yang berisi pasta kacang merah)',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1800022,null,true,18,'温泉に入りたいです','どらやき○',null,false,'Daftar Kosakata'),
('食べる','たべる','makan','kata_kerja','kata_kerja','Kotoba Irodori A1 Buku Pink.pdf',1800023,null,true,18,'温泉に入りたいです','たべ↓る／たべま↓す',2,false,'Daftar Kosakata'),
('温泉','おんせん','onsen (kolam pemandian air panas)',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1800024,null,true,18,'温泉に入りたいです','おんせん○',null,false,'Daftar Kosakata'),
('入る','はいる','masuk','kata_kerja','kata_kerja','Kotoba Irodori A1 Buku Pink.pdf',1800025,null,true,18,'温泉に入りたいです','は↓いる／はいりま↓す',1,false,'Daftar Kosakata'),
('お土産','おみやげ','oleh-oleh; buah tangan',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1800026,null,true,18,'温泉に入りたいです','おみやげ○',null,false,'Daftar Kosakata'),
('ぜひ','ぜひ','harus',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1800027,null,true,18,'温泉に入りたいです','ぜ↓ひ',null,false,'Daftar Kosakata'),
('ほかに','ほかに','selain itu',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1800028,null,true,18,'温泉に入りたいです','ほかに○',null,false,'Daftar Kosakata'),
('あと','あと','dan; juga',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1800029,null,true,18,'温泉に入りたいです','あ↓と',null,false,'Daftar Kosakata'),
('どうして','どうして','mengapa; kenapa',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1800030,null,true,18,'温泉に入りたいです','ど↓うして',null,false,'Daftar Kosakata'),
('行って','いって','Anda harus pergi; Pergilah.',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1800031,null,true,18,'温泉に入りたいです','いって○',null,true,'Daftar Kosakata'),
('新宿','しんじゅく','Shinjuku',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1800032,null,true,18,'温泉に入りたいです','しんじゅく○',null,false,'Daftar Kosakata'),
('須賀神社','すがじんじゃ','Kuil Suga',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1800033,null,true,18,'温泉に入りたいです','すがじ↓んじゃ',null,false,'Daftar Kosakata'),
('写真','しゃしん','foto',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1800034,null,true,18,'温泉に入りたいです','しゃしん○',null,false,'Daftar Kosakata'),
('動画','どうが','video',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1800035,null,true,18,'温泉に入りたいです','どうが○',null,false,'Daftar Kosakata'),
('気分','きぶん','perasaan',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1800036,null,true,18,'温泉に入りたいです','き↓ぶん',null,false,'Daftar Kosakata'),
('アクティビティ','アクティビティ','aktivitas',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1800037,null,true,18,'温泉に入りたいです','アクティ↓ビティ',null,false,'Daftar Kosakata'),
('チェックイン','チェックイン','singgah',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1800038,null,true,18,'温泉に入りたいです','チェックイ↓ン',null,false,'Daftar Kosakata'),
('それに','それに','selain itu',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1800039,null,true,18,'温泉に入りたいです','それに○',null,false,'Daftar Kosakata'),
('景色','けしき','pemandangan',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1800040,null,true,18,'温泉に入りたいです','け↓しき',null,false,'Daftar Kosakata'),
('それから','それから','kemudian',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1800041,null,true,18,'温泉に入りたいです','それから○',null,false,'Daftar Kosakata'),
('鶏','とり','ayam',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1800042,null,true,18,'温泉に入りたいです','とり○',null,false,'Daftar Kosakata'),
('でも','でも','tetapi',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1800043,null,true,18,'温泉に入りたいです','で↓も',null,false,'Daftar Kosakata')
on conflict (source_book,source_order,term) do update set reading=excluded.reading,meaning_id=excluded.meaning_id,lexical_class=excluded.lexical_class,subgroup=excluded.subgroup,lesson_number=excluded.lesson_number,lesson_title=excluded.lesson_title,accent=excluded.accent,verb_group=excluded.verb_group,is_verified=true;
