-- Historical migration marker restored from Supabase migration history.
-- Version: 20260914032532
-- Name: class_role_permissions_and_workflow
-- Production already records this migration as applied.
