INSERT INTO public.vocabulary_source_items (id,vocabulary_id,term,reading,meaning_id,lexical_class,subgroup,source_book,source_order,level_hint,is_verified,created_at,lesson_number,lesson_title,accent,verb_group,is_reference,is_expression,source_section) VALUES
(gen_random_uuid(),NULL,'曜日','ようび','hari',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',100001,NULL,TRUE,now(),10,NULL,'ようび○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'時間','じかん','waktu; jam',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',100002,NULL,TRUE,now(),10,NULL,'じかん○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'費用','ひよう','biaya',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',100003,NULL,TRUE,now(),10,NULL,'ひ↓よう',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'毎月','まいつき','setiap bulan',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',100004,NULL,TRUE,now(),10,NULL,'まいつき○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'第～（第3木曜日）','だい～','ke~ (menyatakan urutan; contoh: hari Kamis ke-3 setiap bulan)',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',100005,NULL,TRUE,now(),10,NULL,'だい～（だいさんもくよ↓うび）',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'公民館','こうみんかん','balai kegiatan publik',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',100006,NULL,TRUE,now(),10,NULL,'こうみ↓んかん',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'問い合わせ','といあわせ','informasi lebih lanjut',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',100007,NULL,TRUE,now(),10,NULL,'といあわせ○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'スタート（10月スタート）','スタート','mulai (mulai bulan Oktober)',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',100008,NULL,TRUE,now(),10,NULL,'スタ↓ート',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'旬','しゅん','masakan; makanan musiman',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',100009,NULL,TRUE,now(),10,NULL,'しゅん○／しゅ↓ん',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'味わう','あじわう','merasakan; mencicipi',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',100010,NULL,TRUE,now(),10,NULL,'あじわ↓う',1,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'全～回（全4回）','ぜん～かい','total sebanyak ～ kali (total sebanyak 4 kali)',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',100011,NULL,TRUE,now(),10,NULL,'ぜ↓ん～か↓い',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'調理室','ちょうりしつ','dapur',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',100012,NULL,TRUE,now(),10,NULL,'ちょうり↓しつ',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'各','かく','setiap; masing-masing',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',100013,NULL,TRUE,now(),10,NULL,'か↓く',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'先着','せんちゃく','pendaftaran berdasarkan urutan; yang lebih dulu mendapat tempat',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',100014,NULL,TRUE,now(),10,NULL,'せんちゃく○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'書道','しょどう','kaligrafi Jepang',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',100015,NULL,TRUE,now(),10,NULL,'しょ↓どう',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'日時','にちじ','tanggal, hari dan waktu',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',100016,NULL,TRUE,now(),10,NULL,'に↓ちじ',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'～代（テキスト代）','～だい','biaya～ (biaya buku)',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',100017,NULL,TRUE,now(),10,NULL,'～だい（テキストだい○）',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'外国人向け','がいこくじんむけ','bagi orang asing',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',100018,NULL,TRUE,now(),10,NULL,'がいこくじんむけ○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'体験教室','たいけんきょうしつ','kelas percobaan',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',100019,NULL,TRUE,now(),10,NULL,'たいけんきょ↓うしつ',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'各自','かくじ','setiap orang; masing-masing orang',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',100020,NULL,TRUE,now(),10,NULL,'か↓くじ',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'見学','けんがく','pengamatan; observasi',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',100021,NULL,TRUE,now(),10,NULL,'けんがく○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'申し込み','もうしこみ','pendaftaran',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',100022,NULL,TRUE,now(),10,NULL,'もうしこみ○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'お持ちください','おもちください','Silakan membawa~ . (ungkapan bentuk sopan)',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',100023,NULL,TRUE,now(),10,NULL,'おもちくださ↓い',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'参加されています','さんかされています','~ikut serta; berpartisipasi (ungkapan bentuk sopan)',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',100024,NULL,TRUE,now(),10,NULL,'さんかされていま↓す',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'いらしてください','いらしてください','Silakan datang. (ungkapan bentuk sopan)',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',100025,NULL,TRUE,now(),10,NULL,'いら↓してくださ↓い',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'かかる','かかる','dikenakan (biaya)',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',100026,NULL,TRUE,now(),10,NULL,'かか↓る',1,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'合気道','あいきどう','Aikido',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',100027,NULL,TRUE,now(),10,NULL,'あいき↓どう',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'～回完結（1回完結）','～かいかんけつ','selesai dalam ~ pertemuan (contoh: selesai dalam 1 kali pertemuan)',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',100028,NULL,TRUE,now(),10,NULL,'～かいかんけつ○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'体育室','たいいくしつ','ruang olahraga',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',100029,NULL,TRUE,now(),10,NULL,'たいいく↓しつ',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'動きやすい','うごきやすい','mudah untuk bergerak',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',100030,NULL,TRUE,now(),10,NULL,'うごきやす↓い',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'道着','どうぎ','dougi (seragam olahraga bela diri)',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',100031,NULL,TRUE,now(),10,NULL,'どうぎ↓',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'かまいません','かまいません','tidak apa-apa',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',100032,NULL,TRUE,now(),10,NULL,'かまいませ↓ん',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'必要ありません','ひつようありません','tidak perlu',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',100033,NULL,TRUE,now(),10,NULL,'ひつようありませ↓ん',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'道具','どうぐ','alat',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',100034,NULL,TRUE,now(),10,NULL,'どうぐ↓',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'参加する','さんかする','ikut serta; berpartisipasi',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',100035,NULL,TRUE,now(),10,NULL,'さんかする○',3,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'クラス','クラス','kelas; kursus',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',100036,NULL,TRUE,now(),10,NULL,'ク↓ラス',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'あとは','あとは','setelah itu',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',100037,NULL,TRUE,now(),10,NULL,'あ↓とは',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'聞く','きく','bertanya; menanyakan',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',100038,NULL,TRUE,now(),10,NULL,'きく○',1,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'まだ空いていますか？','まだあいていますか？','Apakah masih ada tempat?',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',100039,NULL,TRUE,now(),10,NULL,'ま↓だあいていま↓すか？',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'払う','はらう','membayar',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',100040,NULL,TRUE,now(),10,NULL,'はら↓う',1,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'もういっぱいです','もういっぱいです','Sudah penuh',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',100041,NULL,TRUE,now(),10,NULL,'も↓ういっぱいで↓す',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'少々お待ちください','しょうしょうおまちください','Mohon menunggu sebentar',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',100042,NULL,TRUE,now(),10,NULL,'しょ↓うしょうおまちくださ↓い',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'興味がある','きょうみがある','tertarik',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',100043,NULL,TRUE,now(),10,NULL,'きょ↓うみがあ↓る',1,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'それとも','それとも','atau',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',100044,NULL,TRUE,now(),10,NULL,'それと↓も',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'コース','コース','kursus; program',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',100045,NULL,TRUE,now(),10,NULL,'コ↓ース',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'全部','ぜんぶ','semua',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',100046,NULL,TRUE,now(),10,NULL,'ぜ↓んぶ',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'用意する','よういする','menyediakan',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',100047,NULL,TRUE,now(),10,NULL,'よ↓ういする',3,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'もっと','もっと','lebih',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',100048,NULL,TRUE,now(),10,NULL,'も↓っと',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'週','しゅう','pekan; minggu',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',100049,NULL,TRUE,now(),10,NULL,'しゅ↓う',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'何回','なんかい','berapa kali',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',100050,NULL,TRUE,now(),10,NULL,'なんか↓い／な↓んかい／',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'～回（１回）','～かい','～ kali (satu kali)',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',100051,NULL,TRUE,now(),10,NULL,'～かい（いっか↓い／いっかい○）',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'ただ','ただ','gratis',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',100052,NULL,TRUE,now(),10,NULL,'た↓だ',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'チラシ','チラシ','selebaran',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',100053,NULL,TRUE,now(),10,NULL,'チラシ○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'持って来る','もってくる','membawakan; membawa',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',100054,NULL,TRUE,now(),10,NULL,'もってく↓る',3,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'ちょっといいですか？','ちょっといいですか？','Bisa minta waktu sebentar?',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',100055,NULL,TRUE,now(),10,NULL,'ちょ↓っとい↓いですか？',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'きびしい','きびしい','tegas; ketat',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',100056,NULL,TRUE,now(),10,NULL,'きびし↓い',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'母語','ぼご','bahasa ibu',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',100057,NULL,TRUE,now(),10,NULL,'ぼ↓ご',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'どういう','どういう','apa',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',100058,NULL,TRUE,now(),10,NULL,'ど↓ういう',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'意味','いみ','arti; makna',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',100059,NULL,TRUE,now(),10,NULL,'い↓み',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'使う','つかう','menggunakan',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',100060,NULL,TRUE,now(),10,NULL,'つかう○',1,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'前に','まえに','sebelum; sebelumnya',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',100061,NULL,TRUE,now(),10,NULL,'ま↓えに／まえに○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'どんなこと','どんなこと','hal seperti apa',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',100062,NULL,TRUE,now(),10,NULL,'ど↓んなこと',NULL,FALSE,FALSE,NULL)
ON CONFLICT (source_book,source_order,term) DO UPDATE SET reading=EXCLUDED.reading,meaning_id=EXCLUDED.meaning_id,accent=EXCLUDED.accent,verb_group=EXCLUDED.verb_group,lesson_number=EXCLUDED.lesson_number,is_verified=TRUE;
