revoke execute on function public.award_referral_signup(text) from public, anon, authenticated;
grant execute on function public.award_referral_signup(text) to authenticated;
revoke execute on function public.ensure_profile_defaults() from public, anon, authenticated;
grant execute on function public.ensure_profile_defaults() to authenticated;
revoke execute on function public.is_premium(uuid) from public, anon, authenticated;
grant execute on function public.is_premium(uuid) to authenticated;
revoke execute on function public.redeem_referral_points(integer) from public, anon, authenticated;
grant execute on function public.redeem_referral_points(integer) to authenticated;
revoke execute on function public.submit_quiz_attempt(uuid, public.jlpt_level, public.content_skill, jsonb, integer) from public, anon, authenticated;
grant execute on function public.submit_quiz_attempt(uuid, public.jlpt_level, public.content_skill, jsonb, integer) to authenticated;

create index if not exists idx_kanji_relations_related on public.kanji_relations(related_kanji_id);
create index if not exists idx_questions_grammar on public.questions(grammar_id);
create index if not exists idx_questions_kanji on public.questions(kanji_id);
create index if not exists idx_questions_vocabulary on public.questions(vocabulary_id);
create index if not exists idx_questions_passage on public.questions(passage_id);
create index if not exists idx_questions_listening on public.questions(listening_id);
create index if not exists idx_quiz_answers_attempt on public.quiz_answers(attempt_id);
create index if not exists idx_quiz_answers_question on public.quiz_answers(question_id);
create index if not exists idx_quiz_attempts_quiz on public.quiz_attempts(quiz_id);
create index if not exists idx_quiz_questions_question on public.quiz_questions(question_id);
create index if not exists idx_referral_events_referred on public.referral_events(referred_user_id);
create index if not exists idx_referrals_referred on public.referrals(referred_user_id);
create index if not exists idx_reward_grants_user on public.reward_grants(user_id);
drop index if exists public.questions_level_skill_idx;

update public.reading_passages set title='わたしの町の図書館', body_jp='私の町には、小さいですが、静かで使いやすい図書館があります。駅から歩いて十分ぐらいのところにあり、毎週土曜日には家族と一緒に行きます。\n\n図書館には日本語の本だけではなく、写真の本や子ども向けの本もたくさんあります。私はいつも日本語の本を一冊借ります。分からない言葉があるときは、辞書を使って意味を調べます。\n\n先週は雨が降っていたので、図書館で二時間ぐらい本を読みました。静かな場所で読むと、家で読むより集中できます。これからも毎週図書館へ行って、少しずつ日本語を勉強したいです。', body_furigana='私[わたし]の町[まち]には、小[ちい]さいですが、静[しず]かで使[つか]いやすい図書館[としょかん]があります。駅[えき]から歩[ある]いて十分[じゅっぷん]ぐらいのところにあり、毎週[まいしゅう]土曜日[どようび]には家族[かぞく]と一緒[いっしょ]に行[い]きます。\n\n図書館[としょかん]には日本語[にほんご]の本[ほん]だけではなく、写真[しゃしん]の本[ほん]や子[こ]ども向[む]けの本[ほん]もたくさんあります。私[わたし]はいつも日本語[にほんご]の本[ほん]を一冊[いっさつ]借[か]ります。分[わ]からない言葉[ことば]があるときは、辞書[じしょ]を使[つか]って意味[いみ]を調[しら]べます。\n\n先週[せんしゅう]は雨[あめ]が降[ふ]っていたので、図書館[としょかん]で二時間[にじかん]ぐらい本[ほん]を読[よ]みました。静[しず]かな場所[ばしょ]で読[よ]むと、家[いえ]で読[よ]むより集中[しゅうちゅう]できます。これからも毎週[まいしゅう]図書館[としょかん]へ行[い]って、少[すこ]しずつ日本語[にほんご]を勉強[べんきょう]したいです。', translation_id='Di kota saya ada perpustakaan kecil, tetapi tenang dan mudah digunakan. Saya pergi ke sana bersama keluarga setiap Sabtu. Perpustakaan memiliki banyak buku bahasa Jepang, buku foto, dan buku untuk anak-anak. Minggu lalu saya membaca selama sekitar dua jam. Membaca di tempat yang tenang membuat saya lebih mudah berkonsentrasi. Saya ingin terus belajar bahasa Jepang sedikit demi sedikit setiap minggu.', estimated_minutes=4 where id='7d6b3a42-17c0-4b0d-8253-ec4af328c7ef';

update public.reading_passages set title='アルバイトを始めて分かったこと', body_jp='大学に入ってから、私は駅の近くのパン屋でアルバイトを始めました。最初は仕事を覚えることが大変でした。特に、お客さんの注文を聞きながら、別の仕事をしなければならないときは、よく間違えてしまいました。\n\n店長は、急いでいるときほど一つずつ確認することが大切だと教えてくれました。それから私は、注文を聞いたらすぐにメモをして、商品を渡す前にもう一度確認するようにしました。その結果、間違いが少なくなりました。\n\nアルバイトを始めて三か月になります。仕事はまだ忙しいですが、お客さんにありがとうと言ってもらえると、頑張ってよかったと思います。仕事を通して、時間を守ることや相手の話をよく聞くことの大切さも学びました。', body_furigana='大学[だいがく]に入[はい]ってから、私[わたし]は駅[えき]の近[ちか]くのパン屋[や]でアルバイトを始[はじ]めました。最初[さいしょ]は仕事[しごと]を覚[おぼ]えることが大変[たいへん]でした。特[とく]に、お客[きゃく]さんの注文[ちゅうもん]を聞[き]きながら、別[べつ]の仕事[しごと]をしなければならないときは、よく間違[まちが]えてしまいました。\n\n店長[てんちょう]は、急[いそ]いでいるときほど一[ひと]つずつ確認[かくにん]することが大切[たいせつ]だと教[おし]えてくれました。それから私[わたし]は、注文[ちゅうもん]を聞[き]いたらすぐにメモをして、商品[しょうひん]を渡[わた]す前[まえ]にもう一度[いちど]確認[かくにん]するようにしました。その結果[けっか]、間違[まちが]いが少[すく]なくなりました。\n\nアルバイトを始[はじ]めて三[さん]か月[げつ]になります。仕事[しごと]はまだ忙[いそが]しいですが、お客[きゃく]さんにありがとうと言[い]ってもらえると、頑張[がんば]ってよかったと思[おも]います。仕事[しごと]を通[とお]して、時間[じかん]を守[まも]ることや相手[あいて]の話[はなし]をよく聞[き]くことの大切[たいせつ]さも学[まな]びました。', translation_id='Setelah masuk universitas, saya mulai bekerja paruh waktu di toko roti dekat stasiun. Awalnya sulit menghafal pekerjaan. Manajer mengajarkan bahwa justru ketika terburu-buru, kita harus memeriksa satu per satu. Setelah itu saya mencatat pesanan dan memeriksanya lagi sebelum menyerahkan barang. Kesalahan pun berkurang. Dari pekerjaan ini saya belajar pentingnya tepat waktu dan mendengarkan orang lain.', estimated_minutes=5 where id='3b0e1cc3-5192-4341-81e1-a15c1e3b511a';

update public.reading_passages set title='便利さと不便さについて考える', body_jp='最近は、スマートフォン一台で多くのことができるようになった。電車の時間を調べたり、店を探したり、友人に連絡したりすることも、以前より簡単になった。特に、知らない場所へ行くときには、地図の機能が非常に便利である。\n\n一方で、便利になったからこそ、以前なら覚えていたことを自分で考えなくなったと感じる人もいる。例えば、道を覚えずにいつも地図を見る習慣がつくと、スマートフォンが使えない状況で困るかもしれない。また、通知が多いと、目の前の仕事に集中しにくくなることもある。\n\n大切なのは、便利な道具を使わないことではない。目的に合わせて使い方を選び、自分で考える時間も残しておくことだろう。便利さは、それだけで生活を良くするものではなく、使う人の判断によって価値が変わるものだと思う。', body_furigana='最近[さいきん]は、スマートフォン一台[いったい]で多[おお]くのことができるようになった。電車[でんしゃ]の時間[じかん]を調[しら]べたり、店[みせ]を探[さが]したり、友人[ゆうじん]に連絡[れんらく]したりすることも、以前[いぜん]より簡単[かんたん]になった。特[とく]に、知[し]らない場所[ばしょ]へ行[い]くときには、地図[ちず]の機能[きのう]が非常[ひじょう]に便利[べんり]である。\n\n一方[いっぽう]で、便利[べんり]になったからこそ、以前[いぜん]なら覚[おぼ]えていたことを自分[じぶん]で考[かんが]えなくなったと感[かん]じる人[ひと]もいる。例[たと]えば、道[みち]を覚[おぼ]えずにいつも地図[ちず]を見[み]る習慣[しゅうかん]がつくと、スマートフォンが使[つか]えない状況[じょうきょう]で困[こま]るかもしれない。また、通知[つうち]が多[おお]いと、目[め]の前[まえ]の仕事[しごと]に集中[しゅうちゅう]しにくくなることもある。\n\n大切[たいせつ]なのは、便利[べんり]な道具[どうぐ]を使[つか]わないことではない。目的[もくてき]に合[あ]わせて使[つか]い方[かた]を選[えら]び、自分[じぶん]で考[かんが]える時間[じかん]も残[のこ]しておくことだろう。便利[べんり]さは、それだけで生活[せいかつ]を良[よ]くするものではなく、使[つか]う人[ひと]の判断[はんだん]によって価値[かち]が変[か]わるものだと思[おも]う。', translation_id='Saat ini satu ponsel dapat melakukan banyak hal. Di sisi lain, karena semakin praktis, sebagian orang merasa mereka tidak lagi memikirkan sendiri hal-hal yang dulu mereka ingat. Yang penting bukan tidak menggunakan alat yang praktis, melainkan memilih cara menggunakannya sesuai tujuan sambil tetap menyisakan waktu untuk berpikir sendiri.', estimated_minutes=6 where id='7eed0ebc-086d-4607-a42c-894e9179faf4';

update public.reading_passages set title='働き方を変えるときに必要な視点', body_jp='働き方に対する考え方は、ここ数年で大きく変化した。会社に毎日通勤することだけが仕事の形ではなくなり、自宅や共有スペースから働く人も珍しくない。こうした変化には、通勤時間を減らせるという利点がある一方、仕事と生活の境界が曖昧になりやすいという問題もある。\n\n在宅勤務を導入した企業の中には、社員の自由度が高まったことで満足度が上がったところもある。しかし、制度を導入するだけで成果が上がるとは限らない。業務の目的が共有されていなかったり、連絡の方法が複雑だったりすると、かえって負担が増える可能性がある。\n\nしたがって、働く場所を選べるかどうかだけではなく、どのような仕事を、どのような基準で評価するのかを明確にする必要がある。制度の新しさよりも、働く人が自分の役割を理解し、必要なときに周囲と協力できる環境を整えることが重要なのではないだろうか。', body_furigana='働[はたら]き方[かた]に対[たい]する考[かんが]え方[かた]は、ここ数年[すうねん]で大[おお]きく変化[へんか]した。会社[かいしゃ]に毎日[まいにち]通勤[つうきん]することだけが仕事[しごと]の形[かたち]ではなくなり、自宅[じたく]や共有[きょうゆう]スペースから働[はたら]く人[ひと]も珍[めずら]しくない。こうした変化[へんか]には、通勤[つうきん]時間[じかん]を減[へ]らせるという利点[りてん]がある一方[いっぽう]、仕事[しごと]と生活[せいかつ]の境界[きょうかい]が曖昧[あいまい]になりやすいという問題[もんだい]もある。\n\n在宅[ざいたく]勤務[きんむ]を導入[どうにゅう]した企業[きぎょう]の中[なか]には、社員[しゃいん]の自由度[じゆうど]が高[たか]まったことで満足度[まんぞくど]が上[あ]がったところもある。しかし、制度[せいど]を導入[どうにゅう]するだけで成果[せいか]が上[あ]がるとは限[かぎ]らない。業務[ぎょうむ]の目的[もくてき]が共有[きょうゆう]されていなかったり、連絡[れんらく]の方法[ほうほう]が複雑[ふくざつ]だったりすると、かえって負担[ふたん]が増[ふ]える可能性[かのうせい]がある。\n\nしたがって、働[はたら]く場所[ばしょ]を選[えら]べるかどうかだけではなく、どのような仕事[しごと]を、どのような基準[きじゅん]で評価[ひょうか]するのかを明確[めいかく]にする必要[ひつよう]がある。制度[せいど]の新[あたら]しさよりも、働[はたら]く人[ひと]が自分[じぶん]の役割[やくわり]を理解[りかい]し、必要[ひつよう]なときに周囲[しゅうい]と協力[きょうりょく]できる環境[かんきょう]を整[ととの]えることが重要[じゅうよう]なのではないだろうか。', translation_id='Cara berpikir tentang bekerja berubah besar dalam beberapa tahun terakhir. Bekerja dari rumah memberi keuntungan berupa berkurangnya waktu perjalanan, tetapi batas antara pekerjaan dan kehidupan dapat menjadi kabur. Memperkenalkan sistem kerja jarak jauh saja tidak menjamin hasil meningkat. Yang lebih penting adalah memperjelas tujuan, cara evaluasi, dan menciptakan lingkungan tempat pekerja memahami perannya serta dapat bekerja sama ketika diperlukan.', estimated_minutes=7 where id='7e83848a-35cd-45af-b003-445754a1ebe6';

update public.reading_passages set title='知識を持つことと使うこと', body_jp='知識を増やすことは、学習において分かりやすい目標である。本を読んだり講義を聞いたりすれば、新しい情報を得ることができる。しかし、知っていることが多いからといって、必ずしも問題をうまく解決できるとは限らない。\n\n例えば、仕事の方法について多くの知識を持っていても、実際の場面では予想外の事情が起こる。相手の立場が自分の想定と違えば、教科書どおりの方法が適切ではない場合もある。そのため、知識を実際の状況に合わせて使い、必要なら修正する能力が求められる。\n\nもちろん、基礎的な知識がなければ判断すること自体が難しい。だからこそ、知識を覚えることと、知識を使って考えることを別々の活動として扱うべきではない。学んだ内容を実際の問題に当てはめ、うまくいかなかった理由を振り返る。その繰り返しによって、知識は単なる情報ではなく、自分で判断するための道具になっていくのである。', body_furigana='知識[ちしき]を増[ふ]やすことは、学習[がくしゅう]において分[わ]かりやすい目標[もくひょう]である。本[ほん]を読[よ]んだり講義[こうぎ]を聞[き]いたりすれば、新[あたら]しい情報[じょうほう]を得[え]ることができる。しかし、知[し]っていることが多[おお]いからといって、必[かなら]ずしも問題[もんだい]をうまく解決[かいけつ]できるとは限[かぎ]らない。\n\n例[たと]えば、仕事[しごと]の方法[ほうほう]について多[おお]くの知識[ちしき]を持[も]っていても、実際[じっさい]の場面[ばめん]では予想外[よそうがい]の事情[じじょう]が起[お]こる。相手[あいて]の立場[たちば]が自分[じぶん]の想定[そうてい]と違[ちが]えば、教科書[きょうかしょ]どおりの方法[ほうほう]が適切[てきせつ]ではない場合[ばあい]もある。そのため、知識[ちしき]を実際[じっさい]の状況[じょうきょう]に合[あ]わせて使[つか]い、必要[ひつよう]なら修正[しゅうせい]する能力[のうりょく]が求[もと]められる。\n\nもちろん、基礎[きそ]的[てき]な知識[ちしき]がなければ判断[はんだん]すること自体[じたい]が難[むずか]しい。だからこそ、知識[ちしき]を覚[おぼ]えることと、知識[ちしき]を使[つか]って考[かんが]えることを別々[べつべつ]の活動[かつどう]として扱[あつか]うべきではない。学[まな]んだ内容[ないよう]を実際[じっさい]の問題[もんだい]に当[あ]てはめ、うまくいかなかった理由[りゆう]を振[ふ]り返[かえ]る。その繰[く]り返[かえ]しによって、知識[ちしき]は単[たん]なる情報[じょうほう]ではなく、自分[じぶん]で判断[はんだん]するための道具[どうぐ]になっていくのである。', translation_id='Menambah pengetahuan adalah tujuan belajar yang mudah dipahami. Namun, banyak pengetahuan tidak selalu berarti seseorang dapat memecahkan masalah dengan baik. Dalam situasi nyata, keadaan tak terduga dapat muncul dan metode dari buku belum tentu sesuai. Karena itu, pengetahuan perlu diterapkan pada situasi nyata, lalu diperbaiki jika perlu. Dengan mengulang proses belajar, penerapan, dan refleksi, pengetahuan menjadi alat untuk mengambil keputusan sendiri.', estimated_minutes=8 where id='c3f62150-6856-4e9e-b8a8-2368bf8c1594';

insert into public.questions (level, skill, question_type, prompt, choices, correct_index, explanation_id, passage_id, source, is_published)
select x.level::public.jlpt_level, 'reading'::public.content_skill, 'multiple_choice', x.prompt, x.choices::jsonb, x.correct_index, x.explanation, x.passage_id::uuid, 'eno_original', true
from (values
('N5','Apa yang dilakukan penulis setiap Sabtu?','["Pergi ke perpustakaan","Pergi ke rumah sakit","Bekerja di toko","Belajar di stasiun"]',0,'Penulis pergi ke perpustakaan bersama keluarga setiap Sabtu.','7d6b3a42-17c0-4b0d-8253-ec4af328c7ef'),
('N5','Mengapa penulis suka membaca di perpustakaan?','["Karena ramai","Karena lebih mudah berkonsentrasi","Karena tidak ada buku","Karena dekat rumah"]',1,'Tempat yang tenang membuat penulis lebih mudah berkonsentrasi.','7d6b3a42-17c0-4b0d-8253-ec4af328c7ef'),
('N5','Berapa lama penulis membaca di perpustakaan minggu lalu?','["Satu jam","Dua jam","Tiga jam","Sepuluh menit"]',1,'Penulis membaca selama sekitar dua jam.','7d6b3a42-17c0-4b0d-8253-ec4af328c7ef'),
('N5','Apa tujuan penulis ke depan?','["Berhenti belajar Jepang","Pergi ke perpustakaan setiap minggu","Membuka perpustakaan","Membeli rumah baru"]',1,'Penulis ingin terus pergi ke perpustakaan dan belajar sedikit demi sedikit.','7d6b3a42-17c0-4b0d-8253-ec4af328c7ef'),
('N4','Apa yang dilakukan penulis setelah mendengar pesanan?','["Langsung pulang","Mencatatnya","Mengabaikannya","Mengganti manajer"]',1,'Penulis mulai mencatat pesanan.','3b0e1cc3-5192-4341-81e1-a15c1e3b511a'),
('N4','Apa nasihat manajer?','["Bekerja lebih cepat tanpa memeriksa","Memeriksa satu per satu saat terburu-buru","Tidak perlu mencatat","Bekerja hanya tiga bulan"]',1,'Manajer mengajarkan pentingnya memeriksa satu per satu ketika terburu-buru.','3b0e1cc3-5192-4341-81e1-a15c1e3b511a'),
('N4','Apa hasil perubahan cara kerja penulis?','["Kesalahan berkurang","Toko ditutup","Pesanan bertambah dua kali lipat","Penulis berhenti bekerja"]',0,'Setelah mencatat dan memeriksa ulang, kesalahan berkurang.','3b0e1cc3-5192-4341-81e1-a15c1e3b511a'),
('N4','Apa yang dipelajari penulis dari pekerjaan?','["Cara memasak saja","Pentingnya tepat waktu dan mendengarkan","Cara membuka universitas","Cara membeli rumah"]',1,'Penulis belajar pentingnya menjaga waktu dan mendengarkan orang lain.','3b0e1cc3-5192-4341-81e1-a15c1e3b511a'),
('N3','Apa keuntungan smartphone yang disebutkan?','["Tidak perlu bekerja","Mudah mencari waktu kereta dan tempat","Membuat semua orang fokus","Menghilangkan semua masalah"]',1,'Teks memberi contoh jadwal kereta, pencarian toko, dan peta.','7eed0ebc-086d-4607-a42c-894e9179faf4'),
('N3','Apa masalah yang mungkin muncul jika selalu memakai peta?','["Sulit mengingat jalan sendiri","Kereta selalu terlambat","Toko menjadi mahal","Tidak bisa mengirim pesan"]',0,'Kebiasaan selalu melihat peta dapat membuat orang kesulitan saat ponsel tidak dapat digunakan.','7eed0ebc-086d-4607-a42c-894e9179faf4'),
('N3','Menurut teks, apa yang penting?','["Tidak menggunakan teknologi","Menggunakan alat sesuai tujuan dan tetap berpikir sendiri","Membeli ponsel baru","Menghindari semua pemberitahuan"]',1,'Penulis menekankan penggunaan sesuai tujuan sambil mempertahankan waktu untuk berpikir.','7eed0ebc-086d-4607-a42c-894e9179faf4'),
('N3','Apa yang menentukan nilai sebuah kemudahan?','["Harga ponsel","Penilaian orang yang menggunakannya","Jumlah aplikasi","Kecepatan internet"]',1,'Nilai kemudahan berubah berdasarkan penilaian pengguna.','7eed0ebc-086d-4607-a42c-894e9179faf4'),
('N2','Apa salah satu keuntungan kerja dari rumah?','["Menghapus semua pekerjaan","Mengurangi waktu perjalanan","Tidak perlu bekerja sama","Menghilangkan evaluasi"]',1,'Berkurangnya waktu perjalanan adalah salah satu keuntungan.','7e83848a-35cd-45af-b003-445754a1ebe6'),
('N2','Mengapa sistem baru belum tentu meningkatkan hasil?','["Karena rumah terlalu kecil","Tujuan pekerjaan atau komunikasi bisa tidak jelas","Karena semua orang menolak","Karena tidak ada teknologi"]',1,'Tujuan yang tidak dibagi atau komunikasi yang rumit dapat meningkatkan beban.','7e83848a-35cd-45af-b003-445754a1ebe6'),
('N2','Apa yang perlu diperjelas selain tempat bekerja?','["Warna kantor","Pekerjaan dan kriteria evaluasinya","Harga makanan","Jadwal liburan"]',1,'Teks menekankan kejelasan pekerjaan dan standar evaluasi.','7e83848a-35cd-45af-b003-445754a1ebe6'),
('N2','Apa lingkungan kerja yang dianggap penting?','["Lingkungan tanpa komunikasi","Lingkungan yang membuat peran jelas dan memungkinkan kerja sama","Lingkungan tanpa aturan","Lingkungan yang selalu baru"]',1,'Pekerja perlu memahami perannya dan dapat bekerja sama saat diperlukan.','7e83848a-35cd-45af-b003-445754a1ebe6'),
('N1','Apa yang tidak selalu benar menurut penulis?','["Pengetahuan bisa dipelajari","Banyak pengetahuan selalu membuat masalah mudah diselesaikan","Situasi nyata dapat berbeda","Pengetahuan perlu digunakan"]',1,'Banyak pengetahuan tidak otomatis membuat pemecahan masalah berhasil.','c3f62150-6856-4e9e-b8a8-2368bf8c1594'),
('N1','Mengapa metode buku bisa tidak tepat?','["Buku tidak memiliki kata","Keadaan nyata dan posisi orang lain dapat berbeda dari perkiraan","Semua pekerjaan sama","Pengetahuan tidak berguna"]',1,'Situasi nyata dapat berbeda sehingga metode perlu disesuaikan.','c3f62150-6856-4e9e-b8a8-2368bf8c1594'),
('N1','Kemampuan apa yang dibutuhkan selain memiliki pengetahuan?','["Menghafal tanpa berpikir","Menyesuaikan dan memperbaiki penggunaan pengetahuan","Menghindari masalah","Membaca lebih cepat saja"]',1,'Penulis menekankan kemampuan menggunakan pengetahuan sesuai keadaan dan memperbaikinya.','c3f62150-6856-4e9e-b8a8-2368bf8c1594'),
('N1','Bagaimana pengetahuan menjadi alat untuk mengambil keputusan?','["Dengan hanya menghafalnya","Dengan menerapkan pada masalah nyata dan merefleksikan hasilnya","Dengan menghindari pengalaman","Dengan membaca satu buku"]',1,'Penerapan dan refleksi berulang membuat pengetahuan menjadi alat mengambil keputusan.','c3f62150-6856-4e9e-b8a8-2368bf8c1594')
) as x(level,prompt,choices,correct_index,explanation,passage_id)
where exists (select 1 from public.reading_passages rp where rp.id=x.passage_id::uuid)
  and not exists (select 1 from public.questions q where q.passage_id=x.passage_id::uuid and q.prompt=x.prompt);
