INSERT INTO public.vocabulary_source_items (id,vocabulary_id,term,reading,meaning_id,lexical_class,subgroup,source_book,source_order,level_hint,is_verified,created_at,lesson_number,lesson_title,accent,verb_group,is_reference,is_expression,source_section) VALUES
(gen_random_uuid(),NULL,'バーベキュー','バーベキュー','barbeku; BBQ',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110001,NULL,TRUE,now(),11,NULL,'バーベ↓キュー',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'肉','にく','daging',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110002,NULL,TRUE,now(),11,NULL,'にく↓',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'牛肉','ぎゅうにく','daging sapi',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110003,NULL,TRUE,now(),11,NULL,'ぎゅうにく○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'豚肉','ぶたにく','daging babi',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110004,NULL,TRUE,now(),11,NULL,'ぶたにく○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'鶏肉','とりにく','daging ayam',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110005,NULL,TRUE,now(),11,NULL,'とりにく○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'ソーセージ','ソーセージ','sosis',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110006,NULL,TRUE,now(),11,NULL,'ソーセ↓ージ',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'シーフード','シーフード','makanan laut; seafood',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110007,NULL,TRUE,now(),11,NULL,'シーフ↓ード',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'魚','さかな','ikan',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110008,NULL,TRUE,now(),11,NULL,'さかな○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'エビ','エビ','udang',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110009,NULL,TRUE,now(),11,NULL,'エビ○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'イカ','イカ','cumi-cumi',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110010,NULL,TRUE,now(),11,NULL,'イカ○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'ホタテ','ホタテ','kerang; simping',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110011,NULL,TRUE,now(),11,NULL,'ホタテ○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'りんご','りんご','apel',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110012,NULL,TRUE,now(),11,NULL,'りんご○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'バナナ','バナナ','pisang',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110013,NULL,TRUE,now(),11,NULL,'バ↓ナナ',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'焼きそば','やきそば','yakisoba (mie goreng)',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110014,NULL,TRUE,now(),11,NULL,'やきそば○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'おにぎり','おにぎり','onigiri (rice ball; nasi kepal)',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110015,NULL,TRUE,now(),11,NULL,'おに↓ぎり',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'焼肉','やきにく','yakiniku (daging panggang khas Jepang)',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110016,NULL,TRUE,now(),11,NULL,'やきにく○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'たれ','たれ','tare (saus celup; saus cocol)',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110017,NULL,TRUE,now(),11,NULL,'たれ↓',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'ソース','ソース','saus',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110018,NULL,TRUE,now(),11,NULL,'ソ↓ース',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'お菓子','おかし','kue',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110019,NULL,TRUE,now(),11,NULL,'おか↓し',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'ソフトドリンク','ソフトドリンク','soft drink; minuman ringan (tanpa alkohol)',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110020,NULL,TRUE,now(),11,NULL,'ソフトドリ↓ンク',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'お茶','おちゃ','teh; teh khas Jepang',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110021,NULL,TRUE,now(),11,NULL,'おちゃ○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'ジュース','ジュース','jus',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110022,NULL,TRUE,now(),11,NULL,'ジュ↓ース',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'お酒','おさけ','alkohol',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110023,NULL,TRUE,now(),11,NULL,'おさけ○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'ビール','ビール','bir',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110024,NULL,TRUE,now(),11,NULL,'ビ↓ール',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'ワイン','ワイン','anggur',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110025,NULL,TRUE,now(),11,NULL,'ワ↓イン',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'日本酒','にほんしゅ','sake (minuman beralkohol khas Jepang hasil fermentasi beras)',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110026,NULL,TRUE,now(),11,NULL,'にほんしゅ○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'焼酎','しょうちゅう','shochu (minuman beralkohol khas Jepang yang dibuat dengan proses penyulingan)',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110027,NULL,TRUE,now(),11,NULL,'しょうちゅ↓う',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'コップ','コップ','cangkir',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110028,NULL,TRUE,now(),11,NULL,'コップ○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'お皿','おさら','piring',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110029,NULL,TRUE,now(),11,NULL,'おさら○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'わりばし','わりばし','sumpit kayu sekali pakai',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110030,NULL,TRUE,now(),11,NULL,'わりばし○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'ごみ袋','ごみぶくろ','kantong sampah',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110031,NULL,TRUE,now(),11,NULL,'ごみぶ↓くろ',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'準備','じゅんび','persiapan',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110032,NULL,TRUE,now(),11,NULL,'じゅ↓んび',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'持って行く','もっていく','membawa; pergi dengan membawa~',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110033,NULL,TRUE,now(),11,NULL,'もっていく○／も↓っていく',1,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'手伝う','てつだう','membantu',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110034,NULL,TRUE,now(),11,NULL,'てつだ↓う',1,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'飲み物','のみもの','minuman',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110035,NULL,TRUE,now(),11,NULL,'のみも↓の／のみ↓もの',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'バーベキュー場','バーベキューじょう','area pesta barbeku',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110036,NULL,TRUE,now(),11,NULL,'バーベキューじょう○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'デザート','デザート','makanan pencuci mulut',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110037,NULL,TRUE,now(),11,NULL,'デザ↓ート',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'焼く','やく','bakar; panggang',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110038,NULL,TRUE,now(),11,NULL,'やく○',1,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'からあげ','からあげ','karaage (ayam goreng khas Jepang)',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110039,NULL,TRUE,now(),11,NULL,'からあげ○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'焼き鳥','やきとり','yakitori (sate ayam khas Jepang)',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110040,NULL,TRUE,now(),11,NULL,'やきとり○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'塩','しお','garam',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110041,NULL,TRUE,now(),11,NULL,'しお↓',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'紅茶','こうちゃ','teh hitam',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110042,NULL,TRUE,now(),11,NULL,'こうちゃ○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'ウーロン茶','ウーロンちゃ','teh oolong',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110043,NULL,TRUE,now(),11,NULL,'ウーロ↓ンちゃ',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'チョコレートケーキ','チョコレートケーキ','kue cokelat',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110044,NULL,TRUE,now(),11,NULL,'チョコレートケ↓ーキ',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'チーズケーキ','チーズケーキ','kue keju',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110045,NULL,TRUE,now(),11,NULL,'チーズケ↓ーキ',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'どっち','どっち','yang mana (kata tanya bentuk informal untuk memilih antara 2 pilihan)',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110046,NULL,TRUE,now(),11,NULL,'ど↓っち',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'どれ','どれ','yang mana ( kata tanya untuk memilih antara 3 pilihan atau lebih)',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110047,NULL,TRUE,now(),11,NULL,'ど↓れ',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'売る','うる','menjual',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110048,NULL,TRUE,now(),11,NULL,'うる○',1,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'両方','りょうほう','keduanya',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110049,NULL,TRUE,now(),11,NULL,'りょうほ↓う／りょうほう○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'アレルギー','アレルギー','alergi',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110050,NULL,TRUE,now(),11,NULL,'アレ↓ルギー',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'カニ','カニ','kepiting',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110051,NULL,TRUE,now(),11,NULL,'カニ○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'卵','たまご','telur',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110052,NULL,TRUE,now(),11,NULL,'たま↓ご',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'ピーナッツ','ピーナッツ','kacang-kacangan',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110053,NULL,TRUE,now(),11,NULL,'ピ↓ーナッツ',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'落花生','らっかせい','kacang tanah',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110054,NULL,TRUE,now(),11,NULL,'らっか↓せい',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'そば粉','そばこ','tepung soba',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110055,NULL,TRUE,now(),11,NULL,'そばこ○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'小麦','こむぎ','gandum',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110056,NULL,TRUE,now(),11,NULL,'こむぎ○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'小麦粉','こむぎこ','tepung gandum; tepung terigu',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110057,NULL,TRUE,now(),11,NULL,'こむぎこ○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'乳製品','にゅうせいひん','produk susu',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110058,NULL,TRUE,now(),11,NULL,'にゅうせ↓いひん',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'牛乳','ぎゅうにゅう','susu',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110059,NULL,TRUE,now(),11,NULL,'ぎゅうにゅう○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'バター','バター','mentega',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110060,NULL,TRUE,now(),11,NULL,'バ↓ター',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'チーズ','チーズ','keju',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110061,NULL,TRUE,now(),11,NULL,'チ↓ーズ',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'ヨーグルト','ヨーグルト','yoghurt',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110062,NULL,TRUE,now(),11,NULL,'ヨーグ↓ルト',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'材料','ざいりょう','bahan',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110063,NULL,TRUE,now(),11,NULL,'ざいりょ↓う',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'ハラル','ハラル','halal (bahan makanan dan masakan yang boleh dikonsumsi oleh orang muslim)',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110064,NULL,TRUE,now(),11,NULL,'ハ↓ラル',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'消費期限','しょうひきげん','tanggal kedaluwarsa',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110065,NULL,TRUE,now(),11,NULL,'しょうひき↓げん',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'ピザ','ピザ','piza',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110066,NULL,TRUE,now(),11,NULL,'ピ↓ザ',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'入っている','はいっている','mengandung',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110067,NULL,TRUE,now(),11,NULL,'は↓いっている',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'よかったら','よかったら','kalau (Anda) mau',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110068,NULL,TRUE,now(),11,NULL,'よ↓かったら',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'もつ','もつ','tahan, awet',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110069,NULL,TRUE,now(),11,NULL,'も↓つ',1,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'今日中に','きょうじゅうに','hari ini',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110070,NULL,TRUE,now(),11,NULL,'きょうじゅうに○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'コーナー','コーナー','bagian; pojok',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110071,NULL,TRUE,now(),11,NULL,'コ↓ーナー',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'商品','しょうひん','produk',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110072,NULL,TRUE,now(),11,NULL,'しょ↓うひん',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'すべて','すべて','semua',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110073,NULL,TRUE,now(),11,NULL,'す↓べて',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'レトルト','レトルト','makanan siap santap dalam kemasan (dapat disantap setelah dipanaskan atau dimasak di dalam air mendidih)',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110074,NULL,TRUE,now(),11,NULL,'レトルト○／レト↓ルト',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'乳成分','にゅうせいぶん','kandungan susu',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110075,NULL,TRUE,now(),11,NULL,'にゅうせ↓いぶん',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'大豆','だいず','kedelai',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110076,NULL,TRUE,now(),11,NULL,'だいず○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'名称','めいしょう','nama',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110077,NULL,TRUE,now(),11,NULL,'めいしょう○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'原材料名','げんざいりょうめい','bahan baku',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110078,NULL,TRUE,now(),11,NULL,'げんざいりょ↓うめい',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'殺菌方法','さっきんほうほう','cara sterilisasi',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110079,NULL,TRUE,now(),11,NULL,'さっきんほ↓うほう',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'内容量','ないようりょう','berat bersih',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110080,NULL,TRUE,now(),11,NULL,'ないよ↓うりょう',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'賞味期限','しょうみきげん','tanggal layak konsumsi',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110081,NULL,TRUE,now(),11,NULL,'しょうみき↓げん',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'保存方法','ほぞんほうほう','cara menyimpan',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110082,NULL,TRUE,now(),11,NULL,'ほぞんほ↓うほう',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'販売者','はんばいしゃ','penjual',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110083,NULL,TRUE,now(),11,NULL,'はんば↓いしゃ',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'本品','ほんぴん','produk ini',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110084,NULL,TRUE,now(),11,NULL,'ほ↓んぴん',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'含まれる','ふくまれる','terkandung',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110085,NULL,TRUE,now(),11,NULL,'ふくまれ↓る',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'アレルギー物質','アレルギーぶっしつ','alergen (bahan penyebab alergi)',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110086,NULL,TRUE,now(),11,NULL,'アレルギーぶ↓っしつ',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'エビピラフ','エビピラフ','pilaf udang (hidangan dengan tumisan udang)',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110087,NULL,TRUE,now(),11,NULL,'エビピ↓ラフ',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'製造者','せいぞうしゃ','pembuat; produsen',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110088,NULL,TRUE,now(),11,NULL,'せいぞ↓うしゃ',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'チョコレート','チョコレート','cokelat',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110089,NULL,TRUE,now(),11,NULL,'チョコレ↓ート',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'～品目（27品目）','～ひんもく','~bahan (contoh : 27 bahan)',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',110090,NULL,TRUE,now(),11,NULL,'～ひ↓んもく （に↓じゅう△ななひ↓んもく）',NULL,FALSE,FALSE,NULL)
ON CONFLICT (source_book,source_order,term) DO UPDATE SET reading=EXCLUDED.reading,meaning_id=EXCLUDED.meaning_id,accent=EXCLUDED.accent,verb_group=EXCLUDED.verb_group,lesson_number=EXCLUDED.lesson_number,is_verified=TRUE;
