INSERT INTO public.vocabulary_source_items (id,vocabulary_id,term,reading,meaning_id,lexical_class,subgroup,source_book,source_order,level_hint,is_verified,created_at,lesson_number,lesson_title,accent,verb_group,is_reference,is_expression,source_section) VALUES
(gen_random_uuid(),NULL,'どんな','どんな','bagaimana',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',50001,NULL,TRUE,now(),5,NULL,'ど↓んな',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'町','まち','kota',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',50002,NULL,TRUE,now(),5,NULL,'まち↓',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'便利（な）','べんり','praktis',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',50003,NULL,TRUE,now(),5,NULL,'べ↓んり（な）',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'不便（な）','ふべん','tidak praktis',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',50004,NULL,TRUE,now(),5,NULL,'ふ↓べん（な）',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'にぎやか（な）','にぎやか','ramai',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',50005,NULL,TRUE,now(),5,NULL,'にぎ↓やか（な）',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'緑','みどり','pepohonan; tanaman hijau',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',50006,NULL,TRUE,now(),5,NULL,'み↓どり',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'多い','おおい','banyak',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',50007,NULL,TRUE,now(),5,NULL,'お↓おい',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'少ない','すくない','sedikit',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',50008,NULL,TRUE,now(),5,NULL,'すくな↓い',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'人','ひと','orang',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',50009,NULL,TRUE,now(),5,NULL,'ひと○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'やさしい','やさしい','ramah',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',50010,NULL,TRUE,now(),5,NULL,'やさしい○／やさし↓い',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'親切（な）','しんせつ','baik hati',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',50011,NULL,TRUE,now(),5,NULL,'し↓んせつ（な）',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'冷たい','つめたい','dingin (sikap); tidak peduli',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',50012,NULL,TRUE,now(),5,NULL,'つめたい○／つめた↓い',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'田舎','いなか','desa; pedesaan',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',50013,NULL,TRUE,now(),5,NULL,'いなか○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'都会','とかい','kota',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',50014,NULL,TRUE,now(),5,NULL,'とかい○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'きれい（な）','きれい','indah',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',50015,NULL,TRUE,now(),5,NULL,'き↓れい（な）',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'確かに','たしかに','pastinya',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',50016,NULL,TRUE,now(),5,NULL,'た↓しかに',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'住みやすい','すみやすい','nyaman',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',50017,NULL,TRUE,now(),5,NULL,'すみやす↓い',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'店','みせ','toko / restoran',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',50018,NULL,TRUE,now(),5,NULL,'みせ↓',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'安い','やすい','murah',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',50019,NULL,TRUE,now(),5,NULL,'やす↓い',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'おもしろい','おもしろい','menarik',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',50020,NULL,TRUE,now(),5,NULL,'おもしろ↓い',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'遠い','とおい','jauh',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',50021,NULL,TRUE,now(),5,NULL,'とおい○／とお↓い',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'どこか','どこか','suatu tempat',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',50022,NULL,TRUE,now(),5,NULL,'ど↓こか',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'ところ','ところ','tempat',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',50023,NULL,TRUE,now(),5,NULL,'ところ↓',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'行ってみる','いってみる','mencoba pergi',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',50024,NULL,TRUE,now(),5,NULL,'いってみ↓る',2,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'場所','ばしょ','tempat',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',50025,NULL,TRUE,now(),5,NULL,'ばしょ○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'ぜひ','ぜひ','pastikan; jangan sampai tidak',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',50026,NULL,TRUE,now(),5,NULL,'ぜ↓ひ',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'おすすめ','おすすめ','direkomendasikan',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',50027,NULL,TRUE,now(),5,NULL,'おすすめ○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'知っている','しっている','mengetahui',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',50028,NULL,TRUE,now(),5,NULL,'しっている○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'知る','しる','mengetahui',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',50029,NULL,TRUE,now(),5,NULL,'しる○',1,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'休憩所','きゅうけいじょ','tempat istirahat',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',50030,NULL,TRUE,now(),5,NULL,'きゅうけいじょ○／',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'そうね……','そうね……','Hmm... (digunakan saat pembicara sedang berpikir)',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',50031,NULL,TRUE,now(),5,NULL,'そ↓うね……',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'そうだなあ','そうだなあ','Hmm..apa ya.. (digunakan saat pembicara sedang berpikir)',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',50032,NULL,TRUE,now(),5,NULL,'そ↓うだなあ',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'美しい','うつくしい','indah',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',50033,NULL,TRUE,now(),5,NULL,'うつくし↓い',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'砂浜','すなはま','pantai berpasir',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',50034,NULL,TRUE,now(),5,NULL,'すなはま○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'有名（な）','ゆうめい','terkenal',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',50035,NULL,TRUE,now(),5,NULL,'ゆうめい（な）○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'泳ぐ','およぐ','berenang',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',50036,NULL,TRUE,now(),5,NULL,'およ↓ぐ',1,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'丘','おか','bukit',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',50037,NULL,TRUE,now(),5,NULL,'おか○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'見渡す','みわたす','memandang/melihat ke sekeliling',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',50038,NULL,TRUE,now(),5,NULL,'みわたす○',1,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'夕日','ゆうひ','matahari terbenam',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',50039,NULL,TRUE,now(),5,NULL,'ゆうひ○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'タウンマップ','タウンマップ','peta kota',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',50040,NULL,TRUE,now(),5,NULL,'タウンマ↓ップ',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'名物','めいぶつ','makanan khas lokal',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',50041,NULL,TRUE,now(),5,NULL,'め↓いぶつ',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'評判','ひょうばん','reputasi',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',50042,NULL,TRUE,now(),5,NULL,'ひょうばん○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'～ha','～ヘクタール','～ ha (hektar, 1 ha = 10,000 m2)',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',50043,NULL,TRUE,now(),5,NULL,'～ヘクタ↓ール',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'バーベキュー場','バーベキューじょう','area barbeku (BBQ)',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',50044,NULL,TRUE,now(),5,NULL,'バーベキューじょう○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'サイクリングコース','サイクリングコース','jalur sepeda',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',50045,NULL,TRUE,now(),5,NULL,'サイクリングコ↓ース',NULL,FALSE,FALSE,NULL)
ON CONFLICT (source_book,source_order,term) DO UPDATE SET reading=EXCLUDED.reading,meaning_id=EXCLUDED.meaning_id,accent=EXCLUDED.accent,verb_group=EXCLUDED.verb_group,lesson_number=EXCLUDED.lesson_number,is_verified=TRUE;
