insert into public.vocabulary_source_items
(term,reading,meaning_id,lexical_class,subgroup,source_book,source_order,level_hint,is_verified,lesson_number,lesson_title,verb_group,is_expression,source_section)
values
('町','まち','kota','kata_benda','tempat','Kotoba Irodori A2(1) Buku Oren.pdf',5001,null,true,5,'とてもにぎやかで便利です',null,false,'この町はどうですか？'),
('便利','べんり','praktis','kata_sifat','na_keiyoushi','Kotoba Irodori A2(1) Buku Oren.pdf',5002,null,true,5,'とてもにぎやかで便利です',null,false,'この町はどうですか？'),
('不便','ふべん','tidak praktis','kata_sifat','na_keiyoushi','Kotoba Irodori A2(1) Buku Oren.pdf',5003,null,true,5,'とてもにぎやかで便利です',null,false,'この町はどうですか？'),
('にぎやか','にぎやか','ramai','kata_sifat','na_keiyoushi','Kotoba Irodori A2(1) Buku Oren.pdf',5004,null,true,5,'とてもにぎやかで便利です',null,false,'この町はどうですか？'),
('緑','みどり','pepohonan; tanaman hijau','kata_benda','tempat','Kotoba Irodori A2(1) Buku Oren.pdf',5005,null,true,5,'とてもにぎやかで便利です',null,false,'この町はどうですか？'),
('住みやすい','すみやすい','nyaman untuk ditinggali','kata_sifat','i_keiyoushi','Kotoba Irodori A2(1) Buku Oren.pdf',5006,null,true,5,'とてもにぎやかで便利です',null,false,'この町はどうですか？'),
('店','みせ','toko / restoran','kata_benda','tempat','Kotoba Irodori A2(1) Buku Oren.pdf',5007,null,true,5,'とてもにぎやかで便利です',null,false,'場所は不便だけどきれいですよ'),
('建物','たてもの','bangunan','kata_benda','tempat','Kotoba Irodori A2(1) Buku Oren.pdf',5008,null,true,5,'とてもにぎやかで便利です',null,false,'場所は不便だけどきれいですよ'),
('ショッピングモール','ショッピングモール','pusat perbelanjaan','kata_benda','tempat','Kotoba Irodori A2(1) Buku Oren.pdf',5009,null,true,5,'とてもにぎやかで便利です',null,false,'場所は不便だけどきれいですよ'),
('美しい','うつくしい','indah','kata_sifat','i_keiyoushi','Kotoba Irodori A2(1) Buku Oren.pdf',5010,null,true,5,'とてもにぎやかで便利です',null,false,'タウンマップ'),
('砂浜','すなはま','pantai berpasir','kata_benda','tempat','Kotoba Irodori A2(1) Buku Oren.pdf',5011,null,true,5,'とてもにぎやかで便利です',null,false,'タウンマップ'),
('泳ぐ','およぐ','berenang','kata_kerja','kata_kerja','Kotoba Irodori A2(1) Buku Oren.pdf',5012,null,true,5,'とてもにぎやかで便利です',1,false,'タウンマップ'),
('夕日','ゆうひ','matahari terbenam','kata_benda','waktu','Kotoba Irodori A2(1) Buku Oren.pdf',5013,null,true,5,'とてもにぎやかで便利です',null,false,'タウンマップ'),
('名物','めいぶつ','makanan / produk khas daerah','kata_benda','makanan_minuman','Kotoba Irodori A2(1) Buku Oren.pdf',5014,null,true,5,'とてもにぎやかで便利です',null,false,'タウンマップ'),
('横断歩道','おうだんほどう','penyeberangan pejalan kaki; zebra cross','kata_benda','tempat','Kotoba Irodori A2(1) Buku Oren.pdf',6001,null,true,6,'郵便局はどう行ったらいいですか？',null,false,'バス停はどこですか？'),
('交差点','こうさてん','persimpangan','kata_benda','tempat','Kotoba Irodori A2(1) Buku Oren.pdf',6002,null,true,6,'郵便局はどう行ったらいいですか？',null,false,'バス停はどこですか？'),
('まっすぐ','まっすぐ','lurus','kata_keterangan','kata_keterangan','Kotoba Irodori A2(1) Buku Oren.pdf',6003,null,true,6,'郵便局はどう行ったらいいですか？',null,false,'バス停はどこですか？'),
('曲がる','まがる','berbelok','kata_kerja','kata_kerja','Kotoba Irodori A2(1) Buku Oren.pdf',6004,null,true,6,'郵便局はどう行ったらいいですか？',1,false,'バス停はどこですか？'),
('渡る','わたる','menyeberang','kata_kerja','kata_kerja','Kotoba Irodori A2(1) Buku Oren.pdf',6005,null,true,6,'郵便局はどう行ったらいいですか？',1,false,'バス停はどこですか？'),
('郵便局','ゆうびんきょく','kantor pos','kata_benda','tempat','Kotoba Irodori A2(1) Buku Oren.pdf',6006,null,true,6,'郵便局はどう行ったらいいですか？',null,false,'バス停はどこですか？'),
('銀行','ぎんこう','bank','kata_benda','tempat','Kotoba Irodori A2(1) Buku Oren.pdf',6007,null,true,6,'郵便局はどう行ったらいいですか？',null,false,'そちらに行きたいんですが…'),
('神社','じんじゃ','kuil Shinto','kata_benda','tempat','Kotoba Irodori A2(1) Buku Oren.pdf',6008,null,true,6,'郵便局はどう行ったらいいですか？',null,false,'そちらに行きたいんですが…'),
('駐車場','ちゅうしゃじょう','tempat parkir','kata_benda','tempat','Kotoba Irodori A2(1) Buku Oren.pdf',6009,null,true,6,'郵便局はどう行ったらいいですか？',null,false,'そちらに行きたいんですが…'),
('交番','こうばん','pos polisi','kata_benda','tempat','Kotoba Irodori A2(1) Buku Oren.pdf',6010,null,true,6,'郵便局はどう行ったらいいですか？',null,false,'そちらに行きたいんですが…'),
('病院','びょういん','rumah sakit','kata_benda','tempat','Kotoba Irodori A2(1) Buku Oren.pdf',6011,null,true,6,'郵便局はどう行ったらいいですか？',null,false,'そちらに行きたいんですが…'),
('駅','えき','stasiun','kata_benda','tempat','Kotoba Irodori A2(1) Buku Oren.pdf',7001,null,true,7,'道に迷ってちょっと遅れます',null,false,'何時にどこですか？'),
('受付','うけつけ','resepsionis; meja informasi','kata_benda','tempat','Kotoba Irodori A2(1) Buku Oren.pdf',7002,null,true,7,'道に迷ってちょっと遅れます',null,false,'何時にどこですか？'),
('集合する','しゅうごうする','berkumpul','kata_kerja','kata_kerja','Kotoba Irodori A2(1) Buku Oren.pdf',7003,null,true,7,'道に迷ってちょっと遅れます',3,false,'何時にどこですか？'),
('案内する','あんないする','memandu','kata_kerja','kata_kerja','Kotoba Irodori A2(1) Buku Oren.pdf',7004,null,true,7,'道に迷ってちょっと遅れます',3,false,'何時にどこですか？'),
('待ち合わせ','まちあわせ','janjian bertemu','kata_benda','ekspresi','Kotoba Irodori A2(1) Buku Oren.pdf',7005,null,true,7,'道に迷ってちょっと遅れます',null,false,'何時にどこですか？'),
('事故','じこ','kecelakaan','kata_benda','tempat','Kotoba Irodori A2(1) Buku Oren.pdf',7006,null,true,7,'道に迷ってちょっと遅れます',null,false,'電車が止まりました'),
('止まる','とまる','berhenti','kata_kerja','jidoushi','Kotoba Irodori A2(1) Buku Oren.pdf',7007,null,true,7,'道に迷ってちょっと遅れます',1,false,'電車が止まりました'),
('急ぐ','いそぐ','bergegas','kata_kerja','kata_kerja','Kotoba Irodori A2(1) Buku Oren.pdf',7008,null,true,7,'道に迷ってちょっと遅れます',1,false,'電車が止まりました'),
('道に迷う','みちにまよう','tersesat di jalan; salah jalan','kata_kerja','kata_kerja','Kotoba Irodori A2(1) Buku Oren.pdf',7009,null,true,7,'道に迷ってちょっと遅れます',1,false,'電車が止まりました'),
('遅れる','おくれる','terlambat','kata_kerja','jidoushi','Kotoba Irodori A2(1) Buku Oren.pdf',7010,null,true,7,'道に迷ってちょっと遅れます',2,false,'電車が止まりました'),
('動物園','どうぶつえん','kebun binatang','kata_benda','tempat','Kotoba Irodori A2(1) Buku Oren.pdf',8001,null,true,8,'野球、したことありますか？',null,false,'もう行きましたか？'),
('お城','おしろ','istana','kata_benda','tempat','Kotoba Irodori A2(1) Buku Oren.pdf',8002,null,true,8,'野球、したことありますか？',null,false,'もう行きましたか？'),
('博物館','はくぶつかん','museum','kata_benda','tempat','Kotoba Irodori A2(1) Buku Oren.pdf',8003,null,true,8,'野球、したことありますか？',null,false,'もう行きましたか？'),
('試合','しあい','pertandingan','kata_benda','ekspresi','Kotoba Irodori A2(1) Buku Oren.pdf',8004,null,true,8,'野球、したことありますか？',null,false,'もう行きましたか？'),
('足りない','たりない','tidak cukup; kurang','kata_sifat','i_keiyoushi','Kotoba Irodori A2(1) Buku Oren.pdf',8005,null,true,8,'野球、したことありますか？',null,false,'もう行きましたか？'),
('お金','おかね','uang','kata_benda','angka','Kotoba Irodori A2(1) Buku Oren.pdf',8006,null,true,8,'野球、したことありますか？',null,false,'このあと、どうしますか？'),
('おろす','おろす','menarik / mengambil uang','kata_kerja','kata_kerja','Kotoba Irodori A2(1) Buku Oren.pdf',8007,null,true,8,'野球、したことありますか？',1,false,'このあと、どうしますか？'),
('文字','もじ','huruf','kata_benda','alat_sekolah','Kotoba Irodori A2(1) Buku Oren.pdf',9001,null,true,9,'読み方を教えてもらえませんか？',null,false,'会話は得意です'),
('ひらがな','ひらがな','hiragana','kata_benda','alat_sekolah','Kotoba Irodori A2(1) Buku Oren.pdf',9002,null,true,9,'読み方を教えてもらえませんか？',null,false,'会話は得意です'),
('カタカナ','カタカナ','katakana','kata_benda','alat_sekolah','Kotoba Irodori A2(1) Buku Oren.pdf',9003,null,true,9,'読み方を教えてもらえませんか？',null,false,'会話は得意です'),
('漢字','かんじ','kanji','kata_benda','alat_sekolah','Kotoba Irodori A2(1) Buku Oren.pdf',9004,null,true,9,'読み方を教えてもらえませんか？',null,false,'会話は得意です'),
('文法','ぶんぽう','tata bahasa','kata_benda','alat_sekolah','Kotoba Irodori A2(1) Buku Oren.pdf',9005,null,true,9,'読み方を教えてもらえませんか？',null,false,'会話は得意です'),
('発音','はつおん','pelafalan; pengucapan','kata_benda','alat_sekolah','Kotoba Irodori A2(1) Buku Oren.pdf',9006,null,true,9,'読み方を教えてもらえませんか？',null,false,'会話は得意です'),
('辞書','じしょ','kamus','kata_benda','alat_sekolah','Kotoba Irodori A2(1) Buku Oren.pdf',9007,null,true,9,'読み方を教えてもらえませんか？',null,false,'日本語をチェックしてもらえませんか？'),
('貸す','かす','meminjamkan','kata_kerja','tadoushi','Kotoba Irodori A2(1) Buku Oren.pdf',9008,null,true,9,'読み方を教えてもらえませんか？',1,false,'日本語をチェックしてもらえませんか？'),
('見せる','みせる','memperlihatkan','kata_kerja','tadoushi','Kotoba Irodori A2(1) Buku Oren.pdf',9009,null,true,9,'読み方を教えてもらえませんか？',2,false,'日本語をチェックしてもらえませんか？'),
('説明する','せつめいする','menjelaskan','kata_kerja','kata_kerja','Kotoba Irodori A2(1) Buku Oren.pdf',9010,null,true,9,'読み方を教えてもらえませんか？',3,false,'日本語をチェックしてもらえませんか？'),
('練習','れんしゅう','latihan','kata_benda','alat_sekolah','Kotoba Irodori A2(1) Buku Oren.pdf',9011,null,true,9,'読み方を教えてもらえませんか？',null,false,'いい練習のし方がありますか？'),
('曜日','ようび','hari','kata_benda','waktu','Kotoba Irodori A2(1) Buku Oren.pdf',10001,null,true,10,'教室案内',null,false,'教室案内'),
('費用','ひよう','biaya','kata_benda','angka','Kotoba Irodori A2(1) Buku Oren.pdf',10002,null,true,10,'教室案内',null,false,'教室案内'),
('毎月','まいつき','setiap bulan','kata_keterangan','waktu','Kotoba Irodori A2(1) Buku Oren.pdf',10003,null,true,10,'教室案内',null,false,'料理教室'),
('公民館','こうみんかん','balai kegiatan publik','kata_benda','tempat','Kotoba Irodori A2(1) Buku Oren.pdf',10004,null,true,10,'教室案内',null,false,'料理教室'),
('問い合わせ','といあわせ','informasi lebih lanjut','kata_benda','ekspresi','Kotoba Irodori A2(1) Buku Oren.pdf',10005,null,true,10,'教室案内',null,false,'料理教室'),
('書道','しょどう','kaligrafi Jepang','kata_benda','alat_sekolah','Kotoba Irodori A2(1) Buku Oren.pdf',10006,null,true,10,'教室案内',null,false,'書道教室'),
('日時','にちじ','tanggal; waktu','kata_benda','waktu','Kotoba Irodori A2(1) Buku Oren.pdf',10007,null,true,10,'教室案内',null,false,'書道教室'),
('バーベキュー','バーベキュー','barbeku; BBQ','kata_benda','makanan_minuman','Kotoba Irodori A2(1) Buku Oren.pdf',11001,null,true,11,'肉と野菜は私が買って行きます',null,false,'だれが何を持って行きますか？'),
('牛肉','ぎゅうにく','daging sapi','kata_benda','makanan_minuman','Kotoba Irodori A2(1) Buku Oren.pdf',11002,null,true,11,'肉と野菜は私が買って行きます',null,false,'だれが何を持って行きますか？'),
('豚肉','ぶたにく','daging babi','kata_benda','makanan_minuman','Kotoba Irodori A2(1) Buku Oren.pdf',11003,null,true,11,'肉と野菜は私が買って行きます',null,false,'だれが何を持って行きますか？'),
('鶏肉','とりにく','daging ayam','kata_benda','makanan_minuman','Kotoba Irodori A2(1) Buku Oren.pdf',11004,null,true,11,'肉と野菜は私が買って行きます',null,false,'だれが何を持って行きますか？'),
('ソーセージ','ソーセージ','sosis','kata_benda','makanan_minuman','Kotoba Irodori A2(1) Buku Oren.pdf',11005,null,true,11,'肉と野菜は私が買って行きます',null,false,'だれが何を持って行きますか？'),
('シーフード','シーフード','makanan laut; seafood','kata_benda','makanan_minuman','Kotoba Irodori A2(1) Buku Oren.pdf',11006,null,true,11,'肉と野菜は私が買って行きます',null,false,'だれが何を持って行きますか？'),
('エビ','エビ','udang','kata_benda','makanan_minuman','Kotoba Irodori A2(1) Buku Oren.pdf',11007,null,true,11,'肉と野菜は私が買って行きます',null,false,'だれが何を持って行きますか？'),
('イカ','イカ','cumi-cumi','kata_benda','makanan_minuman','Kotoba Irodori A2(1) Buku Oren.pdf',11008,null,true,11,'肉と野菜は私が買って行きます',null,false,'だれが何を持って行きますか？'),
('りんご','りんご','apel','kata_benda','buah_sayur','Kotoba Irodori A2(1) Buku Oren.pdf',11009,null,true,11,'肉と野菜は私が買って行きます',null,false,'だれが何を持って行きますか？'),
('バナナ','バナナ','pisang','kata_benda','buah_sayur','Kotoba Irodori A2(1) Buku Oren.pdf',11010,null,true,11,'肉と野菜は私が買って行きます',null,false,'だれが何を持って行きますか？'),
('準備','じゅんび','persiapan','kata_benda','ekspresi','Kotoba Irodori A2(1) Buku Oren.pdf',11011,null,true,11,'肉と野菜は私が買って行きます',null,false,'だれが何を持って行きますか？'),
('手伝う','てつだう','membantu','kata_kerja','kata_kerja','Kotoba Irodori A2(1) Buku Oren.pdf',11012,null,true,11,'肉と野菜は私が買って行きます',1,false,'だれが何を持って行きますか？'),
('味','あじ','rasa','kata_benda','makanan_minuman','Kotoba Irodori A2(1) Buku Oren.pdf',12001,null,true,12,'お弁当、おいしそうですね',null,false,'辛そうな料理ですね'),
('甘い','あまい','manis','kata_sifat','i_keiyoushi','Kotoba Irodori A2(1) Buku Oren.pdf',12002,null,true,12,'お弁当、おいしそうですね',null,false,'辛そうな料理ですね'),
('辛い','からい','pedas','kata_sifat','i_keiyoushi','Kotoba Irodori A2(1) Buku Oren.pdf',12003,null,true,12,'お弁当、おいしそうですね',null,false,'辛そうな料理ですね'),
('すっぱい','すっぱい','asam','kata_sifat','i_keiyoushi','Kotoba Irodori A2(1) Buku Oren.pdf',12004,null,true,12,'お弁当、おいしそうですね',null,false,'辛そうな料理ですね'),
('しょっぱい','しょっぱい','asin','kata_sifat','i_keiyoushi','Kotoba Irodori A2(1) Buku Oren.pdf',12005,null,true,12,'お弁当、おいしそうですね',null,false,'辛そうな料理ですね'),
('苦い','にがい','pahit','kata_sifat','i_keiyoushi','Kotoba Irodori A2(1) Buku Oren.pdf',12006,null,true,12,'お弁当、おいしそうですね',null,false,'辛そうな料理ですね'),
('まずい','まずい','tidak enak; tidak lezat','kata_sifat','i_keiyoushi','Kotoba Irodori A2(1) Buku Oren.pdf',12007,null,true,12,'お弁当、おいしそうですね',null,false,'辛そうな料理ですね'),
('電気','でんき','lampu; listrik','kata_benda','alat_dapur','Kotoba Irodori A2(1) Buku Oren.pdf',13001,null,true,13,'あと10分ぐらいで終わりそうです',null,false,'パソコンが動かないんですが…'),
('動く','うごく','bergerak; beroperasi','kata_kerja','jidoushi','Kotoba Irodori A2(1) Buku Oren.pdf',13002,null,true,13,'あと10分ぐらいで終わりそうです',1,false,'パソコンが動かないんですが…'),
('再起動する','さいきどうする','memulai ulang; restart','kata_kerja','kata_kerja','Kotoba Irodori A2(1) Buku Oren.pdf',13003,null,true,13,'あと10分ぐらいで終わりそうです',3,false,'パソコンが動かないんですが…'),
('管理室','かんりしつ','ruang manajemen; ruang kontrol','kata_benda','tempat','Kotoba Irodori A2(1) Buku Oren.pdf',13004,null,true,13,'あと10分ぐらいで終わりそうです',null,false,'パソコンが動かないんですが…'),
('倉庫','そうこ','gudang','kata_benda','tempat','Kotoba Irodori A2(1) Buku Oren.pdf',13005,null,true,13,'あと10分ぐらいで終わりそうです',null,false,'パソコンが動かないんですが…'),
('コピー機','コピーき','mesin fotokopi','kata_benda','alat_sekolah','Kotoba Irodori A2(1) Buku Oren.pdf',13006,null,true,13,'あと10分ぐらいで終わりそうです',null,false,'コピー機の使い方を教えてもらえませんか？'),
('ボタン','ボタン','tombol','kata_benda','alat_sekolah','Kotoba Irodori A2(1) Buku Oren.pdf',13007,null,true,13,'あと10分ぐらいで終わりそうです',null,false,'コピー機の使い方を教えてもらえませんか？'),
('押す','おす','menekan','kata_kerja','tadoushi','Kotoba Irodori A2(1) Buku Oren.pdf',13008,null,true,13,'あと10分ぐらいで終わりそうです',1,false,'コピー機の使い方を教えてもらえませんか？'),
('財​​布','さいふ','dompet','kata_benda','kata_benda','Kotoba Irodori A2(1) Buku Oren.pdf',14001,null,true,14,'休みを取ってもいいでしょうか？',null,false,'少し遅くなります'),
('忘れる','わすれる','lupa','kata_kerja','kata_kerja','Kotoba Irodori A2(1) Buku Oren.pdf',14002,null,true,14,'休みを取ってもいいでしょうか？',2,false,'少し遅くなります'),
('伝える','つたえる','menyampaikan','kata_kerja','tadoushi','Kotoba Irodori A2(1) Buku Oren.pdf',14003,null,true,14,'休みを取ってもいいでしょうか？',2,false,'少し遅くなります'),
('休む','やすむ','cuti; tidak masuk kerja; libur','kata_kerja','kata_kerja','Kotoba Irodori A2(1) Buku Oren.pdf',14004,null,true,14,'休みを取ってもいいでしょうか？',1,false,'少し遅くなります'),
('休憩する','きゅうけいする','rehat; istirahat sejenak','kata_kerja','kata_kerja','Kotoba Irodori A2(1) Buku Oren.pdf',14005,null,true,14,'休みを取ってもいいでしょうか？',3,false,'トイレに行って来てもいいですか？'),
('戻る','もどる','kembali','kata_kerja','jidoushi','Kotoba Irodori A2(1) Buku Oren.pdf',14006,null,true,14,'休みを取ってもいいでしょうか？',1,false,'トイレに行って来てもいいですか？'),
('早退する','そうたいする','pulang lebih awal','kata_kerja','kata_kerja','Kotoba Irodori A2(1) Buku Oren.pdf',14007,null,true,14,'休みを取ってもいいでしょうか？',3,false,'明日の午後、早退してもいいでしょうか？'),
('症状','しょうじょう','gejala penyakit','kata_benda','anggota_tubuh','Kotoba Irodori A2(1) Buku Oren.pdf',15001,null,true,15,'熱があってのどが痛いんです',null,false,'今日はどうしましたか？'),
('のど','のど','tenggorokan','kata_benda','anggota_tubuh','Kotoba Irodori A2(1) Buku Oren.pdf',15002,null,true,15,'熱があってのどが痛いんです',null,false,'今日はどうしましたか？'),
('吐き気','はきけ','mual; rasa ingin muntah','kata_benda','anggota_tubuh','Kotoba Irodori A2(1) Buku Oren.pdf',15003,null,true,15,'熱があってのどが痛いんです',null,false,'今日はどうしましたか？'),
('食欲','しょくよく','nafsu makan','kata_benda','anggota_tubuh','Kotoba Irodori A2(1) Buku Oren.pdf',15004,null,true,15,'熱があってのどが痛いんです',null,false,'今日はどうしましたか？'),
('転ぶ','ころぶ','jatuh','kata_kerja','jidoushi','Kotoba Irodori A2(1) Buku Oren.pdf',15005,null,true,15,'熱があってのどが痛いんです',1,false,'今日はどうしましたか？'),
('保険証','ほけんしょう','kartu asuransi kesehatan','kata_benda','ekspresi','Kotoba Irodori A2(1) Buku Oren.pdf',15006,null,true,15,'熱があってのどが痛いんです',null,false,'インフルエンザですね'),
('薬局','やっきょく','apotek','kata_benda','tempat','Kotoba Irodori A2(1) Buku Oren.pdf',15007,null,true,15,'熱があってのどが痛いんです',null,false,'インフルエンザですね'),
('お大事に','おだいじに','Semoga lekas sembuh.','ekspresi','ekspresi','Kotoba Irodori A2(1) Buku Oren.pdf',15008,null,true,15,'熱があってのどが痛いんです',null,true,'インフルエンザですね'),
('顔','かお','muka; wajah','kata_benda','anggota_tubuh','Kotoba Irodori A2(1) Buku Oren.pdf',16001,null,true,16,'食べすぎないようにしています',null,false,'具合が悪そうですね'),
('肩','かた','bahu','kata_benda','anggota_tubuh','Kotoba Irodori A2(1) Buku Oren.pdf',16002,null,true,16,'食べすぎないようにしています',null,false,'具合が悪そうですね'),
('腰','こし','pinggang','kata_benda','anggota_tubuh','Kotoba Irodori A2(1) Buku Oren.pdf',16003,null,true,16,'食べすぎないようにしています',null,false,'具合が悪そうですね'),
('だるい','だるい','lemas; terlalu letih dan lesu','kata_sifat','i_keiyoushi','Kotoba Irodori A2(1) Buku Oren.pdf',16004,null,true,16,'食べすぎないようにしています',null,false,'具合が悪そうですね'),
('眠れない','ねむれない','tidak bisa tidur','kata_kerja','kata_kerja','Kotoba Irodori A2(1) Buku Oren.pdf',16005,null,true,16,'食べすぎないようにしています',null,false,'具合が悪そうですね'),
('運動','うんどう','olahraga','kata_benda','ekspresi','Kotoba Irodori A2(1) Buku Oren.pdf',16006,null,true,16,'食べすぎないようにしています',null,false,'夜は早く寝るようにしています'),
('歩く','あるく','berjalan','kata_kerja','kata_kerja','Kotoba Irodori A2(1) Buku Oren.pdf',16007,null,true,16,'食べすぎないようにしています',1,false,'夜は早く寝るようにしています'),
('食中毒','しょくちゅうどく','keracunan makanan','kata_benda','makanan_minuman','Kotoba Irodori A2(1) Buku Oren.pdf',16008,null,true,16,'食べすぎないようにしています',null,false,'食中毒が増えています'),
('原因','げんいん','penyebab','kata_benda','ekspresi','Kotoba Irodori A2(1) Buku Oren.pdf',16009,null,true,16,'食べすぎないようにしています',null,false,'食中毒が増えています'),
('予防する','よぼうする','mencegah','kata_kerja','kata_kerja','Kotoba Irodori A2(1) Buku Oren.pdf',16010,null,true,16,'食べすぎないようにしています',3,false,'食中毒が増えています')
on conflict (source_book,source_order,term) do update set
reading=excluded.reading, meaning_id=excluded.meaning_id, lexical_class=excluded.lexical_class, subgroup=excluded.subgroup,
lesson_number=excluded.lesson_number, lesson_title=excluded.lesson_title, verb_group=excluded.verb_group,
is_expression=excluded.is_expression, source_section=excluded.source_section, is_verified=true;
