insert into public.vocabulary_source_items(term,reading,meaning_id,lexical_class,subgroup,source_book,source_order,level_hint,is_verified,lesson_number,lesson_title,accent,verb_group,is_expression,source_section) values
('休み','やすみ','libur',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1700001,null,true,17,'ジョギングをします','やすみ↓',null,false,'Daftar Kosakata'),
('運動する','うんどうする','berolahraga','kata_kerja','kata_kerja','Kotoba Irodori A1 Buku Pink.pdf',1700002,null,true,17,'ジョギングをします','うんどうする○／',3,false,'Daftar Kosakata'),
('服','ふく','pakaian',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1700003,null,true,17,'ジョギングをします','ふく↓',null,false,'Daftar Kosakata'),
('買う','かう','membeli','kata_kerja','kata_kerja','Kotoba Irodori A1 Buku Pink.pdf',1700004,null,true,17,'ジョギングをします','かう○／かいま↓す',1,false,'Daftar Kosakata'),
('家族','かぞく','keluarga',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1700005,null,true,17,'ジョギングをします','か↓ぞく',null,false,'Daftar Kosakata'),
('話す','はなす','berbicara; bercakap-cakap','kata_kerja','kata_kerja','Kotoba Irodori A1 Buku Pink.pdf',1700006,null,true,17,'ジョギングをします','はな↓す／はなしま↓す',1,false,'Daftar Kosakata'),
('コンサート','コンサート','konser',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1700007,null,true,17,'ジョギングをします','コ↓ンサート',null,false,'Daftar Kosakata'),
('ゆっくりする','ゆっくりする','bersantai','kata_kerja','kata_kerja','Kotoba Irodori A1 Buku Pink.pdf',1700008,null,true,17,'ジョギングをします','ゆっく↓りする／',3,false,'Daftar Kosakata'),
('掃除する','そうじする','bersih-bersih','kata_kerja','kata_kerja','Kotoba Irodori A1 Buku Pink.pdf',1700009,null,true,17,'ジョギングをします','そうじする○／',3,false,'Daftar Kosakata'),
('寝る','ねる','tidur','kata_kerja','kata_kerja','Kotoba Irodori A1 Buku Pink.pdf',1700010,null,true,17,'ジョギングをします','ねる○／ねま↓す',2,false,'Daftar Kosakata'),
('週末','しゅうまつ','akhir pekan',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1700011,null,true,17,'ジョギングをします','しゅうまつ○',null,false,'Daftar Kosakata'),
('オーケストラ','オーケストラ','orkestra',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1700012,null,true,17,'ジョギングをします','オーケ↓ストラ',null,false,'Daftar Kosakata'),
('昨日','きのう','kemarin',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1700013,null,true,17,'ジョギングをします','きのう○／きの↓う',null,false,'Daftar Kosakata'),
('土日','どにち','Sabtu dan Minggu',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1700014,null,true,17,'ジョギングをします','どにち○',null,false,'Daftar Kosakata'),
('何も','なにも','apa pun',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1700015,null,true,17,'ジョギングをします','なにも○',null,false,'Daftar Kosakata'),
('勉強','べんきょう','belajar',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1700016,null,true,17,'ジョギングをします','べんきょう○',null,false,'Daftar Kosakata'),
('洗濯','せんたく','cuci baju',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1700017,null,true,17,'ジョギングをします','せんたく○',null,false,'Daftar Kosakata'),
('掃除','そうじ','bersih-bersih',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1700018,null,true,17,'ジョギングをします','そうじ○',null,false,'Daftar Kosakata'),
('国際フェスティバル',null,'festival internasional',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1700019,null,true,17,'ジョギングをします','こくさいフェ↓スティバ',null,false,'Daftar Kosakata'),
('楽しい','たのしい','menyenangkan',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1700020,null,true,17,'ジョギングをします','たのし↓い',null,false,'Daftar Kosakata'),
('おもしろい','おもしろい','menarik',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1700021,null,true,17,'ジョギングをします','おもしろ↓い',null,false,'Daftar Kosakata'),
('いい','いい','bagus',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1700022,null,true,17,'ジョギングをします','い↓い',null,false,'Daftar Kosakata'),
('まあまあ','まあまあ','lumayan','kata_sifat','na_keiyoushi','Kotoba Irodori A1 Buku Pink.pdf',1700023,null,true,17,'ジョギングをします','まあま↓あ（な）',null,false,'Daftar Kosakata'),
('大変','たいへん','sulit; berat','kata_sifat','na_keiyoushi','Kotoba Irodori A1 Buku Pink.pdf',1700024,null,true,17,'ジョギングをします','たいへん（な）○',null,false,'Daftar Kosakata'),
('一日中','いちにちじゅう','sepanjang hari',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1700025,null,true,17,'ジョギングをします','いちにちじゅう○',null,false,'Daftar Kosakata'),
('どこにも','どこにも','mana pun',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1700026,null,true,17,'ジョギングをします','どこにも○',null,false,'Daftar Kosakata'),
('よかった（です）','よかった','Bagus.',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1700027,null,true,17,'ジョギングをします','よ↓かった（です）',null,true,'Daftar Kosakata'),
('すばらしい','すばらしい','menakjubkan; luar biasa',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1700028,null,true,17,'ジョギングをします','すばらし↓い',null,false,'Daftar Kosakata'),
('つまらない','つまらない','membosankan',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1700029,null,true,17,'ジョギングをします','つまら↓ない',null,false,'Daftar Kosakata'),
('いまいち','いまいち','tidak begitu bagus','kata_sifat','na_keiyoushi','Kotoba Irodori A1 Buku Pink.pdf',1700030,null,true,17,'ジョギングをします','いま↓いち（な）',null,false,'Daftar Kosakata'),
('家族で','かぞくで','dengan keluarga',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1700031,null,true,17,'ジョギングをします','か↓ぞくで',null,false,'Daftar Kosakata'),
('ペンギン','ペンギン','penguin',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1700032,null,true,17,'ジョギングをします','ペンギン○',null,false,'Daftar Kosakata'),
('そして','そして','kemudian',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1700033,null,true,17,'ジョギングをします','そして○',null,false,'Daftar Kosakata'),
('クラゲ','クラゲ','ubur-ubur',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1700034,null,true,17,'ジョギングをします','クラゲ○',null,false,'Daftar Kosakata'),
('気持ちいい','きもちいい','nyaman; menyegarkan',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1700035,null,true,17,'ジョギングをします','きもちい↓い',null,false,'Daftar Kosakata'),
('コスモス','コスモス','kenikir',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1700036,null,true,17,'ジョギングをします','コ↓スモス',null,false,'Daftar Kosakata'),
('花','はな','bunga',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1700037,null,true,17,'ジョギングをします','はな↓',null,false,'Daftar Kosakata'),
('多い','おおい','banyak',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1700038,null,true,17,'ジョギングをします','おお↓い',null,false,'Daftar Kosakata'),
('まだまだ','まだまだ','masih',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1700039,null,true,17,'ジョギングをします','ま↓だまだ',null,false,'Daftar Kosakata'),
('元気','げんき','sehat; bugar','kata_sifat','na_keiyoushi','Kotoba Irodori A1 Buku Pink.pdf',1700040,null,true,17,'ジョギングをします','げ↓んき（な）',null,false,'Daftar Kosakata'),
('お祝い','おいわい','perayaan',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1700041,null,true,17,'ジョギングをします','おいわい○',null,false,'Daftar Kosakata'),
('二人で','ふたりで','berdua',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1700042,null,true,17,'ジョギングをします','ふたり↓で',null,false,'Daftar Kosakata'),
('おいしい','おいしい','enak; lezat',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1700043,null,true,17,'ジョギングをします','おいしい○／おいし↓い',null,false,'Daftar Kosakata'),
('大人','おとな','dewasa',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1700044,null,true,17,'ジョギングをします','おとな○／だいにん○',null,false,'Daftar Kosakata'),
('高校生','こうこうせい','siswa SMA',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1700045,null,true,17,'ジョギングをします','こうこ↓うせい',null,false,'Daftar Kosakata'),
('小・中学生','しょうちゅうがくせい','siswa SD dan SMP',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1700046,null,true,17,'ジョギングをします','しょうちゅうが↓くせい',null,false,'Daftar Kosakata'),
('発売中','はつばいちゅう','tersedia (sedang dijual)',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1700047,null,true,17,'ジョギングをします','はつばいちゅう○',null,false,'Daftar Kosakata'),
('入館券','にゅうかんけん','tiket masuk',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1700048,null,true,17,'ジョギングをします','にゅうか↓んけん',null,false,'Daftar Kosakata'),
('一般','いっぱん','umum',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1700049,null,true,17,'ジョギングをします','いっぱん○',null,false,'Daftar Kosakata'),
('大学生','だいがくせい','mahasiswa',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1700050,null,true,17,'ジョギングをします','だいが↓くせい',null,false,'Daftar Kosakata'),
('中人','ちゅうにん','remaja',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1700051,null,true,17,'ジョギングをします','ちゅうにん○',null,false,'Daftar Kosakata'),
('小人','しょうにん','anak-anak',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1700052,null,true,17,'ジョギングをします','しょうにん○',null,false,'Daftar Kosakata'),
('料金','りょうきん','tarif',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1700053,null,true,17,'ジョギングをします','りょ↓うきん',null,false,'Daftar Kosakata'),
('古総湯','こそうゆ','Pemandian Umum Kosoyu',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1700054,null,true,17,'ジョギングをします','こそ↓うゆ',null,false,'Daftar Kosakata'),
('営業時間','えいぎょうじかん','jam operasional',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1700055,null,true,17,'ジョギングをします','えいぎょうじ↓かん',null,false,'Daftar Kosakata'),
('休業日','きゅうぎょうび','hari libur',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1700056,null,true,17,'ジョギングをします','きゅうぎょ↓うび',null,false,'Daftar Kosakata'),
('入浴','にゅうよく','mandi',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1700057,null,true,17,'ジョギングをします','にゅうよく○',null,false,'Daftar Kosakata'),
('毎月','まいつき','setiap bulan',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1700058,null,true,17,'ジョギングをします','まいつき○',null,false,'Daftar Kosakata'),
('正午','しょうご','jam 12 siang; tengah hari',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1700059,null,true,17,'ジョギングをします','しょ↓うご',null,false,'Daftar Kosakata'),
('食べ放題','たべほうだい','makan sepuasnya',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1700060,null,true,17,'ジョギングをします','たべほ↓うだい',null,false,'Daftar Kosakata'),
('飲み放題','のみほうだい','minum sepuasnya',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1700061,null,true,17,'ジョギングをします','のみほ↓うだい',null,false,'Daftar Kosakata'),
('プラス','プラス','tambah',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1700062,null,true,17,'ジョギングをします','プラス○',null,false,'Daftar Kosakata'),
('パック','パック','paket',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1700063,null,true,17,'ジョギングをします','パ↓ック',null,false,'Daftar Kosakata'),
('ブース','ブース','stan; ruangan bersekat',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1700064,null,true,17,'ジョギングをします','ブ↓ース／ブース○',null,false,'Daftar Kosakata'),
('個室','こしつ','ruangan privat',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1700065,null,true,17,'ジョギングをします','こしつ○',null,false,'Daftar Kosakata'),
('料金システム','りょうきんシステム','sistem tarif',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1700066,null,true,17,'ジョギングをします','りょうきんシ↓ステム',null,false,'Daftar Kosakata'),
('基本料金','きほんりょうきん','tarif dasar',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1700067,null,true,17,'ジョギングをします','きほんりょ↓うきん',null,false,'Daftar Kosakata'),
('延長料金','えんちょうりょうきん','biaya perpanjangan',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1700068,null,true,17,'ジョギングをします','えんちょうりょ↓うきん',null,false,'Daftar Kosakata'),
('～毎に （10 分毎に）','～ごとに','per ～ (contoh: per 10 menit)',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1700069,null,true,17,'ジョギングをします','～ご↓とに',null,false,'Daftar Kosakata'),
('いつでも','いつでも','kapan pun; kapan saja',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1700070,null,true,17,'ジョギングをします','いつでも○／い↓つでも',null,false,'Daftar Kosakata'),
('ナイト','ナイト','malam',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1700071,null,true,17,'ジョギングをします','ナ↓イト',null,false,'Daftar Kosakata'),
('鍵付き','かぎつき','dengan kunci',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1700072,null,true,17,'ジョギングをします','かぎつき○',null,false,'Daftar Kosakata'),
('席','せき','kursi',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1700073,null,true,17,'ジョギングをします','せ↓き',null,false,'Daftar Kosakata'),
('完全','かんぜん','benar-benar; sepenuhnya','kata_sifat','na_keiyoushi','Kotoba Irodori A1 Buku Pink.pdf',1700074,null,true,17,'ジョギングをします','かんぜん（な）○',null,false,'Daftar Kosakata'),
('着く','つく','tiba; sampai','kata_kerja','kata_kerja','Kotoba Irodori A1 Buku Pink.pdf',1700075,null,true,17,'ジョギングをします','つ↓く／つきま↓す',1,false,'Daftar Kosakata'),
('はじめて','はじめて','pertama kalinya',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1700076,null,true,17,'ジョギングをします','はじ↓めて',null,false,'Daftar Kosakata'),
('また','また','lagi',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1700077,null,true,17,'ジョギングをします','また○',null,false,'Daftar Kosakata'),
('着きました','つきました','Saya sudah sampai.',null,null,'Kotoba Irodori A1 Buku Pink.pdf',1700078,null,true,17,'ジョギングをします','つきま↓した',null,true,'Daftar Kosakata')
on conflict (source_book,source_order,term) do update set reading=excluded.reading,meaning_id=excluded.meaning_id,lexical_class=excluded.lexical_class,subgroup=excluded.subgroup,lesson_number=excluded.lesson_number,lesson_title=excluded.lesson_title,accent=excluded.accent,verb_group=excluded.verb_group,is_verified=true;
