INSERT INTO public.vocabulary_source_items (id,vocabulary_id,term,reading,meaning_id,lexical_class,subgroup,source_book,source_order,level_hint,is_verified,created_at,lesson_number,lesson_title,accent,verb_group,is_reference,is_expression,source_section) VALUES
(gen_random_uuid(),NULL,'動物園','どうぶつえん','kebun binatang',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',80001,NULL,TRUE,now(),8,NULL,'どうぶつ↓えん',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'お城','おしろ','istana',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',80002,NULL,TRUE,now(),8,NULL,'おしろ○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'レストラン','レストラン','restoran',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',80003,NULL,TRUE,now(),8,NULL,'レ↓ストラン',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'博物館','はくぶつかん','museum',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',80004,NULL,TRUE,now(),8,NULL,'はくぶつ↓かん',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'アウトレットモール','アウトレットモール','outlet mall',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',80005,NULL,TRUE,now(),8,NULL,'アウトレットモ↓ール',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'プロレス','プロレス','gulat profesional',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',80006,NULL,TRUE,now(),8,NULL,'プロレス○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'タワー','タワー','menara',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',80007,NULL,TRUE,now(),8,NULL,'タ↓ワー',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'野球','やきゅう','bisbol',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',80008,NULL,TRUE,now(),8,NULL,'やきゅう○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'もう','もう','sudah',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',80009,NULL,TRUE,now(),8,NULL,'も↓う',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'まだ','まだ','belum',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',80010,NULL,TRUE,now(),8,NULL,'ま↓だ',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'アジア','アジア','Asia',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',80011,NULL,TRUE,now(),8,NULL,'ア↓ジア',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'すごく','すごく','sangat',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',80012,NULL,TRUE,now(),8,NULL,'すご↓く',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'市民体育館','しみんたいいくかん','gimnasium / gedung olahraga publik',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',80013,NULL,TRUE,now(),8,NULL,'しみんたいいく↓かん',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'試合','しあい','pertandingan',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',80014,NULL,TRUE,now(),8,NULL,'しあい○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'やる','やる','melakukan',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',80015,NULL,TRUE,now(),8,NULL,'やる○',1,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'メンバー','メンバー','anggota',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',80016,NULL,TRUE,now(),8,NULL,'メ↓ンバー',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'足りない','たりない','tidak cukup; kurang',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',80017,NULL,TRUE,now(),8,NULL,'たりない○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'無理（な）','むり','tidak mungkin',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',80018,NULL,TRUE,now(),8,NULL,'む↓り（な）',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'わかる','わかる','mengerti',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',80019,NULL,TRUE,now(),8,NULL,'わか↓る',1,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'お金','おかね','uang',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',80020,NULL,TRUE,now(),8,NULL,'おかね○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'おろす','おろす','menarik / mengambil (uang)',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',80021,NULL,TRUE,now(),8,NULL,'おろ↓す',1,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'食事','しょくじ','makan',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',80022,NULL,TRUE,now(),8,NULL,'しょくじ○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'ゲームコーナー','ゲームコーナー','game arcade; pusat permainan arkade',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',80023,NULL,TRUE,now(),8,NULL,'ゲームコ↓ーナー',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'フードコート','フードコート','food court; pujasera (pusat jajanan serbaada)',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',80024,NULL,TRUE,now(),8,NULL,'フードコ↓ート',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'カフェ','カフェ','kafe',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',80025,NULL,TRUE,now(),8,NULL,'カ↓フェ',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'映画館','えいがかん','bioskop',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',80026,NULL,TRUE,now(),8,NULL,'えいが↓かん',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'スポーツ店','スポーツてん','toko peralatan olahraga',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',80027,NULL,TRUE,now(),8,NULL,'スポーツ↓てん',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'このあと','このあと','setelah ini; kemudian',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',80028,NULL,TRUE,now(),8,NULL,'このあ↓と',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'お腹がすく','おなかがすく','merasa lapar',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',80029,NULL,TRUE,now(),8,NULL,'おなかがすく○',1,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'何か','なにか','sesuatu',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',80030,NULL,TRUE,now(),8,NULL,'な↓にか',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'その前に','そのまえに','sebelum itu',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',80031,NULL,TRUE,now(),8,NULL,'そのま↓えに',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'すばらしい','すばらしい','bagus',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',80032,NULL,TRUE,now(),8,NULL,'すばらし↓い',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'難しい','むずかしい','sukar; sulit',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',80033,NULL,TRUE,now(),8,NULL,'むずかしい○／むずかし↓い',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'感動する','かんどうする','terkesan',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',80034,NULL,TRUE,now(),8,NULL,'かんどうする○',3,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'かわいい','かわいい','lucu; manis',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',80035,NULL,TRUE,now(),8,NULL,'かわい↓い',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'展覧会','てんらんかい','pameran',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',80036,NULL,TRUE,now(),8,NULL,'てんら↓んかい',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'パンダ','パンダ','panda',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',80037,NULL,TRUE,now(),8,NULL,'パ↓ンダ',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'サル','サル','kera',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',80038,NULL,TRUE,now(),8,NULL,'サ↓ル',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'現代','げんだい','modern',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',80039,NULL,TRUE,now(),8,NULL,'げ↓んだい',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'作品','さくひん','karya seni',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',80040,NULL,TRUE,now(),8,NULL,'さくひん○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'ホラー映画','ホラーえいが','film horor',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',80041,NULL,TRUE,now(),8,NULL,'ホラーえ↓いが',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'つまらない','つまらない','bosan; membosankan',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',80042,NULL,TRUE,now(),8,NULL,'つまら↓ない',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'退屈（な）','たいくつ','bosan; membosankan',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',80043,NULL,TRUE,now(),8,NULL,'たいくつ（な）○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'いまいち（な）','いまいち','tidak cukup bagus',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',80044,NULL,TRUE,now(),8,NULL,'いま↓いち（な）',NULL,FALSE,FALSE,NULL)
ON CONFLICT (source_book,source_order,term) DO UPDATE SET reading=EXCLUDED.reading,meaning_id=EXCLUDED.meaning_id,accent=EXCLUDED.accent,verb_group=EXCLUDED.verb_group,lesson_number=EXCLUDED.lesson_number,is_verified=TRUE;
