create table if not exists public.quiz_error_reviews (
  id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, question_id uuid not null references public.questions(id) on delete cascade, level text not null, skill text, wrong_count integer not null default 1, last_wrong_at timestamptz not null default now(), resolved_at timestamptz, created_at timestamptz not null default now(), unique(user_id,question_id));
create index if not exists quiz_error_reviews_user_open_idx on public.quiz_error_reviews(user_id,last_wrong_at desc) where resolved_at is null;
alter table public.quiz_error_reviews enable row level security;
create policy "Users manage own quiz error reviews" on public.quiz_error_reviews for all to authenticated using (auth.uid()=user_id) with check (auth.uid()=user_id);
create table if not exists public.study_sessions (id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,started_at timestamptz not null default now(),ended_at timestamptz,active_seconds integer not null default 0 check(active_seconds>=0),source text not null default 'learning',metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
create index if not exists study_sessions_user_started_idx on public.study_sessions(user_id,started_at desc);
alter table public.study_sessions enable row level security;
create policy "Users manage own study sessions" on public.study_sessions for all to authenticated using (auth.uid()=user_id) with check (auth.uid()=user_id);
create or replace function public.get_target_page_metrics() returns jsonb language plpgsql security definer set search_path=public as $$ declare u uuid:=auth.uid(); today_jst date:=(now() at time zone 'Asia/Tokyo')::date; xp_today int:=0; seconds_today int:=0; streak int:=0; d date; due_count int:=0; errors_count int:=0; begin if u is null then return '{}'::jsonb; end if; select coalesce(sum(xp),0) into xp_today from learning_activity where user_id=u and (created_at at time zone 'Asia/Tokyo')::date=today_jst; select coalesce(sum(active_seconds),0) into seconds_today from study_sessions where user_id=u and (started_at at time zone 'Asia/Tokyo')::date=today_jst; select seconds_today+coalesce(sum(duration_seconds),0) into seconds_today from quiz_attempts where user_id=u and completed_at is not null and (completed_at at time zone 'Asia/Tokyo')::date=today_jst; d:=today_jst; loop exit when not exists(select 1 from learning_activity where user_id=u and (created_at at time zone 'Asia/Tokyo')::date=d union all select 1 from quiz_attempts where user_id=u and completed_at is not null and (completed_at at time zone 'Asia/Tokyo')::date=d limit 1); streak:=streak+1; d:=d-1; end loop; select count(*) into due_count from user_item_progress where user_id=u and due_at is not null and due_at<=now(); select count(*) into errors_count from quiz_error_reviews where user_id=u and resolved_at is null; return jsonb_build_object('streak',streak,'xpToday',xp_today,'activeSecondsToday',seconds_today,'dueReviewCount',due_count,'errorReviewCount',errors_count); end $$;
grant execute on function public.get_target_page_metrics() to authenticated;
