-- Historical migration marker restored from Supabase migration history.
-- Version: 20260914033358
-- Name: fix_teacher_participant_profile_name
-- Production already records this migration as applied.
