INSERT INTO public.vocabulary_source_items (id,vocabulary_id,term,reading,meaning_id,lexical_class,subgroup,source_book,source_order,level_hint,is_verified,created_at,lesson_number,lesson_title,accent,verb_group,is_reference,is_expression,source_section) VALUES
(gen_random_uuid(),NULL,'駅','えき','stasiun',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',70001,NULL,TRUE,now(),7,NULL,'え↓き',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'受付','うけつけ','resepsionis; meja informasi',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',70002,NULL,TRUE,now(),7,NULL,'うけつけ○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'ホール','ホール','aula',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',70003,NULL,TRUE,now(),7,NULL,'ホ↓ール',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'会社','かいしゃ','perusahaan',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',70004,NULL,TRUE,now(),7,NULL,'かいしゃ○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'門','もん','gerbang',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',70005,NULL,TRUE,now(),7,NULL,'も↓ん',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'集合（する）','しゅうごう','berkumpul',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',70006,NULL,TRUE,now(),7,NULL,'しゅうごう（する）○',3,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'では','では','jadi',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',70007,NULL,TRUE,now(),7,NULL,'で↓は',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'案内する','あんないする','memandu',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',70008,NULL,TRUE,now(),7,NULL,'あんな↓いする',3,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'待ち合わせ','まちあわせ','janjian bertemu',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',70009,NULL,TRUE,now(),7,NULL,'まちあわせ○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'イベント','イベント','acara',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',70010,NULL,TRUE,now(),7,NULL,'イベント○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'始まる','はじまる','mulai',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',70011,NULL,TRUE,now(),7,NULL,'はじまる○',1,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'スタッフ','スタッフ','staf',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',70012,NULL,TRUE,now(),7,NULL,'スタ↓ッフ',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'～前（30分前）','～まえ','～sebelum (30 menit sebelum)',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',70013,NULL,TRUE,now(),7,NULL,'～まえ（さんじゅっぷ↓んまえ）',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'待ち合わせする','まちあわせする','bertemu (satu sama lain)',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',70014,NULL,TRUE,now(),7,NULL,'まちあわせする○',3,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'平和','へいわ','perdamaian',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',70015,NULL,TRUE,now(),7,NULL,'へいわ○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'鳥','とり','burung',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',70016,NULL,TRUE,now(),7,NULL,'とり○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'像','ぞう','patung',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',70017,NULL,TRUE,now(),7,NULL,'ぞ↓う',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'それ、何ですか？','それ、なんですか？','Apa itu? (Ungkapan konfirmasi yang digunakan untuk bertanya sebaliknya kepada pembicara ketika kita tidak memahami apa yang diucapkan olehnya)',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',70018,NULL,TRUE,now(),7,NULL,'それ○、な↓んですか？',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'止まる','とまる','berhenti',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',70019,NULL,TRUE,now(),7,NULL,'とまる○',1,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'連絡する','れんらくする','menghubungi',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',70020,NULL,TRUE,now(),7,NULL,'れんらくする○',3,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'ねぼうする','ねぼうする','terlambat bangun; kesiangan',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',70021,NULL,TRUE,now(),7,NULL,'ねぼうする○',3,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'今から','いまから','dari sekarang',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',70022,NULL,TRUE,now(),7,NULL,'い↓まから',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'急ぐ','いそぐ','bergegas',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',70023,NULL,TRUE,now(),7,NULL,'いそ↓ぐ',1,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'先に','さきに','lebih dulu',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',70024,NULL,TRUE,now(),7,NULL,'さきに○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'始める','はじめる','mulai; memulai',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',70025,NULL,TRUE,now(),7,NULL,'はじめる○',2,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'道に迷う','みちにまよう','tersesat di jalan; salah jalan',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',70026,NULL,TRUE,now(),7,NULL,'みちにまよ↓う',1,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'遅れる','おくれる','terlambat',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',70027,NULL,TRUE,now(),7,NULL,'おくれる○',2,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'着く','つく','tiba',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',70028,NULL,TRUE,now(),7,NULL,'つ↓く',1,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'大丈夫（な）','だいじょうぶ','tidak apa-apa; tidak masalah',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',70029,NULL,TRUE,now(),7,NULL,'だいじょう↓ぶ（な）',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'時間','じかん','waktu',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',70030,NULL,TRUE,now(),7,NULL,'じかん○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'まちがえる','まちがえる','salah (salah paham)',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',70031,NULL,TRUE,now(),7,NULL,'まちが↓える',2,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'待つ','まつ','menunggu',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',70032,NULL,TRUE,now(),7,NULL,'ま↓つ',1,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'カフェ','カフェ','kafe',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',70033,NULL,TRUE,now(),7,NULL,'カ↓フェ',NULL,FALSE,FALSE,NULL)
ON CONFLICT (source_book,source_order,term) DO UPDATE SET reading=EXCLUDED.reading,meaning_id=EXCLUDED.meaning_id,accent=EXCLUDED.accent,verb_group=EXCLUDED.verb_group,lesson_number=EXCLUDED.lesson_number,is_verified=TRUE;
