INSERT INTO public.vocabulary_source_items (id,vocabulary_id,term,reading,meaning_id,lexical_class,subgroup,source_book,source_order,level_hint,is_verified,created_at,lesson_number,lesson_title,accent,verb_group,is_reference,is_expression,source_section) VALUES
(gen_random_uuid(),NULL,'味','あじ','rasa',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',120001,NULL,TRUE,now(),12,NULL,'あじ○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'甘い','あまい','manis',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',120002,NULL,TRUE,now(),12,NULL,'あまい○／あま↓い',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'辛い','からい','pedas',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',120003,NULL,TRUE,now(),12,NULL,'から↓い',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'すっぱい','すっぱい','asam',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',120004,NULL,TRUE,now(),12,NULL,'すっぱ↓い',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'しょっぱい','しょっぱい','asin',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',120005,NULL,TRUE,now(),12,NULL,'しょっぱ↓い',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'苦い','にがい','pahit',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',120006,NULL,TRUE,now(),12,NULL,'にが↓い',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'こい（味がこい）','こい','kental; kuat (contoh : rasanya kental / kuat / kaya rasa)',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',120007,NULL,TRUE,now(),12,NULL,'こ↓い（あじがこ↓い）',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'うすい（味がうすい）','うすい','hambar (contoh : rasanya hambar)',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',120008,NULL,TRUE,now(),12,NULL,'うすい○／うす↓い',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'まずい','まずい','tidak enak; tidak lezat',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',120009,NULL,TRUE,now(),12,NULL,'まず↓い',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'お弁当','おべんとう','bekal',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',120010,NULL,TRUE,now(),12,NULL,'おべんとう○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'チョコレートバニラクリームラテ','チョコレートバニラクリームラテ','minuman chocolate vanilla cream latte',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',120011,NULL,TRUE,now(),12,NULL,'チョコレートバニラクリームラ↓テ',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'みかん','みかん','jeruk',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',120012,NULL,TRUE,now(),12,NULL,'み↓かん',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'庭','にわ','halaman; pekarangan; taman',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',120013,NULL,TRUE,now(),12,NULL,'にわ○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'とれる','とれる','petik; memetik',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',120014,NULL,TRUE,now(),12,NULL,'とれ↓る',2,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'そんなことない','そんなことない','sebenarnya tidak begitu',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',120015,NULL,TRUE,now(),12,NULL,'そんなこ↓とな↓い',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'卵焼き','たまごやき','tamago-yaki (telur dadar gulung)',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',120016,NULL,TRUE,now(),12,NULL,'たまごやき○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'お好み焼き','おこのみやき','okonomiyaki (panekuk khas Jepang yang isiannya berbagai macam jenis sayur, daging, dan seafood)',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',120017,NULL,TRUE,now(),12,NULL,'おこのみやき○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'梅干し','うめぼし','umeboshi (asinan buah prem Jepang)',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',120018,NULL,TRUE,now(),12,NULL,'うめぼし○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'すき焼き','すきやき','sukiyaki (hidangan rebus yang berisi irisan tipis daging sapi, daun bawang, sayur, dll yang dimasak dalam panci)',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',120019,NULL,TRUE,now(),12,NULL,'すきやき○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'生','なま','mentah',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',120020,NULL,TRUE,now(),12,NULL,'な↓ま',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'もう1つ','もうひとつ','satu lagi',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',120021,NULL,TRUE,now(),12,NULL,'もうひと↓つ',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'お腹がいっぱい（な）','おなかがいっぱい','kenyang',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',120022,NULL,TRUE,now(),12,NULL,'おなかがいっぱい（な）○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'苦手（な）','にがて','tidak suka',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',120023,NULL,TRUE,now(),12,NULL,'にがて（な）○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'どんどん','どんどん','tambah lagi',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',120024,NULL,TRUE,now(),12,NULL,'ど↓んどん',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'茶碗蒸し','ちゃわんむし','chawanmushi (telur kukus khas Jepang)',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',120025,NULL,TRUE,now(),12,NULL,'ちゃわ↓んむし',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'プリン','プリン','puding',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',120026,NULL,TRUE,now(),12,NULL,'プ↓リン',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'だし','だし','dashi (kaldu)',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',120027,NULL,TRUE,now(),12,NULL,'だし↓',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'まあ','まあ','(hmmm) ya mungkin',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',120028,NULL,TRUE,now(),12,NULL,'ま↓あ',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'スープ','スープ','sup',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',120029,NULL,TRUE,now(),12,NULL,'ス↓ープ',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'きのこ','きのこ','jamur',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',120030,NULL,TRUE,now(),12,NULL,'き↓のこ',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'銀杏','ぎんなん','kacang gingko',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',120031,NULL,TRUE,now(),12,NULL,'ぎんな↓ん',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'入れる','いれる','memasukkan',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',120032,NULL,TRUE,now(),12,NULL,'いれる○',2,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'いいにおい','いいにおい','aroma yang lezat',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',120033,NULL,TRUE,now(),12,NULL,'い↓いにお↓い',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'調理方法','ちょうりほうほう','cara memasak',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',120034,NULL,TRUE,now(),12,NULL,'ちょうりほ↓うほう',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'フタ','フタ','tutup',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',120035,NULL,TRUE,now(),12,NULL,'フタ○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'取り出す','とりだす','mengeluarkan',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',120036,NULL,TRUE,now(),12,NULL,'とりだ↓す／とりだす○',1,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'めん','めん','mie',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',120037,NULL,TRUE,now(),12,NULL,'め↓ん',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'熱湯','ねっとう','air mendidih',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',120038,NULL,TRUE,now(),12,NULL,'ねっとう○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'注ぐ','そそぐ','menuangkan',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',120039,NULL,TRUE,now(),12,NULL,'そそぐ○',1,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'お湯','おゆ','air panas',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',120040,NULL,TRUE,now(),12,NULL,'おゆ○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'捨てる','すてる','membuang',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',120041,NULL,TRUE,now(),12,NULL,'すてる○',2,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'かける','かける','menaburkan',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',120042,NULL,TRUE,now(),12,NULL,'かけ↓る',2,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'混ぜる','まぜる','mengaduk',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',120043,NULL,TRUE,now(),12,NULL,'まぜ↓る',2,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'はがす','はがす','melepas',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',120044,NULL,TRUE,now(),12,NULL,'はが↓す',1,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'かやく','かやく','bahan pelengkap (seperti irisan sayur, daging, dll)',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',120045,NULL,TRUE,now(),12,NULL,'かやく○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'あける','あける','mengosongkan isi; memasukkan seluruhnya',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',120046,NULL,TRUE,now(),12,NULL,'あける○',2,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'内側','うちがわ','bagian dalam',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',120047,NULL,TRUE,now(),12,NULL,'うちがわ○',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'線','せん','garis',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',120048,NULL,TRUE,now(),12,NULL,'せ↓ん',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'フタをする','フタをする','menutup (penutup)',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',120049,NULL,TRUE,now(),12,NULL,'フタをする○',3,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'湯切り口','ゆきりぐち','lubang untuk membuang air panas',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',120050,NULL,TRUE,now(),12,NULL,'ゆきり↓ぐち',NULL,FALSE,FALSE,NULL),
(gen_random_uuid(),NULL,'できあがり','できあがり','selesai; siap untuk disantap',NULL,NULL,'Kotoba Irodori A2(1) Buku Oren.pdf',120051,NULL,TRUE,now(),12,NULL,'できあがり○',NULL,FALSE,FALSE,NULL)
ON CONFLICT (source_book,source_order,term) DO UPDATE SET reading=EXCLUDED.reading,meaning_id=EXCLUDED.meaning_id,accent=EXCLUDED.accent,verb_group=EXCLUDED.verb_group,lesson_number=EXCLUDED.lesson_number,is_verified=TRUE;
