import { useMemo, useState } from "react";
import { CheckCircle2, XCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { QuestionPrompt } from "@/components/simulation/QuestionPrompt";
import { cn } from "@/lib/utils";
import type { RunnerQuestion } from "@/lib/learn-queries";

export type QuizResult = { total:number; correct:number; durationSeconds:number; answers:Array<{questionId:string;selectedIndex:number;isCorrect:boolean}> };

export function QuizRunner({questions,onFinish,scoreStyle="percent",children}:{questions:RunnerQuestion[];onFinish?:(result:QuizResult)=>void;scoreStyle?:"percent"|"jlpt";children?:React.ReactNode}){
 const [index,setIndex]=useState(0); const [selected,setSelected]=useState<number|null>(null); const [revealed,setRevealed]=useState(false); const [answers,setAnswers]=useState<QuizResult["answers"]>([]); const [done,setDone]=useState(false); const [startedAt]=useState(()=>Date.now());
 const current=questions[index]; const correctCount=answers.filter(a=>a.isCorrect).length;
 const scoreLabel=useMemo(()=>{if(!questions.length)return "0";const ratio=correctCount/questions.length;return scoreStyle==="jlpt"?`${Math.round(ratio*180)} / 180`:`${Math.round(ratio*100)}%`},[correctCount,questions.length,scoreStyle]);
 if(!questions.length)return <Card><CardHeader><CardTitle className="text-base">Belum ada soal</CardTitle><CardDescription>Soal untuk bagian ini belum tersedia.</CardDescription></CardHeader></Card>;
 function submitChoice(){if(selected===null||!current)return;const isCorrect=selected===current.correct_index;setAnswers(prev=>[...prev,{questionId:current.id,selectedIndex:selected,isCorrect}]);setRevealed(true)}
 function next(){if(!current)return;const isLast=index+1>=questions.length;if(isLast){const lastAnswer=selected===null?null:{questionId:current.id,selectedIndex:selected,isCorrect:selected===current.correct_index};const finalAnswers=lastAnswer?[...answers.filter(a=>a.questionId!==current.id),lastAnswer]:answers;setAnswers(finalAnswers);setDone(true);onFinish?.({total:questions.length,correct:finalAnswers.filter(a=>a.isCorrect).length,durationSeconds:Math.round((Date.now()-startedAt)/1000),answers:finalAnswers});return}setIndex(i=>i+1);setSelected(null);setRevealed(false)}
 function restart(){setIndex(0);setSelected(null);setRevealed(false);setAnswers([]);setDone(false)}
 if(done){const passed=correctCount/questions.length>=.6;return <div className="space-y-4 eno-rise"><Card className={passed?"eno-pop":"eno-rise"}><CardHeader><CardTitle>Hasil</CardTitle><CardDescription>{correctCount} benar dari {questions.length} soal</CardDescription></CardHeader><CardContent className="space-y-4"><p className={cn("text-4xl font-semibold text-primary",passed&&"eno-bounce")}>{scoreLabel}</p><p className="text-sm text-muted-foreground">{passed?"Bagus! Ulangi materi yang masih sulit agar semakin kuat.":"Belum mencapai 60%. Pelajari kembali materi lalu coba lagi."}</p><Button onClick={restart} variant="outline">Ulangi</Button></CardContent></Card><Card className="eno-rise"><CardHeader><CardTitle className="text-base">Tinjauan jawaban</CardTitle></CardHeader><CardContent className="space-y-4">{questions.map((q,i)=>{const a=answers[i];return <div key={q.id} className={cn("rounded-lg border border-border/70 p-3",a?.isCorrect?"eno-pop":"eno-rise")}><div className="flex items-start gap-2">{a?.isCorrect?<CheckCircle2 aria-hidden className="mt-0.5 size-4 text-primary eno-bounce"/>:<XCircle aria-hidden className="mt-0.5 size-4 text-destructive"/>}<p className="text-sm font-medium" lang="ja">{q.prompt}</p></div><p className="mt-2 text-xs text-muted-foreground">Jawabanmu: {a?q.choices[a.selectedIndex]:"-"} · Jawaban benar: <span className="text-foreground">{q.choices[q.correct_index]}</span></p>{q.explanation_id?<p className="mt-1 text-xs leading-5 text-muted-foreground">{q.explanation_id}</p>:null}</div>})}</CardContent></Card></div>}
 const selectedCorrect=revealed&&selected===current?.correct_index;
 return <div className="space-y-4 eno-rise">{children}<div><Progress value={((index+(revealed?1:0))/questions.length)*100}/><p className="mt-2 text-xs text-muted-foreground">Soal {index+1} dari {questions.length}</p></div><Card className={revealed?(selectedCorrect?"eno-bounce":"eno-shake"):""}><CardHeader><CardTitle className="text-base leading-relaxed"><QuestionPrompt text={current?.prompt ?? ""}/></CardTitle>{current?.prompt_note?<CardDescription>{current.prompt_note}</CardDescription>:null}</CardHeader><CardContent className="space-y-2">{current?.choices.map((choice,i)=>{const isCorrect=i===current.correct_index;const isSelected=i===selected;return <button key={i} type="button" disabled={revealed} onClick={()=>setSelected(i)} aria-pressed={isSelected} className={cn("flex w-full items-center justify-between rounded-lg border px-4 py-3 text-left text-sm transition-colors","border-border/70 hover:border-primary/60",isSelected&&!revealed&&"border-primary bg-primary/10 eno-pop",revealed&&isCorrect&&"border-primary bg-primary/15 eno-bounce",revealed&&isSelected&&!isCorrect&&"border-destructive bg-destructive/10 eno-shake")}><span lang="ja">{choice}</span>{revealed&&isCorrect?<CheckCircle2 className="size-4 text-primary eno-pop"/>:revealed&&isSelected&&!isCorrect?<XCircle className="size-4 text-destructive eno-pop"/>:null}</button>})}{revealed&&current?.explanation_id?<p className="rounded-lg bg-muted/40 p-3 text-xs leading-5 text-muted-foreground eno-rise">{current.explanation_id}</p>:null}<div className="pt-2">{revealed?<Button onClick={next} className="eno-pop">{index+1>=questions.length?"Lihat hasil":"Soal berikutnya"}</Button>:<Button onClick={submitChoice} disabled={selected===null}>Jawab</Button>}</div></CardContent></Card></div>;
}
